-- ==============================================================================
-- PROCESO: CA_CONSENTIMIENTO_DIARIO (Consentimientos LPDP del Mes)
-- OPTIMIZACIÓN: Se reemplazan los NOT IN lentos por NOT EXISTS, y se simplifica la 
--               lógica compleja de concatenación de códigos utilizando COALESCE.
--               Se define un borrado completo automático al inicio de mes por orquestación.
-- ==============================================================================

-- Si es inicio de mes, la aplicación ejecutará un DELETE general para limpiar el acumulado.
-- DELETE FROM DLAB_GEC.M_EXP_CONSENTIMIENTO_PP ALL;
-- DELETE FROM DLAB_GEC.M_EXP_CONSENTIMIENTO_TC ALL;
-- DELETE FROM DLAB_GEC.M_EXP_CONSENTIMIENTO_EC ALL;
-- DELETE FROM DLAB_GEC.M_EXP_CONSENTIMIENTO_CD ALL;
-- DELETE FROM DLAB_GEC.M_EXP_CONSENTIMIENTO_CON ALL;
-- DELETE FROM DLAB_GEC.M_EXP_CONSENTIMIENTO_IL ALL;
-- DELETE FROM DLAB_GEC.M_EXP_CONSENTIMIENTO_UPG ALL;
-- DELETE FROM DLAB_GEC.M_EXP_CONSENTIMIENTO_DPP ALL;
-- DELETE FROM DLAB_GEC.M_EXP_CONSENTIMIENTO_DTC ALL;
-- DELETE FROM DLAB_GEC.M_EXP_CONSENTIMIENTO_DEC ALL;
-- DELETE FROM DLAB_GEC.M_EXP_CONSENTIMIENTO_DCD ALL;
-- DELETE FROM DLAB_GEC.M_EXP_CONSENTIMIENTO_DPRT ALL;

-- PP (Préstamos Personales)
INSERT INTO DLAB_GEC.M_EXP_CONSENTIMIENTO_PP (TIP_CLIENTE, NUM_DOCUMENTO, FLAG_CONS, USERFIELD5, CODE, UPDATED)
SELECT 
    DISTINCT TIP_CLIENTE, 
    NUMERO_DOCUMENTO AS NUM_DOCUMENTO, 
    VARIABLE_26 AS FLAG_CONS, 
    USERFIELD5,
    CONCAT(TIP_CLIENTE, '_', CAST(NUMERO_DOCUMENTO AS VARCHAR(11)), '_', COALESCE(VARIABLE_26, ''), '_', CAST(USERFIELD5 AS VARCHAR(20))) AS CODE,
    CURRENT_DATE() AS UPDATED
FROM DLAB_GEC.TLV_CARGA_ACTUAL A
WHERE TIP_CLIENTE = 'PP'
  AND NOT EXISTS (
      SELECT 1 FROM DLAB_GEC.M_EXP_CONSENTIMIENTO_PP B 
      WHERE B.CODE = CONCAT(A.TIP_CLIENTE, '_', CAST(A.NUMERO_DOCUMENTO AS VARCHAR(11)), '_', COALESCE(A.VARIABLE_26, ''), '_', CAST(A.USERFIELD5 AS VARCHAR(20)))
  );

-- TC (Tarjetas de Crédito)
INSERT INTO DLAB_GEC.M_EXP_CONSENTIMIENTO_TC (TIP_CLIENTE, NUM_DOCUMENTO, FLAG_CONS, USERFIELD5, CODE, UPDATED)
SELECT 
    DISTINCT 'TC' AS TIP_CLIENTE, 
    NUMERO_DOCUMENTO AS NUM_DOCUMENTO, 
    VARIABLE_26 AS FLAG_CONS, 
    USERFIELD5,
    CONCAT('TC', '_', CAST(NUMERO_DOCUMENTO AS VARCHAR(11)), '_', COALESCE(VARIABLE_26, ''), '_', CAST(USERFIELD5 AS VARCHAR(20))) AS CODE,
    CURRENT_DATE() AS UPDATED
FROM DLAB_GEC.TLV_CARGA_ACTUAL A
WHERE TIP_CLIENTE IN ('C','NC','2DA')
  AND NOT EXISTS (
      SELECT 1 FROM DLAB_GEC.M_EXP_CONSENTIMIENTO_TC B 
      WHERE B.CODE = CONCAT('TC', '_', CAST(A.NUMERO_DOCUMENTO AS VARCHAR(11)), '_', COALESCE(A.VARIABLE_26, ''), '_', CAST(A.USERFIELD5 AS VARCHAR(20)))
  );

-- EC (Extra Cash)
INSERT INTO DLAB_GEC.M_EXP_CONSENTIMIENTO_EC (TIP_CLIENTE, NUM_DOCUMENTO, FLAG_CONS, USERFIELD5, CODE, UPDATED)
SELECT 
    DISTINCT TIP_CLIENTE, 
    NUMERO_DOCUMENTO AS NUM_DOCUMENTO, 
    VARIABLE_26 AS FLAG_CONS, 
    USERFIELD5,
    CONCAT(TIP_CLIENTE, '_', CAST(NUMERO_DOCUMENTO AS VARCHAR(11)), '_', COALESCE(VARIABLE_26, ''), '_', CAST(USERFIELD5 AS VARCHAR(20))) AS CODE,
    CURRENT_DATE() AS UPDATED
FROM DLAB_GEC.TLV_CARGA_ACTUAL A
WHERE TIP_CLIENTE = 'EC'
  AND NOT EXISTS (
      SELECT 1 FROM DLAB_GEC.M_EXP_CONSENTIMIENTO_EC B 
      WHERE B.CODE = CONCAT(A.TIP_CLIENTE, '_', CAST(A.NUMERO_DOCUMENTO AS VARCHAR(11)), '_', COALESCE(A.VARIABLE_26, ''), '_', CAST(A.USERFIELD5 AS VARCHAR(20)))
  );

-- CD (Compra de Deuda)
INSERT INTO DLAB_GEC.M_EXP_CONSENTIMIENTO_CD (TIP_CLIENTE, NUM_DOCUMENTO, FLAG_CONS, USERFIELD5, CODE, UPDATED)
SELECT 
    DISTINCT TIP_CLIENTE, 
    NUMERO_DOCUMENTO AS NUM_DOCUMENTO, 
    VARIABLE_26 AS FLAG_CONS, 
    USERFIELD5,
    CONCAT(TIP_CLIENTE, '_', CAST(NUMERO_DOCUMENTO AS VARCHAR(11)), '_', COALESCE(VARIABLE_26, ''), '_', CAST(USERFIELD5 AS VARCHAR(20))) AS CODE,
    CURRENT_DATE() AS UPDATED
FROM DLAB_GEC.TLV_CARGA_ACTUAL A
WHERE TIP_CLIENTE = 'CD'
  AND NOT EXISTS (
      SELECT 1 FROM DLAB_GEC.M_EXP_CONSENTIMIENTO_CD B 
      WHERE B.CODE = CONCAT(A.TIP_CLIENTE, '_', CAST(A.NUMERO_DOCUMENTO AS VARCHAR(11)), '_', COALESCE(A.VARIABLE_26, ''), '_', CAST(A.USERFIELD5 AS VARCHAR(20)))
  );

-- CON (Convenios)
INSERT INTO DLAB_GEC.M_EXP_CONSENTIMIENTO_CON (TIP_CLIENTE, NUM_DOCUMENTO, FLAG_CONS, USERFIELD5, CODE, UPDATED)
SELECT 
    DISTINCT TIP_CLIENTE, 
    NUMERO_DOCUMENTO AS NUM_DOCUMENTO, 
    VARIABLE_26 AS FLAG_CONS, 
    USERFIELD5,
    CONCAT(TIP_CLIENTE, '_', CAST(NUMERO_DOCUMENTO AS VARCHAR(11)), '_', COALESCE(VARIABLE_26, ''), '_', CAST(USERFIELD5 AS VARCHAR(20))) AS CODE,
    CURRENT_DATE() AS UPDATED
FROM DLAB_GEC.TLV_CARGA_ACTUAL A
WHERE TIP_CLIENTE = 'CON'
  AND NOT EXISTS (
      SELECT 1 FROM DLAB_GEC.M_EXP_CONSENTIMIENTO_CON B 
      WHERE B.CODE = CONCAT(A.TIP_CLIENTE, '_', CAST(A.NUMERO_DOCUMENTO AS VARCHAR(11)), '_', COALESCE(A.VARIABLE_26, ''), '_', CAST(A.USERFIELD5 AS VARCHAR(20)))
  );

-- IL (Incremento de Línea)
INSERT INTO DLAB_GEC.M_EXP_CONSENTIMIENTO_IL (TIP_CLIENTE, NUM_DOCUMENTO, FLAG_ILS, USERFIELD5, CODE, UPDATED)
SELECT 
    DISTINCT TIP_CLIENTE, 
    NUMERO_DOCUMENTO AS NUM_DOCUMENTO, 
    VARIABLE_26 AS FLAG_ILS, 
    USERFIELD5,
    CONCAT(TIP_CLIENTE, '_', CAST(NUMERO_DOCUMENTO AS VARCHAR(11)), '_', COALESCE(VARIABLE_26, ''), '_', CAST(USERFIELD5 AS VARCHAR(20))) AS CODE,
    CURRENT_DATE() AS UPDATED
FROM DLAB_GEC.TLV_CARGA_ACTUAL A
WHERE TIP_CLIENTE = 'IL'
  AND NOT EXISTS (
      SELECT 1 FROM DLAB_GEC.M_EXP_CONSENTIMIENTO_IL B 
      WHERE B.CODE = CONCAT(A.TIP_CLIENTE, '_', CAST(A.NUMERO_DOCUMENTO AS VARCHAR(11)), '_', COALESCE(A.VARIABLE_26, ''), '_', CAST(A.USERFIELD5 AS VARCHAR(20)))
  );

-- UPG (Upgrade)
INSERT INTO DLAB_GEC.M_EXP_CONSENTIMIENTO_UPG (TIP_CLIENTE, NUM_DOCUMENTO, FLAG_ILS, USERFIELD5, CODE, UPDATED)
SELECT 
    DISTINCT TIP_CLIENTE, 
    NUMERO_DOCUMENTO AS NUM_DOCUMENTO, 
    VARIABLE_26 AS FLAG_ILS, 
    USERFIELD5,
    CONCAT(TIP_CLIENTE, '_', CAST(NUMERO_DOCUMENTO AS VARCHAR(11)), '_', COALESCE(VARIABLE_26, ''), '_', CAST(USERFIELD5 AS VARCHAR(20))) AS CODE,
    CURRENT_DATE() AS UPDATED
FROM DLAB_GEC.TLV_CARGA_ACTUAL A
WHERE TIP_CLIENTE = 'UPG'
  AND NOT EXISTS (
      SELECT 1 FROM DLAB_GEC.M_EXP_CONSENTIMIENTO_UPG B 
      WHERE B.CODE = CONCAT(A.TIP_CLIENTE, '_', CAST(A.NUMERO_DOCUMENTO AS VARCHAR(11)), '_', COALESCE(A.VARIABLE_26, ''), '_', CAST(A.USERFIELD5 AS VARCHAR(20)))
  );

-- DPP (Digital Préstamos)
INSERT INTO DLAB_GEC.M_EXP_CONSENTIMIENTO_DPP (TIP_CLIENTE, NUM_DOCUMENTO, FLAG_CONS, USERFIELD5, CODE, UPDATED)
SELECT 
    DISTINCT TIP_CLIENTE, 
    NUMERO_DOCUMENTO AS NUM_DOCUMENTO, 
    VARIABLE_26 AS FLAG_CONS, 
    USERFIELD5,
    CONCAT(TIP_CLIENTE, '_', CAST(NUMERO_DOCUMENTO AS VARCHAR(11)), '_', COALESCE(VARIABLE_26, ''), '_', CAST(USERFIELD5 AS VARCHAR(20))) AS CODE,
    CURRENT_DATE() AS UPDATED
FROM DLAB_GEC.TLV_CARGA_ACTUAL_DIGITAL_PRC A
WHERE TIP_CLIENTE = 'DPP'
  AND NOT EXISTS (
      SELECT 1 FROM DLAB_GEC.M_EXP_CONSENTIMIENTO_DPP B 
      WHERE B.CODE = CONCAT(A.TIP_CLIENTE, '_', CAST(A.NUMERO_DOCUMENTO AS VARCHAR(11)), '_', COALESCE(A.VARIABLE_26, ''), '_', CAST(A.USERFIELD5 AS VARCHAR(20)))
  );

-- DTC (Digital Tarjetas)
INSERT INTO DLAB_GEC.M_EXP_CONSENTIMIENTO_DTC (TIP_CLIENTE, NUM_DOCUMENTO, FLAG_CONS, USERFIELD5, CODE, UPDATED)
SELECT 
    DISTINCT TIP_CLIENTE, 
    NUMERO_DOCUMENTO AS NUM_DOCUMENTO, 
    VARIABLE_26 AS FLAG_CONS, 
    USERFIELD5,
    CONCAT(TIP_CLIENTE, '_', CAST(NUMERO_DOCUMENTO AS VARCHAR(11)), '_', COALESCE(VARIABLE_26, ''), '_', CAST(USERFIELD5 AS VARCHAR(20))) AS CODE,
    CURRENT_DATE() AS UPDATED
FROM DLAB_GEC.TLV_CARGA_ACTUAL_DIGITAL_PRC A
WHERE TIP_CLIENTE = 'DTC'
  AND NUMERO_DOCUMENTO NOT IN ('callback', 'ELMEROSCARRUIZRODRIGUEZ')
  AND NOT EXISTS (
      SELECT 1 FROM DLAB_GEC.M_EXP_CONSENTIMIENTO_DTC B 
      WHERE B.CODE = CONCAT(A.TIP_CLIENTE, '_', CAST(A.NUMERO_DOCUMENTO AS VARCHAR(11)), '_', COALESCE(A.VARIABLE_26, ''), '_', CAST(A.USERFIELD5 AS VARCHAR(20)))
  );

-- DEC (Digital Extra Cash)
INSERT INTO DLAB_GEC.M_EXP_CONSENTIMIENTO_DEC (TIP_CLIENTE, NUM_DOCUMENTO, FLAG_CONS, USERFIELD5, CODE, UPDATED)
SELECT 
    DISTINCT TIP_CLIENTE, 
    NUMERO_DOCUMENTO AS NUM_DOCUMENTO, 
    VARIABLE_26 AS FLAG_CONS, 
    USERFIELD5,
    CONCAT(TIP_CLIENTE, '_', CAST(NUMERO_DOCUMENTO AS VARCHAR(11)), '_', COALESCE(VARIABLE_26, ''), '_', CAST(USERFIELD5 AS VARCHAR(20))) AS CODE,
    CURRENT_DATE() AS UPDATED
FROM DLAB_GEC.TLV_CARGA_ACTUAL_DIGITAL_PRC A
WHERE TIP_CLIENTE = 'DEC'
  AND NOT EXISTS (
      SELECT 1 FROM DLAB_GEC.M_EXP_CONSENTIMIENTO_DEC B 
      WHERE B.CODE = CONCAT(A.TIP_CLIENTE, '_', CAST(A.NUMERO_DOCUMENTO AS VARCHAR(11)), '_', COALESCE(A.VARIABLE_26, ''), '_', CAST(A.USERFIELD5 AS VARCHAR(20)))
  );

-- DCD (Digital Compra Deuda)
INSERT INTO DLAB_GEC.M_EXP_CONSENTIMIENTO_DCD (TIP_CLIENTE, NUM_DOCUMENTO, FLAG_CONS, USERFIELD5, CODE, UPDATED)
SELECT 
    DISTINCT TIP_CLIENTE, 
    NUMERO_DOCUMENTO AS NUM_DOCUMENTO, 
    VARIABLE_26 AS FLAG_CONS, 
    USERFIELD5,
    CONCAT(TIP_CLIENTE, '_', CAST(NUMERO_DOCUMENTO AS VARCHAR(11)), '_', COALESCE(VARIABLE_26, ''), '_', CAST(USERFIELD5 AS VARCHAR(20))) AS CODE,
    CURRENT_DATE() AS UPDATED
FROM DLAB_GEC.TLV_CARGA_ACTUAL_DIGITAL_PRC A
WHERE TIP_CLIENTE = 'DCD'
  AND NOT EXISTS (
      SELECT 1 FROM DLAB_GEC.M_EXP_CONSENTIMIENTO_DCD B 
      WHERE B.CODE = CONCAT(A.TIP_CLIENTE, '_', CAST(A.NUMERO_DOCUMENTO AS VARCHAR(11)), '_', COALESCE(A.VARIABLE_26, ''), '_', CAST(A.USERFIELD5 AS VARCHAR(20)))
  );

-- DPRT (Digital Portafolio)
INSERT INTO DLAB_GEC.M_EXP_CONSENTIMIENTO_DPRT (TIP_CLIENTE, NUM_DOCUMENTO, FLAG_CONS, USERFIELD5, CODE, UPDATED)
SELECT 
    DISTINCT TIP_CLIENTE, 
    NUMERO_DOCUMENTO AS NUM_DOCUMENTO, 
    VARIABLE_26 AS FLAG_CONS, 
    USERFIELD5,
    CONCAT(TIP_CLIENTE, '_', CAST(NUMERO_DOCUMENTO AS VARCHAR(11)), '_', COALESCE(VARIABLE_26, ''), '_', CAST(USERFIELD5 AS VARCHAR(20))) AS CODE,
    CURRENT_DATE() AS UPDATED
FROM DLAB_GEC.TLV_CARGA_ACTUAL_DIGITAL_PRC A
WHERE TIP_CLIENTE IN ('DIL','DUPG','DTCA','DPA')
  AND NOT EXISTS (
      SELECT 1 FROM DLAB_GEC.M_EXP_CONSENTIMIENTO_DPRT B 
      WHERE B.CODE = CONCAT(A.TIP_CLIENTE, '_', CAST(A.NUMERO_DOCUMENTO AS VARCHAR(11)), '_', COALESCE(A.VARIABLE_26, ''), '_', CAST(A.USERFIELD5 AS VARCHAR(20)))
  );
