-- ==============================================================================
-- PROCESO: CD40K (Filtro Créditos > 40K y Crossovers)
-- OPTIMIZACIÓN: 
--   1. Reemplazo de updates por cálculo inline y cruce con LEFT JOINs.
--   2. Uso de QUALIFY nativo de Teradata para deduplicar subconsultas.
--   3. Recolección de estadísticas al terminar.
-- ==============================================================================

DELETE FROM DLAB_GEC.M_EXP_CD40K ALL;

INSERT INTO DLAB_GEC.M_EXP_CD40K (
    MESDESEMBOLSO, TIP_CLIENTE, COD_SOLICITUD, CODDOC, FECDESEMB, CODPROMOT, 
    NOMPROMOT, NOMSUPER, FLAG_CD40, NE_COD_EXPE, CD_MONTO, CD_NUM_TC, CD_ENTIDAD, 
    EECC, EVALUADO
)
SELECT
    A.MESDESEMBOLSO,
    A.TIP_CLIENTE,
    A.COD_SOLICITUD,
    TRIM(A.CODDOC) AS CODDOC,
    A.FECDESEMBOLSO AS FECDESEMB,
    TRIM(A.CODPROMOT) AS CODPROMOT,
    A.NOMPROMOT,
    'VASQUEZ MALCA MIGUEL ANGEL' AS NOMSUPER,
    A.FLAG_CD40,
    B.NE_COD_EXPE,
    ROUND(CAST(B.ND_MONTO AS FLOAT), 2) AS CD_MONTO,
    TRIM(B.CA_NRO_TARJ_PREST) AS CD_NUM_TC,
    B.CA_ENTIDAD AS CD_ENTIDAD,
    CASE 
        WHEN (eecc_sp.DNI_CLIENTE IS NOT NULL) OR (eecc_linea.DNI_CLIENTE IS NOT NULL) THEN 'SI'
        ELSE 'NO'
    END AS EECC,
    CASE 
        WHEN eval.DOCUMENTO IS NOT NULL THEN 'SI'
        ELSE 'NO'
    END AS EVALUADO
FROM DLAB_GEC.M_EXP_VENTAS_CD A
LEFT JOIN (
    SELECT DISTINCT NE_COD_EXPE, ND_MONTO, CA_NRO_TARJ_PREST, CA_ENTIDAD 
    FROM E_DW_VIEWS.V_RSK_ADQ_BTCH_COMPRA_DEUDA
    WHERE NE_COD_EXPE IN (SELECT COD_SOLICITUD FROM DLAB_GEC.M_EXP_VENTAS_CD)
      AND ND_MONTO >= 40000
      AND CA_NRO_TARJ_PREST IS NOT NULL
) B
  ON A.COD_SOLICITUD = B.NE_COD_EXPE 
-- Cruce 1 para EECC (por DNI, Ejecutivo y últimos 4 dígitos de TC) con QUALIFY
LEFT JOIN (
    SELECT DNI_CLIENTE, REG_EJECUTIVO, RIGHT(CD_NUMERO_TC, 4) AS ult4
    FROM DLAB_GEC.T_SP_CD40K
    QUALIFY ROW_NUMBER() OVER (PARTITION BY DNI_CLIENTE, REG_EJECUTIVO, RIGHT(CD_NUMERO_TC, 4) ORDER BY DNI_CLIENTE) = 1
) eecc_sp
  ON TRIM(A.CODDOC) = eecc_sp.DNI_CLIENTE
 AND TRIM(A.CODPROMOT) = eecc_sp.REG_EJECUTIVO
 AND RIGHT(TRIM(B.CA_NRO_TARJ_PREST), 4) = eecc_sp.ult4
-- Cruce 2 para EECC (por DNI, Ejecutivo y últimos 4 de la Línea Paralela) con QUALIFY
LEFT JOIN (
    SELECT DNI_CLIENTE, REG_EJECUTIVO, RIGHT("LINEA PARALELA", 4) AS ult4_par
    FROM DLAB_GEC.T_SP_CD40K
    QUALIFY ROW_NUMBER() OVER (PARTITION BY DNI_CLIENTE, REG_EJECUTIVO, CD_NUMERO_TC, "LINEA PARALELA" ORDER BY DNI_CLIENTE) = 1
) eecc_linea
  ON TRIM(A.CODDOC) = eecc_linea.DNI_CLIENTE
 AND TRIM(A.CODPROMOT) = eecc_linea.REG_EJECUTIVO
 AND RIGHT(TRIM(B.CA_NRO_TARJ_PREST), 4) = eecc_linea.ult4_par
-- Cruce para indicar si el cliente ya fue Evaluado
LEFT JOIN DLAB_GEC.M_EXP_DOCUMENTOS_EVALUADOS eval
  ON TRIM(A.CODDOC) = eval.DOCUMENTO
WHERE A.FLAG_CD40 = 'SI';

COLLECT STATISTICS ON DLAB_GEC.M_EXP_CD40K COLUMN (CODDOC, CODPROMOT);
