-- ==============================================================================
-- PROCESO: KRI_VENTAS_SIN_AUDIO (Ventas Sin Audio KRI)
-- OPTIMIZACIÓN: 
--   1. Consolidación de ventas del mes mediante UNION ALL (Data Flow VENTAS*).
--   2. Limpieza e inyección en TEMP_TRAFICO con cruces de telefonía inline.
--   3. Unificación de actualizaciones de origen de llamada y marcas de audio.
--   4. Uso de la cláusula nativa QUALIFY y COLLECT STATISTICS.
-- ==============================================================================

-- [PASO 1]: Limpieza de tabla consolidada general
DELETE FROM DLAB_GEC.M_EXP_CO_KRI_VENTA_TOTAL ALL;

-- [PASO 2]: Consolidar ventas en la tabla KRI (Lógica del Data Flow VENTAS*)
INSERT INTO DLAB_GEC.M_EXP_CO_KRI_VENTA_TOTAL (
    MESDESEMBOLSO, TIP_CLIENTE, FECDESEMB, DIA, CODDOC, REG_EJECUTIVO
)
SELECT MESDESEMBOLSO, TIP_CLIENTE, CAST(CAST(FECDESEMB AS FORMAT 'YYYYMMDD') AS VARCHAR(8)), DIA, CODDOC, CODPROMOT AS REG_EJECUTIVO
FROM DLAB_GEC.M_EXP_VENTAS_TC
UNION ALL
SELECT MESDESEMBOLSO, TIP_CLIENTE, CAST(CAST(FECDESEMB AS FORMAT 'YYYYMMDD') AS VARCHAR(8)), DIA, CODDOC, CODPROMOT AS REG_EJECUTIVO
FROM DLAB_GEC.M_EXP_VENTAS_PP
WHERE MESDESEMBOLSO IS NOT NULL
UNION ALL
SELECT MESDESEMBOLSO, TIP_CLIENTE, CAST(CAST(FECDESEMB AS FORMAT 'YYYYMMDD') AS VARCHAR(8)), DIA, CODDOC, CODPROMOT AS REG_EJECUTIVO
FROM DLAB_GEC.M_EXP_VENTAS_EC
UNION ALL
SELECT MESDESEMBOLSO, TIP_CLIENTE, CAST(CAST(FECDESEMBOLSO AS FORMAT 'YYYYMMDD') AS VARCHAR(8)), DIA, CODDOC, CODPROMOT AS REG_EJECUTIVO
FROM DLAB_GEC.M_EXP_VENTAS_CD
WHERE COD_CARGA = :periodo
UNION ALL
SELECT MESDESEMBOLSO, TIP_CLIENTE, CAST(CAST(FECDESEMB AS FORMAT 'YYYYMMDD') AS VARCHAR(8)), DIA, CODDOC, CODPROMOT AS REG_EJECUTIVO
FROM DLAB_GEC.M_EXP_VENTAS_CON
UNION ALL
SELECT MESDESEMBOLSO, TIP_CLIENTE, CAST(CAST(FECDESEMBOLSO AS FORMAT 'YYYYMMDD') AS VARCHAR(8)), DIA, CODDOC, CODPROMOT AS REG_EJECUTIVO
FROM DLAB_GEC.M_EXP_VENTAS_UPG
UNION ALL
SELECT MESDESEMBOLSO, TIP_CLIENTE, CAST(CAST(FECDESEMBOLSO AS FORMAT 'YYYYMMDD') AS VARCHAR(8)), DIA, CODDOC, CODPROMOT AS REG_EJECUTIVO
FROM DLAB_GEC.M_EXP_VENTAS_IL;

COLLECT STATISTICS ON DLAB_GEC.M_EXP_CO_KRI_VENTA_TOTAL COLUMN (CODDOC, REG_EJECUTIVO);


-- [PASO 3]: Inicializar TIP_CLIENTE en M_EXP_TRAFICO_GENESYS (Requerido para cruces de DNI)
UPDATE DLAB_GEC.M_EXP_TRAFICO_GENESYS 
FROM DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS B
SET TIP_CLIENTE = B.SUB_EQUIPO
WHERE USERNAME = B.REG_EJECUTIVO;


-- [PASO 3.1]: Actualizar DNI en M_EXP_TRAFICO_GENESYS (Por ANI - Carga Actual y Digital)
UPDATE DLAB_GEC.M_EXP_TRAFICO_GENESYS
FROM (
    SELECT TELEFONO, NUMERO_DOCUMENTO, TIP_CLIENTE
    FROM (
        SELECT TELEFONO, NUMERO_DOCUMENTO, TIP_CLIENTE
        FROM DLAB_GEC.TLV_CARGA_ACTUAL WHERE TELEFONO IS NOT NULL
        UNION ALL
        SELECT TELEFONO, NUMERO_DOCUMENTO, TIP_CLIENTE
        FROM DLAB_GEC.TLV_CARGA_ACTUAL_DIGITAL WHERE TELEFONO IS NOT NULL
    ) U
    QUALIFY ROW_NUMBER() OVER(PARTITION BY TELEFONO, TIP_CLIENTE ORDER BY NUMERO_DOCUMENTO ASC) = 1
) B
SET DNI = B.NUMERO_DOCUMENTO
WHERE DNI IS NULL
  AND ANI = B.TELEFONO
  AND (
      (B.TIP_CLIENTE IN ('C','NC','2DA','DTC') AND DLAB_GEC.M_EXP_TRAFICO_GENESYS.TIP_CLIENTE IN ('DTC','TC')) OR
      (B.TIP_CLIENTE IN ('DPP','PP') AND DLAB_GEC.M_EXP_TRAFICO_GENESYS.TIP_CLIENTE IN ('DPP','PP')) OR
      (B.TIP_CLIENTE IN ('DEC','EC') AND DLAB_GEC.M_EXP_TRAFICO_GENESYS.TIP_CLIENTE IN ('DEC','EC')) OR
      (B.TIP_CLIENTE IN ('DCD','CD') AND DLAB_GEC.M_EXP_TRAFICO_GENESYS.TIP_CLIENTE IN ('DCD','CD')) OR
      (B.TIP_CLIENTE IN ('DCO','CON') AND DLAB_GEC.M_EXP_TRAFICO_GENESYS.TIP_CLIENTE IN ('DCO','CON')) OR
      (B.TIP_CLIENTE IN ('PRT','UPG','IL','TCA','PA','DTCA','DUPG','DIL','DPA','REPRO') AND DLAB_GEC.M_EXP_TRAFICO_GENESYS.TIP_CLIENTE = 'PRT')
  );


-- [PASO 3.2]: Actualizar DNI en M_EXP_TRAFICO_GENESYS (Por DNIS - Carga Actual y Digital)
UPDATE DLAB_GEC.M_EXP_TRAFICO_GENESYS
FROM (
    SELECT TELEFONO, NUMERO_DOCUMENTO, TIP_CLIENTE
    FROM (
        SELECT TELEFONO, NUMERO_DOCUMENTO, TIP_CLIENTE
        FROM DLAB_GEC.TLV_CARGA_ACTUAL WHERE TELEFONO IS NOT NULL
        UNION ALL
        SELECT TELEFONO, NUMERO_DOCUMENTO, TIP_CLIENTE
        FROM DLAB_GEC.TLV_CARGA_ACTUAL_DIGITAL WHERE TELEFONO IS NOT NULL
    ) U
    QUALIFY ROW_NUMBER() OVER(PARTITION BY TELEFONO, TIP_CLIENTE ORDER BY NUMERO_DOCUMENTO ASC) = 1
) B
SET DNI = B.NUMERO_DOCUMENTO
WHERE DNI IS NULL
  AND DNIS = B.TELEFONO
  AND (
      (B.TIP_CLIENTE IN ('C','NC','2DA','DTC') AND DLAB_GEC.M_EXP_TRAFICO_GENESYS.TIP_CLIENTE IN ('DTC','TC')) OR
      (B.TIP_CLIENTE IN ('DPP','PP') AND DLAB_GEC.M_EXP_TRAFICO_GENESYS.TIP_CLIENTE IN ('DPP','PP')) OR
      (B.TIP_CLIENTE IN ('DEC','EC') AND DLAB_GEC.M_EXP_TRAFICO_GENESYS.TIP_CLIENTE IN ('DEC','EC')) OR
      (B.TIP_CLIENTE IN ('DCD','CD') AND DLAB_GEC.M_EXP_TRAFICO_GENESYS.TIP_CLIENTE IN ('DCD','CD')) OR
      (B.TIP_CLIENTE IN ('DCO','CON') AND DLAB_GEC.M_EXP_TRAFICO_GENESYS.TIP_CLIENTE IN ('DCO','CON')) OR
      (B.TIP_CLIENTE IN ('PRT','UPG','IL','TCA','PA','DTCA','DUPG','DIL','DPA','REPRO') AND DLAB_GEC.M_EXP_TRAFICO_GENESYS.TIP_CLIENTE = 'PRT')
  );


-- [PASO 4.1]: Cruzar DNI en M_EXP_TRAFICO_GENESYS con Gob Datos (Por ANI - Filtrado selectivo)
UPDATE DLAB_GEC.M_EXP_TRAFICO_GENESYS
FROM (
    SELECT NUMTELEFONO, CODDOC
    FROM E_DW_VIEWS.V_CONT_TELEFONO_APICLIENTE
    WHERE FLG_VALIDADO = 1
      AND NUMTELEFONO IN (
          SELECT ANI FROM DLAB_GEC.M_EXP_TRAFICO_GENESYS 
          WHERE DNI IS NULL AND ANI IS NOT NULL
      )
    QUALIFY ROW_NUMBER() OVER(PARTITION BY NUMTELEFONO ORDER BY CODDOC ASC) = 1
) B
SET DNI = B.CODDOC
WHERE DNI IS NULL
  AND ANI = B.NUMTELEFONO;


-- [PASO 4.2]: Cruzar DNI en M_EXP_TRAFICO_GENESYS con Gob Datos (Por DNIS - Filtrado selectivo)
UPDATE DLAB_GEC.M_EXP_TRAFICO_GENESYS
FROM (
    SELECT NUMTELEFONO, CODDOC
    FROM E_DW_VIEWS.V_CONT_TELEFONO_APICLIENTE
    WHERE FLG_VALIDADO = 1
      AND NUMTELEFONO IN (
          SELECT DNIS FROM DLAB_GEC.M_EXP_TRAFICO_GENESYS 
          WHERE DNI IS NULL AND DNIS IS NOT NULL
      )
    QUALIFY ROW_NUMBER() OVER(PARTITION BY NUMTELEFONO ORDER BY CODDOC ASC) = 1
) B
SET DNI = B.CODDOC
WHERE DNI IS NULL
  AND DNIS = B.NUMTELEFONO;


-- [PASO 5]: Recrear TEMP_TRAFICO e inyectar datos del mes con cruces inline
DROP TABLE DLAB_GEC.TEMP_TRAFICO;

CREATE MULTISET TABLE DLAB_GEC.TEMP_TRAFICO, FALLBACK,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO,
MAP = TD_MAP1	 
AS (
    SELECT DISTINCT
        COALESCE(
            CASE 
                WHEN LENGTH(A.NUM_DOCUMENTO) > 11 THEN NULL
                WHEN A.NUM_DOCUMENTO = '00000000' THEN NULL
                WHEN LENGTH(A.NUM_DOCUMENTO) = 9 AND LEFT(A.NUM_DOCUMENTO, 1) = '0' THEN SUBSTRING(A.NUM_DOCUMENTO FROM 2 FOR 8)
                ELSE A.NUM_DOCUMENTO
            END,
            ca.NUMERO_DOCUMENTO,
            gd.CODDOC
        ) AS NUM_DOCUMENTO,
        A.TELEFONO_CONTACTO AS TELEFONO,
        CASE WHEN LEFT(A.NOMBRE_AGENTE, 6) = '' THEN NULL ELSE LEFT(A.NOMBRE_AGENTE, 6) END AS REG_EJECUTIVO,
        A.FEC_LLAMADA, 
        A.DURACION_LLAMADA,
        COALESCE(
            CASE WHEN A.TIP_CLIENTE = '' THEN NULL ELSE A.TIP_CLIENTE END,
            exec.SUB_EQUIPO
        ) AS TIP_CLIENTE, 
        A.RESULTADO_LLAMADA
    FROM DLAB_GEC.TEMP_BATCH A
    -- default tip cliente
    LEFT JOIN DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS exec
      ON LEFT(A.NOMBRE_AGENTE, 6) = exec.REG_EJECUTIVO
    -- cruce con base digital/física
    LEFT JOIN (
        SELECT TELEFONO, NUMERO_DOCUMENTO, TIP_CLIENTE
        FROM (
            SELECT TELEFONO, NUMERO_DOCUMENTO, TIP_CLIENTE FROM DLAB_GEC.TLV_CARGA_ACTUAL WHERE LENGTH(TELEFONO) >= 9
            UNION ALL
            SELECT TELEFONO, NUMERO_DOCUMENTO, TIP_CLIENTE FROM DLAB_GEC.TLV_CARGA_ACTUAL_DIGITAL WHERE LENGTH(TELEFONO) >= 9
        ) U
        QUALIFY ROW_NUMBER() OVER(PARTITION BY TELEFONO, TIP_CLIENTE ORDER BY NUMERO_DOCUMENTO ASC) = 1
    ) ca
      ON A.TELEFONO_CONTACTO = ca.TELEFONO
     AND (
         (ca.TIP_CLIENTE IN ('C','NC','2DA','DTC') AND A.TIP_CLIENTE IN ('TC','DTC','C','NC','2DA')) OR
         (ca.TIP_CLIENTE IN ('DPP','PP') AND A.TIP_CLIENTE IN ('PP','DPP')) OR
         (ca.TIP_CLIENTE IN ('DEC','EC') AND A.TIP_CLIENTE IN ('EC','DEC')) OR
         (ca.TIP_CLIENTE IN ('DCD','CD') AND A.TIP_CLIENTE IN ('CD','DCD')) OR
         (ca.TIP_CLIENTE IN ('CON','DCO') AND A.TIP_CLIENTE IN ('CON','DCO')) OR
         (ca.TIP_CLIENTE IN ('IL','DIL','UPG','DUPG','TCAD','DTCA','PA','DPA') AND A.TIP_CLIENTE IN ('IL','DIL','UPG','DUPG','TCAD','DTCA','PA','DPA'))
     )
    -- cruce con Gob Datos
    LEFT JOIN (
        SELECT CODDOC, NUMTELEFONO
        FROM E_DW_VIEWS.V_CONT_TELEFONO_APICLIENTE
        WHERE FLG_VALIDADO = 1
          AND NUMTELEFONO IN (
              SELECT TELEFONO_CONTACTO 
              FROM DLAB_GEC.TEMP_BATCH 
              WHERE TELEFONO_CONTACTO IS NOT NULL
          )
        QUALIFY ROW_NUMBER() OVER(PARTITION BY NUMTELEFONO ORDER BY CODDOC ASC) = 1
    ) gd
      ON A.TELEFONO_CONTACTO = gd.NUMTELEFONO
    WHERE YEAR(A.FEC_LLAMADA) = :anio
      AND MONTH(A.FEC_LLAMADA) = :mes
      AND A.TIP_CLIENTE NOT IN ('RET', 'RET_CTS', 'RET_SEG', 'RET_TC', 'RET_TCI', 'SLC', 'VEH', 'HIP', 'HIP_C', 'HIP_CO', 'BPE', 'BPE_CN', 'BPE_DI', 'BPE_GL', 'BPE_RE', 'BPE_EF', 'BPE_AD', 'BPE_COB', 'BPE_DAD', 'GCC', 'JESUS VELASQUE TEODORO', 'NUNEZ ROLDAN IVAN', 'RET_SEG_BPI', 'SOLICITAR CONSENTIMIENTO INICIAL', 'TIENE CONSENTIMIENTO INICIAL')
) WITH DATA
PRIMARY INDEX(NUM_DOCUMENTO, TELEFONO, FEC_LLAMADA);

COLLECT STATISTICS ON DLAB_GEC.TEMP_TRAFICO COLUMN (NUM_DOCUMENTO, TELEFONO);

-- [PASO 6]: Eliminar llamadas vacías en la temporal
DELETE FROM DLAB_GEC.TEMP_TRAFICO WHERE TELEFONO IS NULL AND NUM_DOCUMENTO IS NULL;


-- [PASO 7]: Actualizar banderas de origen en M_EXP_CO_KRI_VENTA_TOTAL (Cruces Genesys y Derivaciones)
UPDATE DLAB_GEC.M_EXP_CO_KRI_VENTA_TOTAL
FROM (
    SELECT NUM_DOCUMENTO, TARGET_TIP
    FROM (
        SELECT NUM_DOCUMENTO, 
               CASE 
                   WHEN TIP_CLIENTE IN ('TC','DTC','C','NC','2DA') THEN 'DTC'
                   WHEN TIP_CLIENTE IN ('PP','DPP') THEN 'DPP'
                   WHEN TIP_CLIENTE IN ('EC','DEC') THEN 'DEC'
                   WHEN TIP_CLIENTE IN ('DCD','CD') THEN 'DCD'
                   WHEN TIP_CLIENTE IN ('DCO','CON') THEN 'DCO'
                   ELSE 'PRT'
               END AS TARGET_TIP
        FROM DLAB_GEC.TEMP_TRAFICO
    ) U
    QUALIFY ROW_NUMBER() OVER (PARTITION BY NUM_DOCUMENTO, TARGET_TIP ORDER BY NUM_DOCUMENTO) = 1
) B
SET ORIGEN_LLAMADA = 'TRAFICO_CLOUD2'
WHERE CODDOC = B.NUM_DOCUMENTO
  AND ORIGEN_LLAMADA IS NULL
  AND (
      (DLAB_GEC.M_EXP_CO_KRI_VENTA_TOTAL.TIP_CLIENTE = 'DTC' AND B.TARGET_TIP = 'DTC') OR
      (DLAB_GEC.M_EXP_CO_KRI_VENTA_TOTAL.TIP_CLIENTE = 'DPP' AND B.TARGET_TIP = 'DPP') OR
      (DLAB_GEC.M_EXP_CO_KRI_VENTA_TOTAL.TIP_CLIENTE = 'DEC' AND B.TARGET_TIP = 'DEC') OR
      (DLAB_GEC.M_EXP_CO_KRI_VENTA_TOTAL.TIP_CLIENTE = 'DCD' AND B.TARGET_TIP = 'DCD') OR
      (DLAB_GEC.M_EXP_CO_KRI_VENTA_TOTAL.TIP_CLIENTE = 'DCO' AND B.TARGET_TIP = 'DCO') OR
      (DLAB_GEC.M_EXP_CO_KRI_VENTA_TOTAL.TIP_CLIENTE IN ('DUPG','DTCA','DPA','DIL','SEG') AND B.TARGET_TIP = 'PRT')
  );


-- [PASO 8]: Poblar las tablas finales de KRI Sin Audio
DELETE FROM DLAB_GEC.T_EXP_KRI_VENTAS_SINAUDIO ALL;

INSERT INTO DLAB_GEC.T_EXP_KRI_VENTAS_SINAUDIO (
    MESDESEMBOLSO, TIP_CLIENTE, FECDESEMB, DIA, CODDOC, REG_EJECUTIVO, 
    NOM_EJECUTIVO, REG_SUPERVISOR, NOM_SUPERVISOR, ORIGEN_LLAMADA, 
    TIEMPO2, RANGO_TIEMPO, DATAS, MONTO_APROB, FLAG_SEG, FLAG_CD40K, 
    REQUIERE_VAL, VALIDACION_CORRECTA, VALIDACION_SIN_VAL, VALIDACION_FALLIDA, 
    FLAG_EVALUADO, DATE_BK
)
SELECT 
    A.MESDESEMBOLSO, A.TIP_CLIENTE, A.FECDESEMB, A.DIA, A.CODDOC, A.REG_EJECUTIVO, 
    B.NOM_EJECUTIVO, B.REG_SUPERVISOR, B.NOM_SUPERVISOR, A.ORIGEN_LLAMADA, 
    A.TIEMPO2, A.RANGO_TIEMPO, 1 AS DATAS, A.MONTO_APROB, A.FLAG_SEG, A.FLAG_CD40K, 
    A.REQUIERE_VAL, A.VALIDACION_CORRECTA, A.VALIDACION_SIN_VAL, A.VALIDACION_FALLIDA, 
    A.FLAG_EVALUADO, CURRENT_TIMESTAMP(0) AS DATE_BK
FROM DLAB_GEC.M_EXP_CO_KRI_VENTA_TOTAL A
LEFT JOIN DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS B
  ON A.REG_EJECUTIVO = B.REG_EJECUTIVO
WHERE A.ORIGEN_LLAMADA IS NULL;

COLLECT STATISTICS ON DLAB_GEC.T_EXP_KRI_VENTAS_SINAUDIO COLUMN (CODDOC);


DELETE FROM DLAB_GEC.T_EXP_KRI_VENTAS_SINAUDIO_CALIDAD ALL;

INSERT INTO DLAB_GEC.T_EXP_KRI_VENTAS_SINAUDIO_CALIDAD (
    MESDESEMBOLSO, TIP_CLIENTE, FECDESEMB, DIA, CODDOC, REG_EJECUTIVO, 
    NOM_EJECUTIVO, NOM_SUPERVISOR, MONTO_APROB, FLAG_SEG, FLAG_CD40K, 
    REQUIERE_VAL, VALIDACION_CORRECTA, VALIDACION_SIN_VAL, VALIDACION_FALLIDA, 
    TRANSFER_IVR, RANGO_TIEMPO, FLAG_EVALUADO, FLAG_REGISTRO, PRT_SEG
)
SELECT 
    A.MESDESEMBOLSO, A.TIP_CLIENTE, A.FECDESEMB, A.DIA, A.CODDOC, A.REG_EJECUTIVO, 
    B.NOM_EJECUTIVO, B.NOM_SUPERVISOR, A.MONTO_APROB, A.FLAG_SEG, A.FLAG_CD40K, 
    A.REQUIERE_VAL, A.VALIDACION_CORRECTA, A.VALIDACION_SIN_VAL, A.VALIDACION_FALLIDA, 
    A.TRANSFER_IVR, A.RANGO_TIEMPO, A.FLAG_EVALUADO, NULL AS FLAG_REGISTRO, NULL AS PRT_SEG
FROM DLAB_GEC.M_EXP_CO_KRI_VENTA_TOTAL A
LEFT JOIN DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS B
  ON A.REG_EJECUTIVO = B.REG_EJECUTIVO
WHERE A.ORIGEN_LLAMADA IS NULL;

COLLECT STATISTICS ON DLAB_GEC.T_EXP_KRI_VENTAS_SINAUDIO_CALIDAD COLUMN (CODDOC);
