-- ==============================================================================
-- PROCESO: SOURCE_TVL (Bandeja de Orígenes y Canales)
-- OPTIMIZACIÓN: 
--   1. Se eliminan las tablas temporales y se inserta directo a T_RETENCION_BASE_CALIDAD_GIRU.
--   2. Se incluye la lógica del Data Flow UP TD(*) para T_VENTAS_BPE_MARKET.
--   3. Se incluye la lógica del Data Flow UP TDT* para M_EXP_CONSUMO_SELECT_PP_EC.
--   4. Recolección de estadísticas al terminar.
-- ==============================================================================

-- [PASO 1]: Limpiar e insertar en T_RETENCION_BASE_CALIDAD_GIRU
DELETE FROM DLAB_GEC.T_RETENCION_BASE_CALIDAD_GIRU ALL;

INSERT INTO DLAB_GEC.T_RETENCION_BASE_CALIDAD_GIRU (
    RECLAMO, DESC_TIPO, NUM_TARJETA, NUM_DOCUMENTO, USUARIO_ALTA, NOMBRE_USUARIO_ALTA, 
    DESCRIPCION_S_ALTA, ESTADO, FECHA_ALTA, FECHA_RESPUESTA, DESCRIPCION_A_ACTUAL, 
    REG_ASESOR_RET, NOM_ASESOR_RET, NOM_SUPERVISOR, ORIGEN, EVALUADO, FECHA_UPDATE
)
SELECT 
    A.ID_RECLAMO AS RECLAMO,
    C.DESC_TIPO,
    G.cardNumber AS NUM_TARJETA,
    A.NRO_DOCUMENTO AS NUM_DOCUMENTO,
    A.USUARIO_ALTA,
    A.NOMBRE_USUARIO_ALTA,
    E.DESCRIPCION AS DESCRIPCION_S_ALTA,
    CASE 
        WHEN A.estado_reclamo = 'EP' THEN 'EN PROCESO'
        WHEN A.estado_reclamo = 'NF' THEN 'NO PROCEDE'
        WHEN A.estado_reclamo = 'PF' THEN 'PROCEDE'
        WHEN A.estado_reclamo = 'DP' THEN 'DOCUMENTACIÓN PENDIENTE'
        ELSE 'OTRO ESTADO'
    END AS ESTADO,
    A.FECHA_ALTA,
    A.FECHA_RESPUESTA,
    D.DESCRIPCION AS DESCRIPCION_A_ACTUAL,
    -- REG_ASESOR_RET
    CASE 
        WHEN exec_alta.REG_EJECUTIVO IS NOT NULL THEN A.USUARIO_ALTA 
        ELSE A.CODIGO_USUARIO_ACTUAL 
    END AS REG_ASESOR_RET,
    -- NOM_ASESOR_RET
    CASE 
        WHEN exec_alta.REG_EJECUTIVO IS NOT NULL THEN exec_alta.NOM_EJECUTIVO 
        ELSE exec_actual.NOM_EJECUTIVO 
    END AS NOM_ASESOR_RET,
    -- NOM_SUPERVISOR
    CASE 
        WHEN exec_alta.REG_EJECUTIVO IS NOT NULL THEN exec_alta.NOM_SUPERVISOR 
        ELSE exec_actual.NOM_SUPERVISOR 
    END AS NOM_SUPERVISOR,
    -- ORIGEN (IN / OUT)
    CASE 
        WHEN exec_alta.REG_EJECUTIVO IS NOT NULL THEN 'IN' 
        ELSE 'OUT' 
    END AS ORIGEN,
    -- EVALUADO
    CASE 
        WHEN eval.DOCUMENTO IS NOT NULL THEN 'SI' 
        ELSE 'NO' 
    END AS EVALUADO,
    CURRENT_TIMESTAMP(0) AS FECHA_UPDATE
FROM E_DW_VIEWS.V_CRM_EXO_GIR_RECLAMO A
INNER JOIN E_DW_VIEWS.V_CRM_EXO_GIR_DETALLE_RECLAMO B
    ON A.id_reclamo = B.id_reclamo
LEFT JOIN E_DW_VIEWS.V_CRM_EXO_GIR_TIPOLOGIA C
    ON B.id_tipologia = C.id_tipologia
LEFT JOIN E_DW_VIEWS.V_CRM_EXO_GIR_AREA D
    ON A.AREA_ACTUAL = D.CODIGO
LEFT JOIN E_DW_VIEWS.V_CRM_EXO_GIR_AREA E
    ON A.SUCURSAL_ALTA = E.CODIGO
LEFT JOIN (
    SELECT id_reclamo, valor AS cardNumber
    FROM E_DW_VIEWS.V_CRM_EXO_GIR_DATO_ADIC_RECLAMO
    WHERE nombre = 'cardNumber'
      AND id_reclamo IN (
          SELECT id_reclamo 
          FROM E_DW_VIEWS.V_CRM_EXO_GIR_RECLAMO 
          WHERE TO_CHAR(fecha_alta, 'YYYYMMDD') >= :fec_inicio_mes
      )
    QUALIFY ROW_NUMBER() OVER (PARTITION BY id_reclamo ORDER BY id_reclamo) = 1
) G
    ON G.id_reclamo = A.id_reclamo
-- Cruzar con ejecutivos para identificar canal y roles
LEFT JOIN DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS exec_alta
    ON A.USUARIO_ALTA = exec_alta.REG_EJECUTIVO
LEFT JOIN DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS exec_actual
    ON A.CODIGO_USUARIO_ACTUAL = exec_actual.REG_EJECUTIVO
-- Cruzar con evaluados
LEFT JOIN DLAB_GEC.M_EXP_DOCUMENTOS_EVALUADOS eval
    ON A.NRO_DOCUMENTO = eval.DOCUMENTO
-- Cruzar para filtrar derivaciones
LEFT JOIN (
    SELECT DISTINCT ID_RECLAMO 
    FROM E_DW_VIEWS.V_CRM_EXO_GIR_ESTADO_RECLAMO 
    WHERE CAST((CAST(FECHA_CREACION AS FORMAT 'YYYYMM')) AS VARCHAR(8)) = :periodo
      AND ACTIVIDAD = 'DERIVACIONPROCESOAUTOMATICO'
) deriv
  ON A.ID_RECLAMO = deriv.ID_RECLAMO
WHERE C.DESC_TIPO IN ('Finalización de tarjeta de crédito', 'Anulación de tarjeta de crédito')
  AND TO_CHAR(A.fecha_alta, 'YYYYMMDD') >= :fec_inicio_mes
  AND A.estado_reclamo = 'NF'
  AND deriv.ID_RECLAMO IS NULL;

COLLECT STATISTICS ON DLAB_GEC.T_RETENCION_BASE_CALIDAD_GIRU COLUMN (RECLAMO, NUM_DOCUMENTO);


-- [PASO 2]: Limpiar e insertar en T_CALIDAD_SEGUROS_PRT
DELETE FROM DLAB_GEC.T_CALIDAD_SEGUROS_PRT ALL;

INSERT INTO DLAB_GEC.T_CALIDAD_SEGUROS_PRT (
    MESVENTA, FECVENTA, DNI_TITULAR, CODPROMOT, PRODUCTO, PLAN, NOM_EJECUTIVO, 
    NOM_SUPERVISOR
)
SELECT 
    A.MESVENTA, 
    A.FECVENTA,
    A.DNI_TITULAR, 
    A.CODPROMOT, 
    A.PRODUCTO, 
    A.PLAN,
    B.NOM_EJECUTIVO,
    B.NOM_SUPERVISOR
FROM E_DW_VIEWS_DLAB.V_DLAB_CGR_SEGUROS_VENTAS A
LEFT JOIN DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS B
  ON A.CODPROMOT = B.REG_EJECUTIVO
WHERE A.MESVENTA = :periodo_num
  AND A.CODPROMOT IN (
      SELECT DISTINCT REG_EJECUTIVO 
      FROM DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS
      WHERE SUB_EQUIPO = 'SEG'
  );

COLLECT STATISTICS ON DLAB_GEC.T_CALIDAD_SEGUROS_PRT COLUMN (DNI_TITULAR);

-- [PASO 3]: Carga de Canal Select (Proviene del Data Flow UP TDT*)
DELETE FROM DLAB_GEC.M_EXP_CONSUMO_SELECT_PP_EC ALL;

INSERT INTO DLAB_GEC.M_EXP_CONSUMO_SELECT_PP_EC (
    CODMES, EQUIPO, CODPROMOT, NOMPROMOT, CLIENTEID, CODDOC, CLIENTE, 
    FECDESEMBOLSO, SUBPRODUCTO, TIPOBIEN, PRODUCTO, MONTO, TEM, TEA, CAMP_FLG
)
-- Extra Cash Select
SELECT DISTINCT 
    E.PERIODO_VAL AS CODMES, 
    E.EQUIPO_DSC AS EQUIPO, 
    E.PROMOTOR_CD AS CODPROMOT, 
    E.PROMOTOR_DSC AS NOMPROMOT, 
    E.CUC_NUM AS CLIENTEID, 
    TRIM(E.DOCUMENTO_NUM) AS CODDOC, 
    E.CLIENTE_DESC AS CLIENTE,
    E.DESEMBOLSO_FC AS FECDESEMBOLSO,
    CASE WHEN E.REENGANCHE_FLG='S' THEN 'REENGANCHE' ELSE 'REGULAR' END AS SUBPRODUCTO,
    NULL AS TIPOBIEN,
    'EC' AS PRODUCTO,
    CAST(E.DESEMBOLSO_AMT AS INT) AS MONTO,
    CAST(E.TASA_MENSUAL_VAL AS DECIMAL(6,2)) AS TEM,
    CAST(ROUND(POWER((E.TASA_MENSUAL_VAL/100)+1,12)-1,4)*100 AS DECIMAL(6,2)) AS TEA,
    CASE WHEN E.CAMP_FLG = 1 THEN 1 ELSE 0 END AS CAMP_FLG
FROM E_DW_VIEWS_DLAB.CGR_EXTRACASH E
INNER JOIN (
    SELECT DISTINCT REGEJECUTIVO FROM E_DW_VIEWS.V_EJECUTIVO_CONTACTO WHERE MODELO='CANAL SELECT'
    UNION
    SELECT DISTINCT regejecutivo FROM E_DW_VIEWS.V_CARTERA_CLIENTE_HIST WHERE MODELO='CANAL SELECT' AND CAST(codmeS AS CHAR(6))=:periodo_prev
    UNION
    SELECT DISTINCT regsupervisor FROM E_DW_VIEWS.V_CARTERA_CLIENTE_HIST WHERE MODELO='CANAL SELECT' AND CAST(codmeS AS CHAR(6))=:periodo
) C
  ON C.REGEJECUTIVO = E.PROMOTOR_CD
WHERE CAST(E.PERIODO_VAL AS CHAR(6)) = :periodo
  AND E.DESEMBOLSO_AMT IS NOT NULL  
  AND E.VALIDO_FLG='S'

UNION ALL

-- Préstamos Select
SELECT DISTINCT 
    CAST(E.PERIODO_VAL AS CHAR(6)) AS CODMES, 
    E.EQUIPO_DSC AS EQUIPO, 
    E.PROMOTOR_CD AS CODPROMOT, 
    E.PROMOTOR_NM AS NOMPROMOT, 
    E.CUC_NUM AS CLIENTEID, 
    TRIM(E.DOCUMENTO_TITULAR_NUM) AS CODDOC, 
    E.CLIENTE_NM AS CLIENTE,
    E.DESEMBOLSO_FC AS FECDESEMBOLSO,
    CASE 
        WHEN E.OPERACION_DSC='AF/CD' THEN 'COMPRA DEUDA' 
        WHEN E.REENGANCHE_FLG=1 THEN 'REENGANCHE'
        ELSE 'REGULAR' 
    END AS SUBPRODUCTO,
    NULL AS TIPOBIEN,
    'PPE' AS PRODUCTO,
    CAST(E.DESEMBOLSO_AMT AS INT) AS MONTO,
    CAST(0 AS DECIMAL(6,2)) AS TEM,
    CAST(E.TASA_PRESTAMO_EFECTIVO_VAL AS DECIMAL(6,2)) AS TEA,
    CASE WHEN E.CAMP_FLG = 1 THEN 1 ELSE 0 END AS CAMP_FLG
FROM E_DW_VIEWS_DLAB.CGR_PRESTAMOS E
INNER JOIN (
    SELECT DISTINCT REGEJECUTIVO FROM E_DW_VIEWS.V_EJECUTIVO_CONTACTO WHERE MODELO='CANAL SELECT'
    UNION
    SELECT DISTINCT regejecutivo FROM E_DW_VIEWS.V_CARTERA_CLIENTE_HIST WHERE MODELO='CANAL SELECT' AND CAST(codmeS AS CHAR(6))=:periodo
    UNION
    SELECT DISTINCT regsupervisor FROM E_DW_VIEWS.V_CARTERA_CLIENTE_HIST WHERE MODELO='CANAL SELECT' AND CAST(codmeS AS CHAR(6))=:periodo
) C
  ON C.REGEJECUTIVO = E.PROMOTOR_CD 
WHERE CAST(E.PERIODO_VAL AS CHAR(6)) = :periodo
  AND E.DESEMBOLSO_FC IS NOT NULL
  AND E.DESEMBOLSO_AMT IS NOT NULL  
  AND E.DOCUMENTO_TITULAR_NUM IS NOT NULL;

COLLECT STATISTICS ON DLAB_GEC.M_EXP_CONSUMO_SELECT_PP_EC COLUMN (CODDOC, CODPROMOT);

-- [PASO 4]: Reemplazar la vista V_GESTION_CHIP parametrizando el período actual
REPLACE VIEW DLAB_GEC.V_GESTION_CHIP AS
(
 SELECT 
 COD_MES,
 PRODUCTO,
 CANT_CE,
 CONSENTIMIENTO,
 TIPO_CARGA,
 VARIABLE_15 AS CAMPAÑA,
 DES_RESULTLLAMADA_ININ AS TIPIFICACION,
 NUM_DOCUMENTO,
 NUM_TELEFONO,
 FEC_LLAMADA,
 NRO_LLAMADA,
 SUBSTR(NOM_EJECUTIVO, 1, 6) AS REG_EJECUTIVO,
 TRIM(SUBSTR(NOM_EJECUTIVO, 8)) AS NOM_EJECUTIVO,
 XFLUJO_ADQ AS TIPO_BASE
 FROM DLAB_GEC.v1_barrido_HIP_hist
 WHERE COD_MES >= :periodo
   AND CANT_CE = 1
);
