-- ==============================================================================
-- PROCESO: TLF_NO_AUTORIZADO (Teléfonos No Autorizados - COMPLETADO Y OPTIMIZADO)
-- OPTIMIZACIÓN: 
--   1. Reemplazo de drops y creates por DELETE/INSERT para conservar índices y stats.
--   2. Parametrización dinámica de periodos (:periodo, :periodo_num).
--   3. Unificación y estructuración secuencial limpia.
-- ==============================================================================

-- ========================================== 
-- [PROCESANDO PRODUCTO: TC] 
-- ========================================== 
DELETE FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TC ALL;

INSERT INTO DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TC (NUM_DOCUMENTO, REG_EJECUTIVO, NUM_TELEFONO, TIEMPO, RANGO_TIEMPO, GD_VAL, CA_VAL, DE_VAL, TIPO_VAL, FB_VAL, GRUPO_ORIGEN, ORIGEN, MONTO_APROB, FECDESEMB, DIA)
SELECT 
NUM_DOCUMENTO, 
REG_EJECUTIVO, 
NUM_TELEFONO, 
TIEMPO_SEG AS TIEMPO,
CAST(NULL AS VARCHAR(20)) AS RANGO_TIEMPO,
CAST(NULL AS INT) AS GD_VAL,
CAST(NULL AS INT) AS CA_VAL,
CAST(NULL AS INT) AS DE_VAL,
CAST(NULL AS VARCHAR(50)) AS TIPO_VAL,
CAST(NULL AS INT) AS FB_VAL,
CAST(NULL AS VARCHAR(15)) AS GRUPO_ORIGEN,
CAST(NULL AS VARCHAR(15)) AS ORIGEN,
CAST(NULL AS INT) AS MONTO_APROB,
CAST(NULL AS VARCHAR(10)) AS FECDESEMB,
CAST(NULL AS INT) AS DIA

FROM (
			SELECT NUM_DOCUMENTO, REG_EJECUTIVO, NUM_TELEFONO, TIEMPO_SEG, ROW_NUMBER() OVER(PARTITION BY NUM_DOCUMENTO, REG_EJECUTIVO ORDER BY TIEMPO_SEG DESC) AS ROWX
			FROM (
			
			SELECT A.NUM_DOCUMENTO, A.REG_EJECUTIVO, A.TELEFONO AS NUM_TELEFONO, SUM(EXTRACT(HOUR FROM A.DURACION_LLAMADA) * 3600
																										 + EXTRACT(MINUTE FROM A.DURACION_LLAMADA) * 60
																										 + EXTRACT(SECOND FROM A.DURACION_LLAMADA)) AS TIEMPO_SEG
			FROM DLAB_GEC.TEMP_TRAFICO A, DLAB_GEC.M_EXP_VENTAS_TC B
			WHERE A.NUM_DOCUMENTO = B.CODDOC
			AND A.REG_EJECUTIVO = B.CODPROMOT
			GROUP BY A.NUM_DOCUMENTO, A.REG_EJECUTIVO, A.TELEFONO
			
			UNION ALL 
			
			--- TABLA GENESYS 
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, username AS REG_EJECUTIVO, ANI AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_TRAFICO_GENESYS A, DLAB_GEC.M_EXP_VENTAS_TC B
			WHERE NUM_TELEFONO IS NOT NULL 
			AND A.DNI = B.CODDOC
			AND A.USERNAME = B.CODPROMOT
			GROUP BY DNI, USERNAME, ANI
			
			UNION ALL
			
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, username AS REG_EJECUTIVO, DNIS AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_TRAFICO_GENESYS A, DLAB_GEC.M_EXP_VENTAS_TC B
			WHERE NUM_TELEFONO IS NOT NULL
			AND A.DNI = B.CODDOC
			AND A.USERNAME = B.CODPROMOT
			GROUP BY DNI, USERNAME, DNIS
			
			UNION ALL 
			
			--- TABLA DERIVABT 
			
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, REG_EJECUTIVO, TELF_ANI AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_DERIVA_BT_TIEMPOS A, DLAB_GEC.M_EXP_VENTAS_TC B
			WHERE A.DNI = B.CODDOC
			AND A.REG_EJECUTIVO = B.CODPROMOT
			AND NUM_TELEFONO IS NOT NULL
			AND NUM_TELEFONO NOT IN ('localhost')
			AND NUM_TELEFONO NOT LIKE ('%.%')
			GROUP BY DNI, REG_EJECUTIVO, TELF_ANI
			
			
			UNION ALL 
			
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, REG_EJECUTIVO, TELF_DNIS AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_DERIVA_BT_TIEMPOS A, DLAB_GEC.M_EXP_VENTAS_TC B
			WHERE A.DNI = B.CODDOC
			AND A.REG_EJECUTIVO = B.CODPROMOT
			AND NUM_TELEFONO IS NOT NULL
			AND NUM_DOCUMENTO IS NOT NULL
			AND NUM_TELEFONO NOT IN ('localhost')
			AND NUM_TELEFONO NOT LIKE ('%.%')
			AND NUM_TELEFONO NOT LIKE ('%11311%')
			AND REG_EJECUTIVO NOT LIKE ('%TLV_%')
			GROUP BY DNI, REG_EJECUTIVO, TELF_DNIS
			
			) X
  ) Z
  WHERE ROWX = 1
  AND NUM_DOCUMENTO IS NOT NULL;

-- AGREGAMOS RANGOS TIEMPO 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TC SET RANGO_TIEMPO ='[1MIN]' WHERE (TIEMPO  >=0 AND TIEMPO <=60);
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TC SET RANGO_TIEMPO ='[3MIN]' WHERE (TIEMPO  >=60.0 AND TIEMPO <=180); 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TC SET RANGO_TIEMPO ='[5MIN]' WHERE (TIEMPO  >=180.0 AND TIEMPO <=300);
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TC SET RANGO_TIEMPO ='[10MIN]' WHERE (TIEMPO  >=300.0 AND TIEMPO <=600); 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TC SET RANGO_TIEMPO ='[20MIN]' WHERE (TIEMPO  >=600.0 AND TIEMPO <=1200); 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TC SET RANGO_TIEMPO ='[+20]' WHERE (TIEMPO  >=1200 AND TIEMPO <=300000);




--- CRUCE CON GOBIERNO DE DATOS
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TC
FROM  (SELECT CODDOC, NUMTELEFONO 
		FROM E_DW_VIEWS.V_CONT_TELEFONO_APICLIENTE
		WHERE FLG_VALIDADO=1
		AND CODDOC IN (SELECT NUM_DOCUMENTO FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TC
						WHERE TIPO_VAL IS NULL)) B
SET GD_VAL  = 1, TIPO_VAL = 'GOB DATOS'
WHERE NUM_DOCUMENTO = B.CODDOC
AND NUM_TELEFONO = B.NUMTELEFONO;


--- CRUCE CON CARGA - MES ACTUAL
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TC
FROM (
    SELECT NUMERO_DOCUMENTO, TELEFONO
    FROM (
        SELECT NUMERO_DOCUMENTO, TELEFONO,
               ROW_NUMBER() OVER (PARTITION BY NUMERO_DOCUMENTO, TELEFONO ORDER BY 1) AS RN
        FROM DLAB_GEC.TLV_CARGA_ACTUAL
        WHERE TIP_CLIENTE IN ('NC','C','2DA')
    ) AS SUB
    WHERE RN = 1
) AS B
SET CA_VAL = 1,
    TIPO_VAL = 'CARGA ACTUAL'
WHERE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TC.NUM_DOCUMENTO = B.NUMERO_DOCUMENTO
  AND DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TC.NUM_TELEFONO = B.TELEFONO
  AND DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TC.TIPO_VAL IS NULL;


---- CRUCE CON DATA ENRICHMENT
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TC
FROM (SELECT * FROM DLAB_GEC.TLV_CARGA_ACTUAL
		WHERE TIP_CLIENTE IN ('NC','C','2DA')
		AND CHANGE_N >= 11) B
SET CA_VAL = 1, TIPO_VAL = 'ENRICHMENT'
WHERE NUM_DOCUMENTO = B.NUMERO_DOCUMENTO
AND NUM_TELEFONO = B.TELEFONO
AND TIPO_VAL IS NULL;


--- TABLA DE CAMPAÑAS 

UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TC
FROM (SELECT DISTINCT CODDOC, NRO_TELEFONO1 FROM E_DW_VIEWS.V_AGG_CAMP_TC_VIGENTE
	WHERE CODMES = 202606) B ---------------------------------------------CAMBIAR
SET FB_VAL = 1, TIPO_VAL = 'FB_LEADS'
WHERE NUM_DOCUMENTO = B.CODDOC
AND NUM_TELEFONO = B.NRO_TELEFONO1
AND TIPO_VAL IS NULL;


UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TC
FROM (SELECT DISTINCT CODDOC, NRO_TELEFONO2 FROM E_DW_VIEWS.V_AGG_CAMP_TC_VIGENTE
	WHERE CODMES = 202606) B ---------------------------------------------CAMBIAR
SET FB_VAL = 1, TIPO_VAL = 'FB_LEADS'
WHERE NUM_DOCUMENTO = B.CODDOC
AND NUM_TELEFONO = B.NRO_TELEFONO2
AND TIPO_VAL IS NULL;


--- MONTO APROBADO - FECDESEMBOLSO -  DIA 

UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TC 
FROM (SELECT DISTINCT CODDOC, MONTO_APROB, FECDESEMB, DIA FROM DLAB_GEC.M_EXP_VENTAS_TC) B
SET MONTO_APROB = B.MONTO_APROB, FECDESEMB = B.FECDESEMB, DIA = B.DIA 
WHERE NUM_DOCUMENTO = B.CODDOC;


------------------------------- END ---------------------------------

COLLECT STATISTICS ON DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TC COLUMN (NUM_DOCUMENTO);


-- ========================================== 
-- [PROCESANDO PRODUCTO: PP] 
-- ========================================== 
DELETE FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_PP ALL;

INSERT INTO DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_PP (NUM_DOCUMENTO, REG_EJECUTIVO, NUM_TELEFONO, TIEMPO, RANGO_TIEMPO, GD_VAL, CA_VAL, DE_VAL, TIPO_VAL, FB_VAL, GRUPO_ORIGEN, ORIGEN, MONTO_APROB, FECDESEMB, DIA)
SELECT 
NUM_DOCUMENTO, 
REG_EJECUTIVO, 
NUM_TELEFONO, 
TIEMPO_SEG AS TIEMPO,
CAST(NULL AS VARCHAR(20)) AS RANGO_TIEMPO,
CAST(NULL AS INT) AS GD_VAL,
CAST(NULL AS INT) AS CA_VAL,
CAST(NULL AS INT) AS DE_VAL,
CAST(NULL AS VARCHAR(50)) AS TIPO_VAL,
CAST(NULL AS INT) AS FB_VAL,
CAST(NULL AS VARCHAR(15)) AS GRUPO_ORIGEN,
CAST(NULL AS VARCHAR(15)) AS ORIGEN,
CAST(NULL AS INT) AS MONTO_APROB,
CAST(NULL AS VARCHAR(10)) AS FECDESEMB,
CAST(NULL AS INT) AS DIA

FROM (
			SELECT NUM_DOCUMENTO, REG_EJECUTIVO, NUM_TELEFONO, TIEMPO_SEG, ROW_NUMBER() OVER(PARTITION BY NUM_DOCUMENTO, REG_EJECUTIVO ORDER BY TIEMPO_SEG DESC) AS ROWX
			FROM (
			
			SELECT A.NUM_DOCUMENTO, A.REG_EJECUTIVO, A.TELEFONO AS NUM_TELEFONO, SUM(EXTRACT(HOUR FROM A.DURACION_LLAMADA) * 3600
																										 + EXTRACT(MINUTE FROM A.DURACION_LLAMADA) * 60
																										 + EXTRACT(SECOND FROM A.DURACION_LLAMADA)) AS TIEMPO_SEG
			FROM DLAB_GEC.TEMP_TRAFICO A, DLAB_GEC.M_EXP_VENTAS_PP B
			WHERE A.NUM_DOCUMENTO = B.CODDOC
			AND A.REG_EJECUTIVO = B.CODPROMOT
			GROUP BY A.NUM_DOCUMENTO, A.REG_EJECUTIVO, A.TELEFONO
			
			UNION ALL 
			
			--- TABLA GENESYS 
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, username AS REG_EJECUTIVO, ANI AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_TRAFICO_GENESYS A, DLAB_GEC.M_EXP_VENTAS_PP B
			WHERE NUM_TELEFONO IS NOT NULL 
			AND A.DNI = B.CODDOC
			AND A.USERNAME = B.CODPROMOT
			GROUP BY DNI, USERNAME, ANI
			
			UNION ALL
			
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, username AS REG_EJECUTIVO, DNIS AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_TRAFICO_GENESYS A, DLAB_GEC.M_EXP_VENTAS_PP B
			WHERE NUM_TELEFONO IS NOT NULL
			AND A.DNI = B.CODDOC
			AND A.USERNAME = B.CODPROMOT
			GROUP BY DNI, USERNAME, DNIS
			
			UNION ALL 
			
			--- TABLA DERIVABT 
			
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, REG_EJECUTIVO, TELF_ANI AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_DERIVA_BT_TIEMPOS A, DLAB_GEC.M_EXP_VENTAS_PP B
			WHERE A.DNI = B.CODDOC
			AND A.REG_EJECUTIVO = B.CODPROMOT
			AND NUM_TELEFONO IS NOT NULL
			AND NUM_TELEFONO NOT IN ('localhost')
			AND NUM_TELEFONO NOT LIKE ('%.%')
			GROUP BY DNI, REG_EJECUTIVO, TELF_ANI
			
			
			UNION ALL 
			
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, REG_EJECUTIVO, TELF_DNIS AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_DERIVA_BT_TIEMPOS A, DLAB_GEC.M_EXP_VENTAS_PP B
			WHERE A.DNI = B.CODDOC
			AND A.REG_EJECUTIVO = B.CODPROMOT
			AND NUM_TELEFONO IS NOT NULL
			AND NUM_DOCUMENTO IS NOT NULL
			AND NUM_TELEFONO NOT IN ('localhost')
			AND NUM_TELEFONO NOT LIKE ('%.%')
			AND NUM_TELEFONO NOT LIKE ('%11311%')
			AND REG_EJECUTIVO NOT LIKE ('%TLV_%')
			GROUP BY DNI, REG_EJECUTIVO, TELF_DNIS
			
			) X
  ) Z
  WHERE ROWX = 1
  AND NUM_DOCUMENTO IS NOT NULL;

-- AGREGAMOS RANGOS TIEMPO 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_PP SET RANGO_TIEMPO ='[1MIN]' WHERE (TIEMPO  >=0 AND TIEMPO <=60);
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_PP SET RANGO_TIEMPO ='[3MIN]' WHERE (TIEMPO  >=60.0 AND TIEMPO <=180); 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_PP SET RANGO_TIEMPO ='[5MIN]' WHERE (TIEMPO  >=180.0 AND TIEMPO <=300);
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_PP SET RANGO_TIEMPO ='[10MIN]' WHERE (TIEMPO  >=300.0 AND TIEMPO <=600); 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_PP SET RANGO_TIEMPO ='[20MIN]' WHERE (TIEMPO  >=600.0 AND TIEMPO <=1200); 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_PP SET RANGO_TIEMPO ='[+20]' WHERE (TIEMPO  >=1200 AND TIEMPO <=300000);




--- CRUCE CON GOBIERNO DE DATOS
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_PP
FROM (
    SELECT CODDOC, NUMTELEFONO,
           ROW_NUMBER() OVER(PARTITION BY CODDOC, NUMTELEFONO ORDER BY CODDOC) AS RN
    FROM E_DW_VIEWS.V_CONT_TELEFONO_APICLIENTE
    WHERE FLG_VALIDADO = 1
    AND CODDOC IN (
        SELECT NUM_DOCUMENTO 
        FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_PP
        WHERE TIPO_VAL IS NULL
    )
) B
SET GD_VAL = 1, TIPO_VAL = 'GOB DATOS'
WHERE NUM_DOCUMENTO = B.CODDOC
AND NUM_TELEFONO = B.NUMTELEFONO
AND B.RN = 1;



--- CRUCE CON CARGA - MES ACTUAL
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_PP
FROM (
    SELECT NUMERO_DOCUMENTO, TELEFONO,
           ROW_NUMBER() OVER(PARTITION BY NUMERO_DOCUMENTO, TELEFONO ORDER BY NUMERO_DOCUMENTO) AS RN
    FROM DLAB_GEC.TLV_CARGA_ACTUAL
    WHERE TIP_CLIENTE IN ('PP')
) B
SET CA_VAL = 1, TIPO_VAL = 'CARGA ACTUAL'
WHERE NUM_DOCUMENTO = B.NUMERO_DOCUMENTO
AND NUM_TELEFONO = B.TELEFONO
AND TIPO_VAL IS NULL
AND B.RN = 1;



---- CRUCE CON DATA ENRICHMENT
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_PP
FROM (
    SELECT *
    FROM DLAB_GEC.TLV_CARGA_ACTUAL
    WHERE TIP_CLIENTE IN ('PP')
    AND REGEXP_SIMILAR(TRIM(CHANGE_N), '^[0-9]+$') = 1  -- Filtrar valores numéricos
    AND CAST(TRIM(CHANGE_N) AS INTEGER) >= 12  -- Convertir y comparar
) B
SET CA_VAL = 1, TIPO_VAL = 'ENRICHMENT'
WHERE NUM_DOCUMENTO = B.NUMERO_DOCUMENTO
AND NUM_TELEFONO = B.TELEFONO
AND TIPO_VAL IS NULL;

 

--- TABLA DE CAMPAÑAS 

UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_PP
FROM (
    SELECT CODDOC, NUMTEL1,
           ROW_NUMBER() OVER(PARTITION BY CODDOC, NUMTEL1 ORDER BY CODDOC) AS RN
    FROM E_DW_VIEWS.V_AGG_CAMP_PP_VIGENTE
    WHERE CODMES = :periodo_num  ---------------------------------------------CAMBIAR
) B
SET FB_VAL = 1, TIPO_VAL = 'FB_LEADS'
WHERE NUM_DOCUMENTO = B.CODDOC
AND NUM_TELEFONO = B.NUMTEL1
AND TIPO_VAL IS NULL
AND B.RN = 1;



UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_PP
FROM (
    SELECT CODDOC, NUMTEL2,
           ROW_NUMBER() OVER(PARTITION BY CODDOC, NUMTEL2 ORDER BY CODDOC) AS RN
    FROM E_DW_VIEWS.V_AGG_CAMP_PP_VIGENTE
    WHERE CODMES = :periodo_num ---------------------------------------------CAMBIAR
) B
SET FB_VAL = 1, TIPO_VAL = 'FB_LEADS'
WHERE NUM_DOCUMENTO = B.CODDOC
AND NUM_TELEFONO = B.NUMTEL2
AND TIPO_VAL IS NULL
AND B.RN = 1;




--- MONTO APROBADO - FECDESEMBOLSO -  DIA 

UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_PP
FROM (
    SELECT CODDOC, MONTO_APROB, FECDESEMB, DIA,
           ROW_NUMBER() OVER(PARTITION BY CODDOC ORDER BY MONTO_APROB DESC) AS RN
    FROM DLAB_GEC.M_EXP_VENTAS_PP
) B
SET MONTO_APROB = B.MONTO_APROB, FECDESEMB = B.FECDESEMB, DIA = B.DIA
WHERE NUM_DOCUMENTO = B.CODDOC
AND B.RN = 1;



------------------------------- END ---------------------------------

COLLECT STATISTICS ON DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_PP COLUMN (NUM_DOCUMENTO);


-- ========================================== 
-- [PROCESANDO PRODUCTO: CD] 
-- ========================================== 
DELETE FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CD ALL;

INSERT INTO DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CD (NUM_DOCUMENTO, REG_EJECUTIVO, NUM_TELEFONO, TIEMPO, RANGO_TIEMPO, GD_VAL, CA_VAL, DE_VAL, TIPO_VAL, FB_VAL, GRUPO_ORIGEN, ORIGEN, MONTO_APROB, FECDESEMB, DIA)
SELECT 
NUM_DOCUMENTO, 
REG_EJECUTIVO, 
NUM_TELEFONO, 
TIEMPO_SEG AS TIEMPO,
CAST(NULL AS VARCHAR(20)) AS RANGO_TIEMPO,
CAST(NULL AS INT) AS GD_VAL,
CAST(NULL AS INT) AS CA_VAL,
CAST(NULL AS INT) AS DE_VAL,
CAST(NULL AS VARCHAR(50)) AS TIPO_VAL,
CAST(NULL AS INT) AS FB_VAL,
CAST(NULL AS VARCHAR(15)) AS GRUPO_ORIGEN,
CAST(NULL AS VARCHAR(15)) AS ORIGEN,
CAST(NULL AS INT) AS MONTO_APROB,
CAST(NULL AS VARCHAR(10)) AS FECDESEMB,
CAST(NULL AS INT) AS DIA

FROM (
			SELECT NUM_DOCUMENTO, REG_EJECUTIVO, NUM_TELEFONO, TIEMPO_SEG, ROW_NUMBER() OVER(PARTITION BY NUM_DOCUMENTO, REG_EJECUTIVO ORDER BY TIEMPO_SEG DESC) AS ROWX
			FROM (
			
			SELECT A.NUM_DOCUMENTO, A.REG_EJECUTIVO, A.TELEFONO AS NUM_TELEFONO, SUM(EXTRACT(HOUR FROM A.DURACION_LLAMADA) * 3600
																										 + EXTRACT(MINUTE FROM A.DURACION_LLAMADA) * 60
																										 + EXTRACT(SECOND FROM A.DURACION_LLAMADA)) AS TIEMPO_SEG
			FROM DLAB_GEC.TEMP_TRAFICO A, DLAB_GEC.M_EXP_VENTAS_CD B
			WHERE A.NUM_DOCUMENTO = B.CODDOC
			AND A.REG_EJECUTIVO = B.CODPROMOT
			GROUP BY A.NUM_DOCUMENTO, A.REG_EJECUTIVO, A.TELEFONO
			
			UNION ALL 
			
			--- TABLA GENESYS 
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, username AS REG_EJECUTIVO, ANI AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_TRAFICO_GENESYS A, DLAB_GEC.M_EXP_VENTAS_CD B
			WHERE NUM_TELEFONO IS NOT NULL 
			AND A.DNI = B.CODDOC
			AND A.USERNAME = B.CODPROMOT
			GROUP BY DNI, USERNAME, ANI
			
			UNION ALL
			
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, username AS REG_EJECUTIVO, DNIS AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_TRAFICO_GENESYS A, DLAB_GEC.M_EXP_VENTAS_CD B
			WHERE NUM_TELEFONO IS NOT NULL
			AND A.DNI = B.CODDOC
			AND A.USERNAME = B.CODPROMOT
			GROUP BY DNI, USERNAME, DNIS
			
			UNION ALL 
			
			--- TABLA DERIVABT 
			
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, REG_EJECUTIVO, TELF_ANI AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_DERIVA_BT_TIEMPOS A, DLAB_GEC.M_EXP_VENTAS_CD B
			WHERE A.DNI = B.CODDOC
			AND A.REG_EJECUTIVO = B.CODPROMOT
			AND NUM_TELEFONO IS NOT NULL
			AND NUM_TELEFONO NOT IN ('localhost')
			AND NUM_TELEFONO NOT LIKE ('%.%')
			GROUP BY DNI, REG_EJECUTIVO, TELF_ANI
			
			
			UNION ALL 
			
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, REG_EJECUTIVO, TELF_DNIS AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_DERIVA_BT_TIEMPOS A, DLAB_GEC.M_EXP_VENTAS_CD B
			WHERE A.DNI = B.CODDOC
			AND A.REG_EJECUTIVO = B.CODPROMOT
			AND NUM_TELEFONO IS NOT NULL
			AND NUM_DOCUMENTO IS NOT NULL
			AND NUM_TELEFONO NOT IN ('localhost')
			AND NUM_TELEFONO NOT LIKE ('%.%')
			AND NUM_TELEFONO NOT LIKE ('%11311%')
			AND REG_EJECUTIVO NOT LIKE ('%TLV_%')
			GROUP BY DNI, REG_EJECUTIVO, TELF_DNIS
			
			) X
  ) Z
  WHERE ROWX = 1
  AND NUM_DOCUMENTO IS NOT NULL;

-- AGREGAMOS RANGOS TIEMPO 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CD SET RANGO_TIEMPO ='[1MIN]' WHERE (TIEMPO  >=0 AND TIEMPO <=60);
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CD SET RANGO_TIEMPO ='[3MIN]' WHERE (TIEMPO  >=60.0 AND TIEMPO <=180); 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CD SET RANGO_TIEMPO ='[5MIN]' WHERE (TIEMPO  >=180.0 AND TIEMPO <=300);
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CD SET RANGO_TIEMPO ='[10MIN]' WHERE (TIEMPO  >=300.0 AND TIEMPO <=600); 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CD SET RANGO_TIEMPO ='[20MIN]' WHERE (TIEMPO  >=600.0 AND TIEMPO <=1200); 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CD SET RANGO_TIEMPO ='[+20]' WHERE (TIEMPO  >=1200 AND TIEMPO <=300000);




--- CRUCE CON GOBIERNO DE DATOS
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CD
FROM  (SELECT DISTINCT CODDOC, NUMTELEFONO 
		FROM E_DW_VIEWS.V_CONT_TELEFONO_APICLIENTE
		WHERE FLG_VALIDADO=1
		AND CODDOC IN (SELECT NUM_DOCUMENTO FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CD
						WHERE TIPO_VAL IS NULL)) B
SET GD_VAL  = 1, TIPO_VAL = 'GOB DATOS'
WHERE NUM_DOCUMENTO = B.CODDOC
AND NUM_TELEFONO = B.NUMTELEFONO;


--- CRUCE CON CARGA - MES ACTUAL
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CD
FROM (SELECT * FROM DLAB_GEC.TLV_CARGA_ACTUAL
		WHERE TIP_CLIENTE IN ('EC')) B
SET CA_VAL = 1, TIPO_VAL = 'CARGA ACTUAL'
WHERE NUM_DOCUMENTO = B.NUMERO_DOCUMENTO
AND NUM_TELEFONO = B.TELEFONO
AND TIPO_VAL IS NULL;


---- CRUCE CON DATA ENRICHMENT

UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CD
FROM (
    SELECT 
        NUMERO_DOCUMENTO, 
        TELEFONO, 
        TIP_CLIENTE,
        CHANGE_N,
        ROW_NUMBER() OVER (PARTITION BY NUMERO_DOCUMENTO, TELEFONO ORDER BY NUMERO_DOCUMENTO) AS RN
    FROM DLAB_GEC.TLV_CARGA_ACTUAL
    WHERE TIP_CLIENTE IN ('CD')
      AND REGEXP_SIMILAR(TRIM(CHANGE_N), '^[0-9]+$') = 1  -- Filtrar valores numéricos
      AND CAST(TRIM(CHANGE_N) AS INTEGER) >= 12  -- Convertir y comparar
) B
SET CA_VAL = 1, TIPO_VAL = 'ENRICHMENT'
WHERE NUM_DOCUMENTO = B.NUMERO_DOCUMENTO
  AND NUM_TELEFONO = B.TELEFONO
  AND TIPO_VAL IS NULL
  AND B.RN = 1;



--- TABLA DE CAMPAÑAS 

UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CD
FROM (SELECT DISTINCT CODDOC, NRO_TELEFONO1 FROM E_DW_VIEWS.V_AGG_CAMP_EC_VIGENTE
	WHERE CODMES = :periodo_num) B --------------------CAMBIAR
SET FB_VAL = 1, TIPO_VAL = 'FB_LEADS'
WHERE NUM_DOCUMENTO = B.CODDOC
AND NUM_TELEFONO = B.NRO_TELEFONO1
AND TIPO_VAL IS NULL;


UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CD
FROM (SELECT DISTINCT CODDOC, NRO_TELEFONO2 FROM E_DW_VIEWS.V_AGG_CAMP_EC_VIGENTE
	WHERE CODMES = :periodo_num) B --------------------CAMBIAR
SET FB_VAL = 1, TIPO_VAL = 'FB_LEADS'
WHERE NUM_DOCUMENTO = B.CODDOC
AND NUM_TELEFONO = B.NRO_TELEFONO2
AND TIPO_VAL IS NULL;


SELECT * FROM DLAB_GEC.M_EXP_VENTAS_CD;
--- MONTO APROBADO - FECDESEMBOLSO -  DIA 

UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CD 
FROM (
    SELECT CODDOC, MONTO_APROB, FECDESEMBOLSO, DIA
    FROM (
        SELECT CODDOC, MONTO_APROB, FECDESEMBOLSO, DIA,
               ROW_NUMBER() OVER (PARTITION BY CODDOC ORDER BY FECDESEMBOLSO DESC) AS RN
        FROM DLAB_GEC.M_EXP_VENTAS_CD
    ) AS SubQuery
    WHERE RN = 1
) B
SET MONTO_APROB = B.MONTO_APROB, FECDESEMB = B.FECDESEMBOLSO, DIA = B.DIA
WHERE NUM_DOCUMENTO = B.CODDOC;



------------------------------- END ---------------------------------

COLLECT STATISTICS ON DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CD COLUMN (NUM_DOCUMENTO);


-- ========================================== 
-- [PROCESANDO PRODUCTO: EC] 
-- ========================================== 
DELETE FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_EC ALL;

INSERT INTO DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_EC (NUM_DOCUMENTO, REG_EJECUTIVO, NUM_TELEFONO, TIEMPO, RANGO_TIEMPO, GD_VAL, CA_VAL, DE_VAL, TIPO_VAL, FB_VAL, GRUPO_ORIGEN, ORIGEN, MONTO_APROB, FECDESEMB, DIA)
SELECT 
NUM_DOCUMENTO, 
REG_EJECUTIVO, 
NUM_TELEFONO, 
TIEMPO_SEG AS TIEMPO,
CAST(NULL AS VARCHAR(20)) AS RANGO_TIEMPO,
CAST(NULL AS INT) AS GD_VAL,
CAST(NULL AS INT) AS CA_VAL,
CAST(NULL AS INT) AS DE_VAL,
CAST(NULL AS VARCHAR(50)) AS TIPO_VAL,
CAST(NULL AS INT) AS FB_VAL,
CAST(NULL AS VARCHAR(15)) AS GRUPO_ORIGEN,
CAST(NULL AS VARCHAR(15)) AS ORIGEN,
CAST(NULL AS INT) AS MONTO_APROB,
CAST(NULL AS VARCHAR(10)) AS FECDESEMB,
CAST(NULL AS INT) AS DIA

FROM (
			SELECT NUM_DOCUMENTO, REG_EJECUTIVO, NUM_TELEFONO, TIEMPO_SEG, ROW_NUMBER() OVER(PARTITION BY NUM_DOCUMENTO, REG_EJECUTIVO ORDER BY TIEMPO_SEG DESC) AS ROWX
			FROM (
			
			SELECT A.NUM_DOCUMENTO, A.REG_EJECUTIVO, A.TELEFONO AS NUM_TELEFONO, SUM(EXTRACT(HOUR FROM A.DURACION_LLAMADA) * 3600
																										 + EXTRACT(MINUTE FROM A.DURACION_LLAMADA) * 60
																										 + EXTRACT(SECOND FROM A.DURACION_LLAMADA)) AS TIEMPO_SEG
			FROM DLAB_GEC.TEMP_TRAFICO A, DLAB_GEC.M_EXP_VENTAS_EC B
			WHERE A.NUM_DOCUMENTO = B.CODDOC
			AND A.REG_EJECUTIVO = B.CODPROMOT
			GROUP BY A.NUM_DOCUMENTO, A.REG_EJECUTIVO, A.TELEFONO
			
			UNION ALL 
			
			--- TABLA GENESYS 
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, username AS REG_EJECUTIVO, ANI AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_TRAFICO_GENESYS A, DLAB_GEC.M_EXP_VENTAS_EC B
			WHERE NUM_TELEFONO IS NOT NULL 
			AND A.DNI = B.CODDOC
			AND A.USERNAME = B.CODPROMOT
			GROUP BY DNI, USERNAME, ANI
			
			UNION ALL
			
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, username AS REG_EJECUTIVO, DNIS AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_TRAFICO_GENESYS A, DLAB_GEC.M_EXP_VENTAS_EC B
			WHERE NUM_TELEFONO IS NOT NULL
			AND A.DNI = B.CODDOC
			AND A.USERNAME = B.CODPROMOT
			GROUP BY DNI, USERNAME, DNIS
			
			UNION ALL 
			
			--- TABLA DERIVABT 
			
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, REG_EJECUTIVO, TELF_ANI AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_DERIVA_BT_TIEMPOS A, DLAB_GEC.M_EXP_VENTAS_EC B
			WHERE A.DNI = B.CODDOC
			AND A.REG_EJECUTIVO = B.CODPROMOT
			AND NUM_TELEFONO IS NOT NULL
			AND NUM_TELEFONO NOT IN ('localhost')
			AND NUM_TELEFONO NOT LIKE ('%.%')
			GROUP BY DNI, REG_EJECUTIVO, TELF_ANI
			
			
			UNION ALL 
			
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, REG_EJECUTIVO, TELF_DNIS AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_DERIVA_BT_TIEMPOS A, DLAB_GEC.M_EXP_VENTAS_EC B
			WHERE A.DNI = B.CODDOC
			AND A.REG_EJECUTIVO = B.CODPROMOT
			AND NUM_TELEFONO IS NOT NULL
			AND NUM_DOCUMENTO IS NOT NULL
			AND NUM_TELEFONO NOT IN ('localhost')
			AND NUM_TELEFONO NOT LIKE ('%.%')
			AND NUM_TELEFONO NOT LIKE ('%11311%')
			AND REG_EJECUTIVO NOT LIKE ('%TLV_%')
			GROUP BY DNI, REG_EJECUTIVO, TELF_DNIS
			
			) X
  ) Z
  WHERE ROWX = 1
  AND NUM_DOCUMENTO IS NOT NULL;

-- AGREGAMOS RANGOS TIEMPO 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_EC SET RANGO_TIEMPO ='[1MIN]' WHERE (TIEMPO  >=0 AND TIEMPO <=60);
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_EC SET RANGO_TIEMPO ='[3MIN]' WHERE (TIEMPO  >=60.0 AND TIEMPO <=180); 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_EC SET RANGO_TIEMPO ='[5MIN]' WHERE (TIEMPO  >=180.0 AND TIEMPO <=300);
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_EC SET RANGO_TIEMPO ='[10MIN]' WHERE (TIEMPO  >=300.0 AND TIEMPO <=600); 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_EC SET RANGO_TIEMPO ='[20MIN]' WHERE (TIEMPO  >=600.0 AND TIEMPO <=1200); 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_EC SET RANGO_TIEMPO ='[+20]' WHERE (TIEMPO  >=1200 AND TIEMPO <=300000);




--- CRUCE CON GOBIERNO DE DATOS
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_EC
FROM  (SELECT DISTINCT CODDOC, NUMTELEFONO 
		FROM E_DW_VIEWS.V_CONT_TELEFONO_APICLIENTE
		WHERE FLG_VALIDADO=1
		AND CODDOC IN (SELECT NUM_DOCUMENTO FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_EC
						WHERE TIPO_VAL IS NULL)) B
SET GD_VAL  = 1, TIPO_VAL = 'GOB DATOS'
WHERE NUM_DOCUMENTO = B.CODDOC
AND NUM_TELEFONO = B.NUMTELEFONO;


--- CRUCE CON CARGA - MES ACTUAL
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_EC
FROM (SELECT DISTINCT NUMERO_DOCUMENTO  FROM DLAB_GEC.TLV_CARGA_ACTUAL
		WHERE TIP_CLIENTE IN ('EC')) B
SET CA_VAL = 1, TIPO_VAL = 'CARGA ACTUAL'
WHERE NUM_DOCUMENTO = B.NUMERO_DOCUMENTO
--AND NUM_TELEFONO = B.TELEFONO
AND TIPO_VAL IS NULL;


---- CRUCE CON DATA ENRICHMENT
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_EC
FROM (SELECT * FROM DLAB_GEC.TLV_CARGA_ACTUAL
		WHERE TIP_CLIENTE IN ('EC')
		AND CHANGE_N >= 11) B
SET CA_VAL = 1, TIPO_VAL = 'ENRICHMENT'
WHERE NUM_DOCUMENTO = B.NUMERO_DOCUMENTO
AND NUM_TELEFONO = B.TELEFONO
AND TIPO_VAL IS NULL;


--- TABLA DE CAMPAÑAS 

UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_EC
FROM (SELECT DISTINCT CODDOC, NRO_TELEFONO1 FROM E_DW_VIEWS.V_AGG_CAMP_EC_VIGENTE
	WHERE CODMES = :periodo_num) B --------------------CAMBIAR
SET FB_VAL = 1, TIPO_VAL = 'FB_LEADS'
WHERE NUM_DOCUMENTO = B.CODDOC
AND NUM_TELEFONO = B.NRO_TELEFONO1
AND TIPO_VAL IS NULL;


UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_EC
FROM (SELECT DISTINCT CODDOC, NRO_TELEFONO2 FROM E_DW_VIEWS.V_AGG_CAMP_EC_VIGENTE
	WHERE CODMES = :periodo_num) B --------------------CAMBIAR
SET FB_VAL = 1, TIPO_VAL = 'FB_LEADS'
WHERE NUM_DOCUMENTO = B.CODDOC
AND NUM_TELEFONO = B.NRO_TELEFONO2
AND TIPO_VAL IS NULL;



--- MONTO APROBADO - FECDESEMBOLSO -  DIA 

UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_EC 
FROM (SELECT DISTINCT CODDOC, MONTO_APROB, FECDESEMB, DIA FROM DLAB_GEC.M_EXP_VENTAS_EC) B
SET MONTO_APROB = B.MONTO_APROB, FECDESEMB = B.FECDESEMB, DIA = B.DIA 
WHERE NUM_DOCUMENTO = B.CODDOC;


------------------------------- END ---------------------------------

COLLECT STATISTICS ON DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_EC COLUMN (NUM_DOCUMENTO);


-- ========================================== 
-- [PROCESANDO PRODUCTO: CON] 
-- ========================================== 
DELETE FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CON ALL;

INSERT INTO DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CON (NUM_DOCUMENTO, REG_EJECUTIVO, NUM_TELEFONO, TIEMPO, RANGO_TIEMPO, GD_VAL, CA_VAL, DE_VAL, TIPO_VAL, FB_VAL, GRUPO_ORIGEN, ORIGEN, MONTO_APROB, FECDESEMB, DIA)
SELECT 
NUM_DOCUMENTO, 
REG_EJECUTIVO, 
NUM_TELEFONO, 
TIEMPO_SEG AS TIEMPO,
CAST(NULL AS VARCHAR(20)) AS RANGO_TIEMPO,
CAST(NULL AS INT) AS GD_VAL,
CAST(NULL AS INT) AS CA_VAL,
CAST(NULL AS INT) AS DE_VAL,
CAST(NULL AS VARCHAR(50)) AS TIPO_VAL,
CAST(NULL AS INT) AS FB_VAL,
CAST(NULL AS VARCHAR(15)) AS GRUPO_ORIGEN,
CAST(NULL AS VARCHAR(15)) AS ORIGEN,
CAST(NULL AS INT) AS MONTO_APROB,
CAST(NULL AS VARCHAR(10)) AS FECDESEMB,
CAST(NULL AS INT) AS DIA

FROM (
			SELECT NUM_DOCUMENTO, REG_EJECUTIVO, NUM_TELEFONO, TIEMPO_SEG, ROW_NUMBER() OVER(PARTITION BY NUM_DOCUMENTO, REG_EJECUTIVO ORDER BY TIEMPO_SEG DESC) AS ROWX
			FROM (
			
			SELECT A.NUM_DOCUMENTO, A.REG_EJECUTIVO, A.TELEFONO AS NUM_TELEFONO, SUM(EXTRACT(HOUR FROM A.DURACION_LLAMADA) * 3600
																										 + EXTRACT(MINUTE FROM A.DURACION_LLAMADA) * 60
																										 + EXTRACT(SECOND FROM A.DURACION_LLAMADA)) AS TIEMPO_SEG
			FROM DLAB_GEC.TEMP_TRAFICO A, DLAB_GEC.M_EXP_VENTAS_CON B
			WHERE A.NUM_DOCUMENTO = B.CODDOC
			AND A.REG_EJECUTIVO = B.CODPROMOT
			GROUP BY A.NUM_DOCUMENTO, A.REG_EJECUTIVO, A.TELEFONO
			
			UNION ALL 
			
			--- TABLA GENESYS 
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, username AS REG_EJECUTIVO, ANI AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_TRAFICO_GENESYS A, DLAB_GEC.M_EXP_VENTAS_CON B
			WHERE NUM_TELEFONO IS NOT NULL 
			AND A.DNI = B.CODDOC
			AND A.USERNAME = B.CODPROMOT
			GROUP BY DNI, USERNAME, ANI
			
			UNION ALL
			
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, username AS REG_EJECUTIVO, DNIS AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_TRAFICO_GENESYS A, DLAB_GEC.M_EXP_VENTAS_CON B
			WHERE NUM_TELEFONO IS NOT NULL
			AND A.DNI = B.CODDOC
			AND A.USERNAME = B.CODPROMOT
			GROUP BY DNI, USERNAME, DNIS
			
			UNION ALL 
			
			--- TABLA DERIVABT 
			
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, REG_EJECUTIVO, TELF_ANI AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_DERIVA_BT_TIEMPOS A, DLAB_GEC.M_EXP_VENTAS_CON B
			WHERE A.DNI = B.CODDOC
			AND A.REG_EJECUTIVO = B.CODPROMOT
			AND NUM_TELEFONO IS NOT NULL
			AND NUM_TELEFONO NOT IN ('localhost')
			AND NUM_TELEFONO NOT LIKE ('%.%')
			GROUP BY DNI, REG_EJECUTIVO, TELF_ANI
			
			
			UNION ALL 
			
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, REG_EJECUTIVO, TELF_DNIS AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_DERIVA_BT_TIEMPOS A, DLAB_GEC.M_EXP_VENTAS_CON B
			WHERE A.DNI = B.CODDOC
			AND A.REG_EJECUTIVO = B.CODPROMOT
			AND NUM_TELEFONO IS NOT NULL
			AND NUM_DOCUMENTO IS NOT NULL
			AND NUM_TELEFONO NOT IN ('localhost')
			AND NUM_TELEFONO NOT LIKE ('%.%')
			AND NUM_TELEFONO NOT LIKE ('%11311%')
			AND REG_EJECUTIVO NOT LIKE ('%TLV_%')
			GROUP BY DNI, REG_EJECUTIVO, TELF_DNIS
			
			) X
  ) Z
  WHERE ROWX = 1
  AND NUM_DOCUMENTO IS NOT NULL;

-- AGREGAMOS RANGOS TIEMPO 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CON SET RANGO_TIEMPO ='[1MIN]' WHERE (TIEMPO  >=0 AND TIEMPO <=60);
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CON SET RANGO_TIEMPO ='[3MIN]' WHERE (TIEMPO  >=60.0 AND TIEMPO <=180); 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CON SET RANGO_TIEMPO ='[5MIN]' WHERE (TIEMPO  >=180.0 AND TIEMPO <=300);
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CON SET RANGO_TIEMPO ='[10MIN]' WHERE (TIEMPO  >=300.0 AND TIEMPO <=600); 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CON SET RANGO_TIEMPO ='[20MIN]' WHERE (TIEMPO  >=600.0 AND TIEMPO <=1200); 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CON SET RANGO_TIEMPO ='[+20]' WHERE (TIEMPO  >=1200 AND TIEMPO <=300000);




--- CRUCE CON GOBIERNO DE DATOS
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CON
FROM (
    SELECT CODDOC, NUMTELEFONO,
           ROW_NUMBER() OVER(PARTITION BY CODDOC, NUMTELEFONO ORDER BY CODDOC) AS RN
    FROM E_DW_VIEWS.V_CONT_TELEFONO_APICLIENTE
    WHERE FLG_VALIDADO = 1
    AND CODDOC IN (
        SELECT NUM_DOCUMENTO 
        FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CON
        WHERE TIPO_VAL IS NULL
    )
) B
SET GD_VAL = 1, TIPO_VAL = 'GOB DATOS'
WHERE NUM_DOCUMENTO = B.CODDOC
AND NUM_TELEFONO = B.NUMTELEFONO
AND B.RN = 1;

--- CRUCE CON CARGA - MES ACTUAL
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CON
FROM (
    SELECT NUMERO_DOCUMENTO, TELEFONO,
           ROW_NUMBER() OVER(PARTITION BY NUMERO_DOCUMENTO, TELEFONO ORDER BY NUMERO_DOCUMENTO) AS RN
    FROM DLAB_GEC.TLV_CARGA_ACTUAL
    WHERE TIP_CLIENTE IN ('CON')
) B
SET CA_VAL = 1, TIPO_VAL = 'CARGA ACTUAL'
WHERE NUM_DOCUMENTO = B.NUMERO_DOCUMENTO
AND NUM_TELEFONO = B.TELEFONO
AND TIPO_VAL IS NULL
AND B.RN = 1;

---- CRUCE CON DATA ENRICHMENT

UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CON
FROM (
    SELECT NUMERO_DOCUMENTO, TELEFONO,
           ROW_NUMBER() OVER(PARTITION BY NUMERO_DOCUMENTO, TELEFONO ORDER BY NUMERO_DOCUMENTO) AS RN
    FROM DLAB_GEC.TLV_CARGA_ACTUAL
    WHERE TIP_CLIENTE IN ('CON')
    AND REGEXP_SIMILAR(TRIM(CHANGE_N), '^[0-9]+$') = 1  -- Asegurar que CHANGE_N sea numérico
    AND CAST(TRIM(CHANGE_N) AS INTEGER) >= 12  -- Convertir a entero y comparar
) B
SET CA_VAL = 1, TIPO_VAL = 'ENRICHMENT'
WHERE NUM_DOCUMENTO = B.NUMERO_DOCUMENTO
AND NUM_TELEFONO = B.TELEFONO
AND TIPO_VAL IS NULL
AND B.RN = 1;



--- TABLA DE CAMPAÑAS 

UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CON
FROM (
    SELECT CODDOC, NRO_TELEFONO1,
           ROW_NUMBER() OVER(PARTITION BY CODDOC, NRO_TELEFONO1 ORDER BY CODDOC) AS RN
    FROM E_DW_VIEWS.V_AGG_CAMP_CONV_VIGENTE
    WHERE CODMES = :periodo_num  --------------------CAMBIAR
) B
SET FB_VAL = 1, TIPO_VAL = 'FB_LEADS'
WHERE NUM_DOCUMENTO = B.CODDOC
AND NUM_TELEFONO = B.NRO_TELEFONO1
AND TIPO_VAL IS NULL
AND B.RN = 1;

UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CON
FROM (
    SELECT CODDOC, NRO_TELEFONO2,
           ROW_NUMBER() OVER(PARTITION BY CODDOC, NRO_TELEFONO2 ORDER BY CODDOC) AS RN
    FROM E_DW_VIEWS.V_AGG_CAMP_CONV_VIGENTE
    WHERE CODMES = :periodo_num --------------------CAMBIAR
) B
SET FB_VAL = 1, TIPO_VAL = 'FB_LEADS'
WHERE NUM_DOCUMENTO = B.CODDOC
AND NUM_TELEFONO = B.NRO_TELEFONO2
AND TIPO_VAL IS NULL
AND B.RN = 1;

--- MONTO APROBADO - FECDESEMBOLSO - DIA 

UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CON 
FROM (
    SELECT CODDOC, MONTO_APROB, FECDESEMB, DIA,
           ROW_NUMBER() OVER(PARTITION BY CODDOC ORDER BY MONTO_APROB DESC) AS ROWX
    FROM DLAB_GEC.M_EXP_VENTAS_CON
) B
SET MONTO_APROB = B.MONTO_APROB, FECDESEMB = B.FECDESEMB, DIA = B.DIA 
WHERE NUM_DOCUMENTO = B.CODDOC
AND B.ROWX = 1;


------------------------------- END ---------------------------------

COLLECT STATISTICS ON DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CON COLUMN (NUM_DOCUMENTO);


-- ========================================== 
-- [PROCESANDO PRODUCTO: IL] 
-- ========================================== 
DELETE FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_IL ALL;

INSERT INTO DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_IL (NUM_DOCUMENTO, REG_EJECUTIVO, NUM_TELEFONO, TIEMPO, RANGO_TIEMPO, GD_VAL, CA_VAL, DE_VAL, TIPO_VAL, FB_VAL, GRUPO_ORIGEN, ORIGEN, MONTO_APROB, FECDESEMB, DIA)
SELECT 
NUM_DOCUMENTO, 
REG_EJECUTIVO, 
NUM_TELEFONO, 
TIEMPO_SEG AS TIEMPO,
CAST(NULL AS VARCHAR(20)) AS RANGO_TIEMPO,
CAST(NULL AS INT) AS GD_VAL,
CAST(NULL AS INT) AS CA_VAL,
CAST(NULL AS INT) AS DE_VAL,
CAST(NULL AS VARCHAR(50)) AS TIPO_VAL,
CAST(NULL AS INT) AS FB_VAL,
CAST(NULL AS VARCHAR(15)) AS GRUPO_ORIGEN,
CAST(NULL AS VARCHAR(15)) AS ORIGEN,
CAST(NULL AS INT) AS MONTO_APROB,
CAST(NULL AS VARCHAR(10)) AS FECDESEMB,
CAST(NULL AS INT) AS DIA

FROM (
			SELECT NUM_DOCUMENTO, REG_EJECUTIVO, NUM_TELEFONO, TIEMPO_SEG, ROW_NUMBER() OVER(PARTITION BY NUM_DOCUMENTO, REG_EJECUTIVO ORDER BY TIEMPO_SEG DESC) AS ROWX
			FROM (
			
			SELECT A.NUM_DOCUMENTO, A.REG_EJECUTIVO, A.TELEFONO AS NUM_TELEFONO, SUM(EXTRACT(HOUR FROM A.DURACION_LLAMADA) * 3600
																										 + EXTRACT(MINUTE FROM A.DURACION_LLAMADA) * 60
																										 + EXTRACT(SECOND FROM A.DURACION_LLAMADA)) AS TIEMPO_SEG
			FROM DLAB_GEC.TEMP_TRAFICO A, DLAB_GEC.M_EXP_VENTAS_IL B
			WHERE A.NUM_DOCUMENTO = B.CODDOC
			AND A.REG_EJECUTIVO = B.CODPROMOT
			GROUP BY A.NUM_DOCUMENTO, A.REG_EJECUTIVO, A.TELEFONO
			
			UNION ALL 
			
			--- TABLA GENESYS 
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, username AS REG_EJECUTIVO, ANI AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_TRAFICO_GENESYS A, DLAB_GEC.M_EXP_VENTAS_IL B
			WHERE NUM_TELEFONO IS NOT NULL 
			AND A.DNI = B.CODDOC
			AND A.USERNAME = B.CODPROMOT
			GROUP BY DNI, USERNAME, ANI
			
			UNION ALL
			
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, username AS REG_EJECUTIVO, DNIS AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_TRAFICO_GENESYS A, DLAB_GEC.M_EXP_VENTAS_IL B
			WHERE NUM_TELEFONO IS NOT NULL
			AND A.DNI = B.CODDOC
			AND A.USERNAME = B.CODPROMOT
			GROUP BY DNI, USERNAME, DNIS
			
			UNION ALL 
			
			--- TABLA DERIVABT 
			
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, REG_EJECUTIVO, TELF_ANI AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_DERIVA_BT_TIEMPOS A, DLAB_GEC.M_EXP_VENTAS_IL B
			WHERE A.DNI = B.CODDOC
			AND A.REG_EJECUTIVO = B.CODPROMOT
			AND NUM_TELEFONO IS NOT NULL
			AND NUM_TELEFONO NOT IN ('localhost')
			AND NUM_TELEFONO NOT LIKE ('%.%')
			GROUP BY DNI, REG_EJECUTIVO, TELF_ANI
			
			
			UNION ALL 
			
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, REG_EJECUTIVO, TELF_DNIS AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_DERIVA_BT_TIEMPOS A, DLAB_GEC.M_EXP_VENTAS_IL B
			WHERE A.DNI = B.CODDOC
			AND A.REG_EJECUTIVO = B.CODPROMOT
			AND NUM_TELEFONO IS NOT NULL
			AND NUM_DOCUMENTO IS NOT NULL
			AND NUM_TELEFONO NOT IN ('localhost')
			AND NUM_TELEFONO NOT LIKE ('%.%')
			AND NUM_TELEFONO NOT LIKE ('%11311%')
			AND REG_EJECUTIVO NOT LIKE ('%TLV_%')
			GROUP BY DNI, REG_EJECUTIVO, TELF_DNIS
			
			) X
  ) Z
  WHERE ROWX = 1
  AND NUM_DOCUMENTO IS NOT NULL;

-- AGREGAMOS RANGOS TIEMPO 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_IL SET RANGO_TIEMPO ='[1MIN]' WHERE (TIEMPO  >=0 AND TIEMPO <=60);
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_IL SET RANGO_TIEMPO ='[3MIN]' WHERE (TIEMPO  >=60.0 AND TIEMPO <=180); 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_IL SET RANGO_TIEMPO ='[5MIN]' WHERE (TIEMPO  >=180.0 AND TIEMPO <=300);
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_IL SET RANGO_TIEMPO ='[10MIN]' WHERE (TIEMPO  >=300.0 AND TIEMPO <=600); 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_IL SET RANGO_TIEMPO ='[20MIN]' WHERE (TIEMPO  >=600.0 AND TIEMPO <=1200); 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_IL SET RANGO_TIEMPO ='[+20]' WHERE (TIEMPO  >=1200 AND TIEMPO <=300000);



--- CRUCE CON GOBIERNO DE DATOS
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_IL
FROM (
    SELECT CODDOC, NUMTELEFONO,
           ROW_NUMBER() OVER(PARTITION BY CODDOC, NUMTELEFONO ORDER BY CODDOC) AS RN
    FROM E_DW_VIEWS.V_CONT_TELEFONO_APICLIENTE
    WHERE FLG_VALIDADO = 1
    AND CODDOC IN (
        SELECT NUM_DOCUMENTO 
        FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_IL
        WHERE TIPO_VAL IS NULL
    )
) B
SET GD_VAL = 1, TIPO_VAL = 'GOB DATOS'
WHERE NUM_DOCUMENTO = B.CODDOC
AND NUM_TELEFONO = B.NUMTELEFONO
AND B.RN = 1;

--- CRUCE CON CARGA - MES ACTUAL
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_IL
FROM (
    SELECT NUMERO_DOCUMENTO, TELEFONO,
           ROW_NUMBER() OVER(PARTITION BY NUMERO_DOCUMENTO, TELEFONO ORDER BY NUMERO_DOCUMENTO) AS RN
    FROM DLAB_GEC.TLV_CARGA_ACTUAL
    WHERE TIP_CLIENTE IN ('IL')
) B
SET CA_VAL = 1, TIPO_VAL = 'CARGA ACTUAL'
WHERE NUM_DOCUMENTO = B.NUMERO_DOCUMENTO
AND NUM_TELEFONO = B.TELEFONO
AND TIPO_VAL IS NULL
AND B.RN = 1;

---- CRUCE CON DATA ENRICHMENT
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_IL
FROM (
    SELECT NUMERO_DOCUMENTO, TELEFONO,
           ROW_NUMBER() OVER(PARTITION BY NUMERO_DOCUMENTO, TELEFONO ORDER BY NUMERO_DOCUMENTO) AS RN
    FROM DLAB_GEC.TLV_CARGA_ACTUAL
    WHERE TIP_CLIENTE IN ('IL')
    AND REGEXP_SIMILAR(TRIM(CHANGE_N), '^[0-9]+$') = 1  -- Asegurar que CHANGE_N sea numérico
    AND CAST(TRIM(CHANGE_N) AS INTEGER) >= 12  -- Convertir a entero y comparar
) B
SET CA_VAL = 1, TIPO_VAL = 'ENRICHMENT'
WHERE NUM_DOCUMENTO = B.NUMERO_DOCUMENTO
AND NUM_TELEFONO = B.TELEFONO
AND TIPO_VAL IS NULL
AND B.RN = 1;



--- TABLA DE CAMPAÑAS 

UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_IL
FROM (
    SELECT CODDOC, NRO_TELEFONO1,
           ROW_NUMBER() OVER(PARTITION BY CODDOC, NRO_TELEFONO1 ORDER BY CODDOC) AS RN
    FROM E_DW_VIEWS.V_AGG_CAMP_IL_VIGENTE
    WHERE CODMES = :periodo_num --------------------CAMBIAR
) B
SET FB_VAL = 1, TIPO_VAL = 'FB_LEADS'
WHERE NUM_DOCUMENTO = B.CODDOC
AND NUM_TELEFONO = B.NRO_TELEFONO1
AND TIPO_VAL IS NULL
AND B.RN = 1;

--- MONTO APROBADO - FECDESEMBOLSO - DIA 

UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_IL 
FROM (
    SELECT CODDOC, MONTO_APROB, FECDESEMBOLSO, DIA,
           ROW_NUMBER() OVER(PARTITION BY CODDOC ORDER BY MONTO_APROB DESC) AS ROWX
    FROM DLAB_GEC.M_EXP_VENTAS_IL
) B
SET MONTO_APROB = B.MONTO_APROB, FECDESEMB = B.FECDESEMBOLSO, DIA = B.DIA 
WHERE NUM_DOCUMENTO = B.CODDOC
AND B.ROWX = 1;


------------------------------- END ---------------------------------

COLLECT STATISTICS ON DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_IL COLUMN (NUM_DOCUMENTO);


-- ========================================== 
-- [PROCESANDO PRODUCTO: UPG] 
-- ========================================== 
DELETE FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_UPG ALL;

INSERT INTO DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_UPG (NUM_DOCUMENTO, REG_EJECUTIVO, NUM_TELEFONO, TIEMPO, RANGO_TIEMPO, GD_VAL, CA_VAL, DE_VAL, TIPO_VAL, FB_VAL, GRUPO_ORIGEN, ORIGEN, MONTO_APROB, FECDESEMB, DIA)
SELECT 
NUM_DOCUMENTO, 
REG_EJECUTIVO, 
NUM_TELEFONO, 
TIEMPO_SEG AS TIEMPO,
CAST(NULL AS VARCHAR(20)) AS RANGO_TIEMPO,
CAST(NULL AS INT) AS GD_VAL,
CAST(NULL AS INT) AS CA_VAL,
CAST(NULL AS INT) AS DE_VAL,
CAST(NULL AS VARCHAR(50)) AS TIPO_VAL,
CAST(NULL AS INT) AS FB_VAL,
CAST(NULL AS VARCHAR(15)) AS GRUPO_ORIGEN,
CAST(NULL AS VARCHAR(15)) AS ORIGEN,
CAST(NULL AS INT) AS MONTO_APROB,
CAST(NULL AS VARCHAR(10)) AS FECDESEMB,
CAST(NULL AS INT) AS DIA

FROM (
			SELECT NUM_DOCUMENTO, REG_EJECUTIVO, NUM_TELEFONO, TIEMPO_SEG, ROW_NUMBER() OVER(PARTITION BY NUM_DOCUMENTO, REG_EJECUTIVO ORDER BY TIEMPO_SEG DESC) AS ROWX
			FROM (
			
			SELECT A.NUM_DOCUMENTO, A.REG_EJECUTIVO, A.TELEFONO AS NUM_TELEFONO, SUM(EXTRACT(HOUR FROM A.DURACION_LLAMADA) * 3600
																										 + EXTRACT(MINUTE FROM A.DURACION_LLAMADA) * 60
																										 + EXTRACT(SECOND FROM A.DURACION_LLAMADA)) AS TIEMPO_SEG
			FROM DLAB_GEC.TEMP_TRAFICO A, DLAB_GEC.M_EXP_VENTAS_UPG B
			WHERE A.NUM_DOCUMENTO = B.CODDOC
			AND A.REG_EJECUTIVO = B.CODPROMOT
			GROUP BY A.NUM_DOCUMENTO, A.REG_EJECUTIVO, A.TELEFONO
			
			UNION ALL 
			
			--- TABLA GENESYS 
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, username AS REG_EJECUTIVO, ANI AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_TRAFICO_GENESYS A, DLAB_GEC.M_EXP_VENTAS_UPG B
			WHERE NUM_TELEFONO IS NOT NULL 
			AND A.DNI = B.CODDOC
			AND A.USERNAME = B.CODPROMOT
			GROUP BY DNI, USERNAME, ANI
			
			UNION ALL
			
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, username AS REG_EJECUTIVO, DNIS AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_TRAFICO_GENESYS A, DLAB_GEC.M_EXP_VENTAS_UPG B
			WHERE NUM_TELEFONO IS NOT NULL
			AND A.DNI = B.CODDOC
			AND A.USERNAME = B.CODPROMOT
			GROUP BY DNI, USERNAME, DNIS
			
			UNION ALL 
			
			--- TABLA DERIVABT 
			
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, REG_EJECUTIVO, TELF_ANI AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_DERIVA_BT_TIEMPOS A, DLAB_GEC.M_EXP_VENTAS_UPG B
			WHERE A.DNI = B.CODDOC
			AND A.REG_EJECUTIVO = B.CODPROMOT
			AND NUM_TELEFONO IS NOT NULL
			AND NUM_TELEFONO NOT IN ('localhost')
			AND NUM_TELEFONO NOT LIKE ('%.%')
			GROUP BY DNI, REG_EJECUTIVO, TELF_ANI
			
			
			UNION ALL 
			
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, REG_EJECUTIVO, TELF_DNIS AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_DERIVA_BT_TIEMPOS A, DLAB_GEC.M_EXP_VENTAS_UPG B
			WHERE A.DNI = B.CODDOC
			AND A.REG_EJECUTIVO = B.CODPROMOT
			AND NUM_TELEFONO IS NOT NULL
			AND NUM_DOCUMENTO IS NOT NULL
			AND NUM_TELEFONO NOT IN ('localhost')
			AND NUM_TELEFONO NOT LIKE ('%.%')
			AND NUM_TELEFONO NOT LIKE ('%11311%')
			AND REG_EJECUTIVO NOT LIKE ('%TLV_%')
			GROUP BY DNI, REG_EJECUTIVO, TELF_DNIS
			
			) X
  ) Z
  WHERE ROWX = 1
  AND NUM_DOCUMENTO IS NOT NULL;

-- AGREGAMOS RANGOS TIEMPO 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_UPG SET RANGO_TIEMPO ='[1MIN]' WHERE (TIEMPO  >=0 AND TIEMPO <=60);
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_UPG SET RANGO_TIEMPO ='[3MIN]' WHERE (TIEMPO  >=60.0 AND TIEMPO <=180); 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_UPG SET RANGO_TIEMPO ='[5MIN]' WHERE (TIEMPO  >=180.0 AND TIEMPO <=300);
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_UPG SET RANGO_TIEMPO ='[10MIN]' WHERE (TIEMPO  >=300.0 AND TIEMPO <=600); 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_UPG SET RANGO_TIEMPO ='[20MIN]' WHERE (TIEMPO  >=600.0 AND TIEMPO <=1200); 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_UPG SET RANGO_TIEMPO ='[+20]' WHERE (TIEMPO  >=1200 AND TIEMPO <=300000);




--- CRUCE CON GOBIERNO DE DATOS
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_UPG
FROM  (SELECT DISTINCT CODDOC, NUMTELEFONO 
		FROM E_DW_VIEWS.V_CONT_TELEFONO_APICLIENTE
		WHERE FLG_VALIDADO=1
		AND CODDOC IN (SELECT NUM_DOCUMENTO FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_UPG
						WHERE TIPO_VAL IS NULL)) B
SET GD_VAL  = 1, TIPO_VAL = 'GOB DATOS'
WHERE NUM_DOCUMENTO = B.CODDOC
AND NUM_TELEFONO = B.NUMTELEFONO;


--- CRUCE CON CARGA - MES ACTUAL

UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_UPG
FROM (
    SELECT NUMERO_DOCUMENTO, TELEFONO
    FROM DLAB_GEC.TLV_CARGA_ACTUAL
    WHERE TIP_CLIENTE = 'UPG'
    QUALIFY ROW_NUMBER() OVER (PARTITION BY NUMERO_DOCUMENTO, TELEFONO ORDER BY NUMERO_DOCUMENTO) = 1
) AS B
SET CA_VAL = 1,
    TIPO_VAL = 'CARGA ACTUAL'
WHERE NUM_DOCUMENTO = B.NUMERO_DOCUMENTO
  AND NUM_TELEFONO = B.TELEFONO
  AND TIPO_VAL IS NULL;



---- CRUCE CON DATA ENRICHMENT
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_UPG
FROM (SELECT * FROM DLAB_GEC.TLV_CARGA_ACTUAL
		WHERE TIP_CLIENTE IN ('UPG')
		AND CHANGE_N >= 11) B
SET CA_VAL = 1, TIPO_VAL = 'ENRICHMENT'
WHERE NUM_DOCUMENTO = B.NUMERO_DOCUMENTO
AND NUM_TELEFONO = B.TELEFONO
AND TIPO_VAL IS NULL;



--- TABLA DE CAMPAÑAS 

UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_UPG
FROM (SELECT DISTINCT CODDOC, NRO_TELEFONO1 FROM E_DW_VIEWS.V_AGG_CAMP_UPG_VIGENTE
	WHERE CODMES = :periodo_num) B ---------------------------------------------CAMBIAR
SET FB_VAL = 1, TIPO_VAL = 'FB_LEADS'
WHERE NUM_DOCUMENTO = B.CODDOC
AND NUM_TELEFONO = B.NRO_TELEFONO1
AND TIPO_VAL IS NULL;



--- MONTO APROBADO - FECDESEMBOLSO -  DIA 

UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_UPG 
FROM (SELECT * FROM (
		SELECT DISTINCT CODDOC, MONTO_APROB, FECDESEMBOLSO, DIA, ROW_NUMBER() OVER(PARTITION BY CODDOC ORDER BY MONTO_APROB DESC) AS ROWX
		FROM DLAB_GEC.M_EXP_VENTAS_UPG ) X
		WHERE ROWX = 1) B
SET MONTO_APROB = B.MONTO_APROB, FECDESEMB = B.FECDESEMBOLSO, DIA = B.DIA 
WHERE NUM_DOCUMENTO = B.CODDOC;

------------------------------- END ---------------------------------

COLLECT STATISTICS ON DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_UPG COLUMN (NUM_DOCUMENTO);


-- ========================================== 
-- [PROCESANDO PRODUCTO: TCA] 
-- ========================================== 
DELETE FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TCA ALL;

INSERT INTO DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TCA (NUM_DOCUMENTO, REG_EJECUTIVO, NUM_TELEFONO, TIEMPO, RANGO_TIEMPO, GD_VAL, CA_VAL, DE_VAL, TIPO_VAL, FB_VAL, GRUPO_ORIGEN, ORIGEN, MONTO_APROB, FECDESEMB, DIA)
SELECT 
NUM_DOCUMENTO, 
REG_EJECUTIVO, 
NUM_TELEFONO, 
TIEMPO_SEG AS TIEMPO,
CAST(NULL AS VARCHAR(20)) AS RANGO_TIEMPO,
CAST(NULL AS INT) AS GD_VAL,
CAST(NULL AS INT) AS CA_VAL,
CAST(NULL AS INT) AS DE_VAL,
CAST(NULL AS VARCHAR(50)) AS TIPO_VAL,
CAST(NULL AS INT) AS FB_VAL,
CAST(NULL AS VARCHAR(15)) AS GRUPO_ORIGEN,
CAST(NULL AS VARCHAR(15)) AS ORIGEN,
CAST(NULL AS INT) AS MONTO_APROB,
CAST(NULL AS VARCHAR(10)) AS FECDESEMB,
CAST(NULL AS INT) AS DIA

FROM (
			SELECT NUM_DOCUMENTO, REG_EJECUTIVO, NUM_TELEFONO, TIEMPO_SEG, ROW_NUMBER() OVER(PARTITION BY NUM_DOCUMENTO, REG_EJECUTIVO ORDER BY TIEMPO_SEG DESC) AS ROWX
			FROM (
			
			SELECT A.NUM_DOCUMENTO, A.REG_EJECUTIVO, A.TELEFONO AS NUM_TELEFONO, SUM(EXTRACT(HOUR FROM A.DURACION_LLAMADA) * 3600
																										 + EXTRACT(MINUTE FROM A.DURACION_LLAMADA) * 60
																										 + EXTRACT(SECOND FROM A.DURACION_LLAMADA)) AS TIEMPO_SEG
			FROM DLAB_GEC.TEMP_TRAFICO A, DLAB_GEC.M_EXP_VENTAS_TCA B
			WHERE A.NUM_DOCUMENTO = B.CODDOC
			AND A.REG_EJECUTIVO = B.CODPROMOT
			GROUP BY A.NUM_DOCUMENTO, A.REG_EJECUTIVO, A.TELEFONO
			
			UNION ALL 
			
			--- TABLA GENESYS 
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, username AS REG_EJECUTIVO, ANI AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_TRAFICO_GENESYS A, DLAB_GEC.M_EXP_VENTAS_TCA B
			WHERE NUM_TELEFONO IS NOT NULL 
			AND A.DNI = B.CODDOC
			AND A.USERNAME = B.CODPROMOT
			GROUP BY DNI, USERNAME, ANI
			
			UNION ALL
			
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, username AS REG_EJECUTIVO, DNIS AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_TRAFICO_GENESYS A, DLAB_GEC.M_EXP_VENTAS_TCA B
			WHERE NUM_TELEFONO IS NOT NULL
			AND A.DNI = B.CODDOC
			AND A.USERNAME = B.CODPROMOT
			GROUP BY DNI, USERNAME, DNIS
			
			UNION ALL 
			
			--- TABLA DERIVABT 
			
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, REG_EJECUTIVO, TELF_ANI AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_DERIVA_BT_TIEMPOS A, DLAB_GEC.M_EXP_VENTAS_TCA B
			WHERE A.DNI = B.CODDOC
			AND A.REG_EJECUTIVO = B.CODPROMOT
			AND NUM_TELEFONO IS NOT NULL
			AND NUM_TELEFONO NOT IN ('localhost')
			AND NUM_TELEFONO NOT LIKE ('%.%')
			GROUP BY DNI, REG_EJECUTIVO, TELF_ANI
			
			
			UNION ALL 
			
			SELECT DISTINCT DNI AS NUM_DOCUMENTO, REG_EJECUTIVO, TELF_DNIS AS NUM_TELEFONO,
			SUM(((EXTRACT(  HOUR FROM sessionendtime) - EXTRACT(HOUR FROM sessionstarttime))) * 3600
			      + ((EXTRACT(MINUTE FROM sessionendtime) - EXTRACT(MINUTE FROM sessionstarttime)) * 60)
			      + ((EXTRACT(SECOND FROM sessionendtime) - EXTRACT(SECOND FROM sessionstarttime)))) AS TIEMPO_SEG 
			      FROM DLAB_GEC.M_EXP_DERIVA_BT_TIEMPOS A, DLAB_GEC.M_EXP_VENTAS_TCA B
			WHERE A.DNI = B.CODDOC
			AND A.REG_EJECUTIVO = B.CODPROMOT
			AND NUM_TELEFONO IS NOT NULL
			AND NUM_DOCUMENTO IS NOT NULL
			AND NUM_TELEFONO NOT IN ('localhost')
			AND NUM_TELEFONO NOT LIKE ('%.%')
			AND NUM_TELEFONO NOT LIKE ('%11311%')
			AND REG_EJECUTIVO NOT LIKE ('%TLV_%')
			GROUP BY DNI, REG_EJECUTIVO, TELF_DNIS
			
			) X
  ) Z
  WHERE ROWX = 1
  AND NUM_DOCUMENTO IS NOT NULL;

-- AGREGAMOS RANGOS TIEMPO 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TCA SET RANGO_TIEMPO ='[1MIN]' WHERE (TIEMPO  >=0 AND TIEMPO <=60);
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TCA SET RANGO_TIEMPO ='[3MIN]' WHERE (TIEMPO  >=60.0 AND TIEMPO <=180); 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TCA SET RANGO_TIEMPO ='[5MIN]' WHERE (TIEMPO  >=180.0 AND TIEMPO <=300);
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TCA SET RANGO_TIEMPO ='[10MIN]' WHERE (TIEMPO  >=300.0 AND TIEMPO <=600); 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TCA SET RANGO_TIEMPO ='[20MIN]' WHERE (TIEMPO  >=600.0 AND TIEMPO <=1200); 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TCA SET RANGO_TIEMPO ='[+20]' WHERE (TIEMPO  >=1200 AND TIEMPO <=300000);




--- CRUCE CON GOBIERNO DE DATOS
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TCA
FROM  (SELECT DISTINCT CODDOC, NUMTELEFONO 
		FROM E_DW_VIEWS.V_CONT_TELEFONO_APICLIENTE
		WHERE FLG_VALIDADO=1
		AND CODDOC IN (SELECT NUM_DOCUMENTO FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TCA
						WHERE TIPO_VAL IS NULL)) B
SET GD_VAL  = 1, TIPO_VAL = 'GOB DATOS'
WHERE NUM_DOCUMENTO = B.CODDOC
AND NUM_TELEFONO = B.NUMTELEFONO;


--- CRUCE CON CARGA - MES ACTUAL
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TCA
FROM (SELECT * FROM DLAB_GEC.TLV_CARGA_ACTUAL
		WHERE TIP_CLIENTE IN ('TCA')) B
SET CA_VAL = 1, TIPO_VAL = 'CARGA ACTUAL'
WHERE NUM_DOCUMENTO = B.NUMERO_DOCUMENTO
AND NUM_TELEFONO = B.TELEFONO
AND TIPO_VAL IS NULL;


---- CRUCE CON DATA ENRICHMENT
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TCA
FROM (SELECT * FROM DLAB_GEC.TLV_CARGA_ACTUAL
		WHERE TIP_CLIENTE IN ('TCA')
		AND CHANGE_N >= 11) B
SET CA_VAL = 1, TIPO_VAL = 'ENRICHMENT'
WHERE NUM_DOCUMENTO = B.NUMERO_DOCUMENTO
AND NUM_TELEFONO = B.TELEFONO
AND TIPO_VAL IS NULL;



--- TABLA DE CAMPAÑAS 

UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TCA
FROM (SELECT DISTINCT CODDOC, NRO_TELEFONO1 FROM E_DW_VIEWS.V_AGG_CAMP_TC_ADIC_VIGENTE
	WHERE CODMES = :periodo_num) B ---------------------------------------------CAMBIAR
SET FB_VAL = 1, TIPO_VAL = 'FB_LEADS'
WHERE NUM_DOCUMENTO = B.CODDOC
AND NUM_TELEFONO = B.NRO_TELEFONO1
AND TIPO_VAL IS NULL;

/*
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TCA
FROM (SELECT DISTINCT CODDOC, NRO_TELEFONO2 FROM E_DW_VIEWS.V_AGG_CAMP_TC_ADIC_VIGENTE
	WHERE CODMES = :periodo_num) B ---------------------------------------------CAMBIAR
SET FB_VAL = 1, TIPO_VAL = 'FB_LEADS'
WHERE NUM_DOCUMENTO = B.CODDOC
AND NUM_TELEFONO = B.NRO_TELEFONO2
AND TIPO_VAL IS NULL;
*/


--- MONTO APROBADO - FECDESEMBOLSO -  DIA 

UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TCA 
FROM (SELECT * FROM (
		SELECT DISTINCT CODDOC, MONTO_APROB, FECDESEMBOLSO, DIA, ROW_NUMBER() OVER(PARTITION BY CODDOC ORDER BY MONTO_APROB DESC) AS ROWX
		FROM DLAB_GEC.M_EXP_VENTAS_TCA ) X
		WHERE ROWX = 1) B
SET MONTO_APROB = B.MONTO_APROB, FECDESEMB = B.FECDESEMBOLSO, DIA = B.DIA 
WHERE NUM_DOCUMENTO = B.CODDOC;

------------------------------- END ---------------------------------

COLLECT STATISTICS ON DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TCA COLUMN (NUM_DOCUMENTO);


-- ========================================== 
-- [PROCESANDO UNIFICACION ALL Y TABLAS FINALES] 
-- ========================================== 
DELETE FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_ALL ALL;

INSERT INTO DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_ALL (PRODUCTO, NUM_DOCUMENTO, REG_EJECUTIVO, NUM_TELEFONO, TIEMPO, RANGO_TIEMPO, GD_VAL, CA_VAL, DE_VAL, TIPO_VAL, FB_VAL, GRUPO_ORIGEN, ORIGEN, MONTO_APROB, FECDESEMB, DIA, FLAG_SEG, FLAG_CD40K, REQUIERE_VAL, VALIDACION_CORRECTA, VALIDACION_SIN_VAL, VALIDACION_FALLIDA, TRANSFER_IVR, FLAG_EVALUADO, FLAG_REGISTRO)
SELECT
X.*,
CAST(NULL AS VARCHAR(5)) AS FLAG_SEG,
CAST(NULL AS VARCHAR(5)) AS FLAG_CD40K,
CAST(NULL AS INT) AS REQUIERE_VAL,
CAST(NULL AS INT) AS VALIDACION_CORRECTA,
CAST(NULL AS INT) AS VALIDACION_SIN_VAL,
CAST(NULL AS INT) AS VALIDACION_FALLIDA,
CAST(NULL AS VARCHAR(50)) AS TRANSFER_IVR,
CAST(NULL AS VARCHAR(20)) AS FLAG_EVALUADO,
CAST(NULL AS INT) AS FLAG_REGISTRO

FROM (

SELECT CAST('TC' AS VARCHAR(10)) AS PRODUCTO, A.* FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TC A
UNION ALL
SELECT CAST('PP' AS VARCHAR(10)) AS PRODUCTO, A.* FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_PP A
UNION ALL
SELECT CAST('EC' AS VARCHAR(10)) AS PRODUCTO, A.* FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_EC A
UNION ALL
SELECT CAST('CD' AS VARCHAR(10)) AS PRODUCTO, A.* FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CD A
UNION ALL
SELECT CAST('CON' AS VARCHAR(10)) AS PRODUCTO, A.* FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_CON A
UNION ALL
SELECT CAST('IL' AS VARCHAR(10)) AS PRODUCTO, A.* FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_IL A
UNION ALL
SELECT CAST('UPG' AS VARCHAR(10)) AS PRODUCTO, A.* FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_UPG A
UNION ALL
SELECT CAST('TCA' AS VARCHAR(10)) AS PRODUCTO, A.* FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_TCA A
) X
--WHERE TIPO_VAL IS NULL
WHERE NUM_TELEFONO IS NOT NULL;

-- FLAG SEGUROS 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_ALL
FROM (SELECT DISTINCT CODDOC, CODPROMOT FROM DLAB_GEC.M_EXP_VENTAS_TC
	 WHERE FLAGSEGURO = 1) B
SET FLAG_SEG = 'SI'
WHERE NUM_DOCUMENTO = B.CODDOC
AND REG_EJECUTIVO = B.CODPROMOT 
AND PRODUCTO = 'TC';


UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_ALL
FROM (SELECT DISTINCT CODDOC, CODPROMOT FROM DLAB_GEC.M_EXP_VENTAS_PP
	 WHERE SEGURO_FLG = 1) B
SET FLAG_SEG = 'SI'
WHERE NUM_DOCUMENTO = B.CODDOC
AND REG_EJECUTIVO = B.CODPROMOT 
AND PRODUCTO = 'PP';


UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_ALL
FROM (SELECT DISTINCT CODDOC, CODPROMOT FROM DLAB_GEC.M_EXP_VENTAS_EC
	 WHERE FLAGSEGURO = 1) B
SET FLAG_SEG = 'SI'
WHERE NUM_DOCUMENTO = B.CODDOC
AND REG_EJECUTIVO = B.CODPROMOT 
AND PRODUCTO = 'EC';


--- FLAG CD40K
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_ALL
FROM (SELECT DISTINCT CODDOC, CODPROMOT FROM DLAB_GEC.M_EXP_VENTAS_CD
	 WHERE FLAG_CD40 = 'SI') B
SET FLAG_CD40K = 'SI'
WHERE NUM_DOCUMENTO = B.CODDOC
AND REG_EJECUTIVO = B.CODPROMOT 
AND PRODUCTO = 'CD';



--- VALIDACIÓN IVR 
UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_ALL
FROM  (SELECT DISTINCT CODDOC, CODPROMOT, REQUIERE_VAL, TIENE_VAL_EXITOSA, SIN_VAL, SIN_VAL_FALLIDA FROM DLAB_GEC.M_EXP_VALIDACIONES_IVR_EQ) B
SET REQUIERE_VAL = B.REQUIERE_VAL, VALIDACION_CORRECTA = B.TIENE_VAL_EXITOSA, VALIDACION_SIN_VAL = B.SIN_VAL, VALIDACION_FALLIDA = B.SIN_VAL_FALLIDA
WHERE NUM_DOCUMENTO = B.CODDOC
AND REG_EJECUTIVO = B.CODPROMOT;

UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_ALL  SET FLAG_EVALUADO = 'NO';

UPDATE DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_ALL 
FROM (SELECT * FROM DLAB_GEC.M_EXP_DOCUMENTOS_EVALUADOS) B
SET FLAG_EVALUADO = 'SI'
WHERE NUM_DOCUMENTO = B.DOCUMENTO;

-- [PASO 3]: Copiar a la tabla final nominal (Data Flow TLF NO AUTORIZADO)
DELETE FROM DLAB_GEC.T_EXP_KRI_TELF_NO_AUTORIZADO ALL;

INSERT INTO DLAB_GEC.T_EXP_KRI_TELF_NO_AUTORIZADO (
    PRODUCTO, NUM_DOCUMENTO, REG_EJECUTIVO, NUM_TELEFONO, TIEMPO, RANGO_TIEMPO, 
    X1, GD_VAL, CA_VAL, DE_VAL, TIPO_VAL, FB_VAL, GRUPO_ORIGEN, ORIGEN, 
    MONTO_APROB, FECDESEMB, MONTO_RANGO, DATE_BK
)
SELECT 
    PRODUCTO,
    NUM_DOCUMENTO,
    REG_EJECUTIVO,
    NUM_TELEFONO,
    TIEMPO,
    RANGO_TIEMPO,
    1 AS X1,
    GD_VAL,
    CA_VAL,
    DE_VAL,
    TIPO_VAL,
    FB_VAL,
    GRUPO_ORIGEN,
    ORIGEN,
    MONTO_APROB,
    FECDESEMB,
    CAST(NULL AS VARCHAR(20)) AS MONTO_RANGO,
    CURRENT_TIMESTAMP(0) AS DATE_BK
FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_ALL;

COLLECT STATISTICS ON DLAB_GEC.T_EXP_KRI_TELF_NO_AUTORIZADO COLUMN (NUM_DOCUMENTO);


-- [PASO 4]: Copiar a la tabla final de Calidad PBI (Data Flow TLF NO AUTO- CALIDAD)
DELETE FROM DLAB_GEC.T_EXP_KRI_TELF_NO_AUTORIZADO_CALIDAD ALL;

INSERT INTO DLAB_GEC.T_EXP_KRI_TELF_NO_AUTORIZADO_CALIDAD (
    PRODUCTO, NUM_DOCUMENTO, REG_EJECUTIVO, NOM_EJECUTIVO, NOM_SUPERVISOR, 
    NUM_TELEFONO, RANGO_TIEMPO, GRUPO_ORIGEN, ORIGEN, MONTO_APROB, FLAG_SEG, 
    FLAG_CD40K, VALIDACION_CORRECTA, VALIDACION_SIN_VAL, VALIDACION_FALLIDA, 
    REQUIERE_VAL, TRANSFER_IVR, FLAG_EVALUADO, FECDESEMB, DIA, FLAG_REGISTRO
)
SELECT 
    A.PRODUCTO,
    A.NUM_DOCUMENTO,
    A.REG_EJECUTIVO,
    B.NOM_EJECUTIVO,
    B.NOM_SUPERVISOR,
    A.NUM_TELEFONO,
    A.RANGO_TIEMPO,
    A.GRUPO_ORIGEN,
    A.ORIGEN,
    A.MONTO_APROB,
    A.FLAG_SEG,
    A.FLAG_CD40K,
    A.VALIDACION_CORRECTA,
    A.VALIDACION_SIN_VAL,
    A.VALIDACION_FALLIDA,
    A.REQUIERE_VAL,
    A.TRANSFER_IVR,
    A.FLAG_EVALUADO,
    A.FECDESEMB,
    A.DIA,
    NULL AS FLAG_REGISTRO
FROM DLAB_GEC.M_EXP_TLFNO_AUTORIZADO_ALL A
INNER JOIN DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS B 
    ON A.REG_EJECUTIVO = B.REG_EJECUTIVO;

COLLECT STATISTICS ON DLAB_GEC.T_EXP_KRI_TELF_NO_AUTORIZADO_CALIDAD COLUMN (NUM_DOCUMENTO);
