-- ==============================================================================
-- PROCESO: VENTAS_DN (Ventas por Producto del Mes)
-- OPTIMIZACIÓN: 
--   1. Reemplazo de DROPs por DELETE ALL (Fastpath en Teradata).
--   2. Cálculo de flags de seguros e indicadores inline con LEFT JOINs.
--   3. Recolección de estadísticas automáticas (COLLECT STATISTICS) al final.
-- ==============================================================================

-- DTC: Tarjetas de Crédito
DELETE FROM DLAB_GEC.M_EXP_VENTAS_TC ALL;

INSERT INTO DLAB_GEC.M_EXP_VENTAS_TC (
    MESDESEMBOLSO, TIP_CLIENTE, GESTION, CODPROMOT, NOMPROMOT, NOMSUPER, EQUIPO, 
    SUB_EQUIPO, FECDESEMB, DIA, CODDOC, MONTO_APROB, ESTADO, TIPOAPROB, DISPOEFECT, 
    ESTACIVIL, SITLABORAL, CORREO, TELCELUL, ECREGIST, FECENTREGA, FECACTIVA, 
    NOMCLIENTE, TARJETA_NUM, FLAGSEGURO
)
SELECT 
    A.PERIODO_VAL AS MESDESEMBOLSO,
    'DTC' AS TIP_CLIENTE,
    'TLV' AS GESTION,
    A.PROMOTOR_CD AS CODPROMOT,
    A.PROMOTOR_NM AS NOMPROMOT,
    A.SUPERVISOR_NM AS NOMSUPER,
    A.EquipoVenta_Dsc AS EQUIPO,
    A.SubEquipoVenta_Dsc AS SUB_EQUIPO,
    A.AprobacionExpedADQ_Fc AS FECDESEMB,
    EXTRACT(DAY FROM AprobacionExpedADQ_Fc) AS DIA,
    TRIM(A.DOCUMENTO_NUM) AS CODDOC,
    A.LineaTc_Amt AS MONTO_APROB,
    A.EstadoSolicitud_Dsc AS ESTADO, 
    A.TipoTcAprobada_Dsc AS TIPOAPROB, 
    A.DisposicionEfectivo_Amt AS DISPOEFECT, 
    A.EstadoCivilCli_Dsc AS ESTACIVIL, 
    A.SituacionLaboralCli_Dsc AS SITLABORAL,
    A.CorreoCli_Dsc AS CORREO,		
    A.TelefonoCelular_Num AS TELCELUL,
    A.IngresoExpedADQ_Fc AS ECREGIST,
    A.EntregaTc_Fc AS FECENTREGA, 
    A.ActivaTc_Fc AS FECACTIVA, 
    A.Cliente_Nm AS NOMCLIENTE,
    A.TARJETA_NUM,
    CASE WHEN seg.DNI_TITULAR IS NOT NULL THEN 1 ELSE NULL END AS FLAGSEGURO
FROM E_DW_VIEWS.V_FCT_RT_TC_HISTORICO A
LEFT JOIN (
    SELECT DISTINCT DNI_TITULAR, CODPROMOT 
    FROM E_DW_VIEWS_DLAB.V_DLAB_CGR_SEGUROS_VENTAS 
    WHERE MESVENTA = :periodo
      AND PRODUCTO = 'IBK - SEGURO PROTECCION DE TARJETAS 360'
) seg
  ON TRIM(A.DOCUMENTO_NUM) = TRIM(seg.DNI_TITULAR)
 AND A.PROMOTOR_CD = seg.CODPROMOT
WHERE A.mesingresoexpedADQ_DSC = :periodo
  AND A.PROMOTOR_CD IN (SELECT REG_EJECUTIVO FROM DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS WHERE SUB_EQUIPO='TC')
  AND A.EquipoVenta_Dsc IN ('TLV TARJETAS','Televentas')
  AND A.ESTADOSOLICITUD_DSC = 'Aprobado'
  AND A.TIPOTRAMITE_DSC <> 'MIGRACIÓN TC'
  AND A.OPERACION_CD IN (1,2)
  AND A.ESTADOSOLICITUD_CD IN (3);

COLLECT STATISTICS ON DLAB_GEC.M_EXP_VENTAS_TC COLUMN (CODDOC, CODPROMOT);


-- DPP: Préstamos Personales
DELETE FROM DLAB_GEC.M_EXP_VENTAS_PP ALL;

INSERT INTO DLAB_GEC.M_EXP_VENTAS_PP (
    MESDESEMBOLSO, TIP_CLIENTE, GESTION, CODPROMOT, NOMPROMOT, NOMSUPER, EQUIPO, 
    SUB_EQUIPO, FECDESEMB, DIA, CODDOC, MONTO_APROB, GRUPOESTADO, F_DESEMBOLSO, 
    TELCELUL, FECHOREGI, SEGMENTOIBK, NUMPLAZO, ESTCIVIL, NOMCLIENTE, SEGURO_FLG
)
SELECT 
    PERIODO_VAL AS MESDESEMBOLSO,
    'DPP' AS TIP_CLIENTE,
    'TLV' AS GESTION,
    PROMOTOR_CD AS CODPROMOT,
    PROMOTOR_NM AS NOMPROMOT,
    SUPERVISOR_NM AS NOMSUPER,
    EQUIPO_DSC AS EQUIPO,
    SUBEQUIPO_DSC AS SUB_EQUIPO,
    DESEMBOLSO_FC AS FECDESEMB,
    EXTRACT(DAY FROM DESEMBOLSO_FC) AS DIA,
    TRIM(DOCUMENTO_TITULAR_NUM) AS CODDOC,
    DESEMBOLSO_AMT AS MONTO_APROB, 
    GRUPO_ESTADO_DSC AS GRUPOESTADO, 
    DESEMBOLSADO_FLG AS F_DESEMBOLSO,
    TELEFONO_CELULAR_NUM AS TELCELUL,
    REGISTRO_FC AS FECHOREGI, 
    SEGMENTO_DSC AS SEGMENTOIBK, 
    PLAZO_CNT AS NUMPLAZO,
    ESTADO_CIVIL_DSC AS ESTCIVIL,
    CLIENTE_NM AS NOMCLIENTE,
    SEGURO_FLG
FROM E_DW_VIEWS_DLAB.CGR_PRESTAMOS 
WHERE PERIODO_VAL = :periodo 
  AND PROMOTOR_CD IN (SELECT REG_EJECUTIVO FROM DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS WHERE SUB_EQUIPO='PP')
  AND DESEMBOLSO_AMT IS NOT NULL
  AND PERIODO_DESEMBOLSO_VAL IS NOT NULL;

COLLECT STATISTICS ON DLAB_GEC.M_EXP_VENTAS_PP COLUMN (CODDOC);


-- DEC: Extra Cash
DELETE FROM DLAB_GEC.M_EXP_VENTAS_EC ALL;

INSERT INTO DLAB_GEC.M_EXP_VENTAS_EC (
    MESDESEMBOLSO, TIP_CLIENTE, GESTION, CODPROMOT, NOMPROMOT, NOMSUPER, EQUIPO, 
    SUB_EQUIPO, FECDESEMB, DIA, CODDOC, MONTO_APROB, TASA_MENSUAL, CANT_CUOTAS, 
    FLAGSEGURO, APLICAT, NOMCLIENTE
)
SELECT
    PERIODO_VAL AS MESDESEMBOLSO,
    'DEC' AS TIP_CLIENTE,
    'TLV' AS GESTION,
    PROMOTOR_CD AS CODPROMOT,
    PROMOTOR_DSC AS NOMPROMOT,
    SUPERVISOR_DSC AS NOMSUPER,
    EQUIPO_DSC AS EQUIPO,
    SUBEQUIPO_DSC AS SUB_EQUIPO,
    DESEMBOLSO_FC AS FECDESEMB,
    EXTRACT(DAY FROM DESEMBOLSO_FC) AS DIA,
    DOCUMENTO_NUM AS CODDOC,
    DESEMBOLSO_AMT AS MONTO_APROB,
    TASA_MENSUAL_VAL AS TASA_MENSUAL, 
    CUOTAS_CNT AS CANT_CUOTAS,
    FLAGSEGURO, 
    APLICATIVO AS APLICAT,
    CLIENTE_DESC AS NOMCLIENTE
FROM E_DW_VIEWS_DLAB.CGR_EXTRACASH
WHERE PERIODO_VAL = :periodo 
  AND PROMOTOR_CD IN (SELECT REG_EJECUTIVO FROM DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS WHERE SUB_EQUIPO='EC')
  AND VALIDO_FLG = 'S'
  AND DESEMBOLSO_AMT IS NOT NULL;

COLLECT STATISTICS ON DLAB_GEC.M_EXP_VENTAS_EC COLUMN (CODDOC);


-- DCD: Compra de Deuda
DELETE FROM DLAB_GEC.M_EXP_VENTAS_CD ALL;

INSERT INTO DLAB_GEC.M_EXP_VENTAS_CD (
    MESDESEMBOLSO, TIP_CLIENTE, GESTION, CODPROMOT, NOMPROMOT, NOMSUPER, EQUIPO, 
    SUBEQUIPO, FECDESEMBOLSO, DIA, CODDOC, MONTO_APROB, TASA_MENSUAL, CANT_CUOTAS, 
    TIPO_CD, COD_SOLICITUD, NUM_TARJETA, FLAG_CD40, COD_CARGA
)
SELECT 
    A.MESDESEMBOLSO, 
    'DCD' AS TIP_CLIENTE,
    'TLV' AS GESTION,
    A.CODPROMOT,
    A.NOMPROMOT,
    A.NOMSUPER,
    'TLV PRODUCTOS' AS EQUIPO, 
    'COMPRA DE DEUDA' AS SUBEQUIPO,
    A.FECHA_DESEMBOLSO AS FECDESEMBOLSO,
    EXTRACT(DAY FROM A.FECHA_DESEMBOLSO) AS DIA,
    A.CODDOC,
    A.ADQ_MONTOCDSOL AS MONTO_APROB,
    A.TASA_MENSUAL,
    A.CANT_CUOTAS,
    A.TIPO_CD,
    RIGHT(A.ADQ_NROSOL, 8) AS COD_SOLICITUD, 
    A.NUME_TARJETA AS NUM_TARJETA,
    CASE WHEN b_cd40.NE_COD_EXPE IS NOT NULL THEN 'SI' ELSE 'NO' END AS FLAG_CD40,
    b_carga.CA_ANIOMES_CARGA AS COD_CARGA
FROM E_DW_VIEWS_DLAB.V_CD_DESEMB_HISTORICO A
LEFT JOIN (
    SELECT DISTINCT NE_COD_EXPE 
    FROM E_DW_VIEWS.V_RSK_ADQ_BTCH_COMPRA_DEUDA
    WHERE NE_COD_EXPE IN (SELECT RIGHT(ADQ_NROSOL, 8) FROM E_DW_VIEWS_DLAB.V_CD_DESEMB_HISTORICO WHERE MESDESEMBOLSO = :periodo_num)
      AND ND_MONTO > 40000
) b_cd40
  ON RIGHT(A.ADQ_NROSOL, 8) = b_cd40.NE_COD_EXPE
LEFT JOIN (
    SELECT NE_COD_EXPE, CA_ANIOMES_CARGA
    FROM E_DW_VIEWS.V_RSK_ADQ_BTCH_COMPRA_DEUDA
    WHERE NE_COD_EXPE IN (SELECT RIGHT(ADQ_NROSOL, 8) FROM E_DW_VIEWS_DLAB.V_CD_DESEMB_HISTORICO WHERE MESDESEMBOLSO = :periodo_num)
    QUALIFY ROW_NUMBER() OVER(PARTITION BY NE_COD_EXPE ORDER BY CA_ANIOMES_CARGA ASC) = 1
) b_carga
  ON RIGHT(A.ADQ_NROSOL, 8) = b_carga.NE_COD_EXPE
WHERE A.MESDESEMBOLSO = :periodo_num
  AND A.CODPROMOT IN (SELECT REG_EJECUTIVO FROM DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS WHERE SUB_EQUIPO ='CD')
  AND A.TIPONOCOMISION IS NULL
  AND A.FLAG_VALIDO = 'S'
  AND A.IMPOR_INIC_DESEMBOLSO IS NOT NULL;

COLLECT STATISTICS ON DLAB_GEC.M_EXP_VENTAS_CD COLUMN (CODDOC, COD_SOLICITUD);


-- DCO: Convenios
DELETE FROM DLAB_GEC.M_EXP_VENTAS_CON ALL;

INSERT INTO DLAB_GEC.M_EXP_VENTAS_CON (
    MESDESEMBOLSO, TIP_CLIENTE, FECDESEMB, DIA, CODDOC, CODPROMOT, NOMPROMOT, 
    NOMSUPER, MONTO_APROB, TASA, TIPO_VENTA, FAMILIA, PLAZO
)
SELECT 
    PERIODO_VAL AS MESDESEMBOLSO,
    'DCO' AS TIP_CLIENTE,
    DESEMBOLSO_FC AS FECDESEMB,
    EXTRACT(DAY FROM DESEMBOLSO_FC) AS DIA,
    DOCUMENTO_NUM AS CODDOC,
    REGISTRO_CD AS CODPROMOT, 
    REGISTRO_NM AS NOMPROMOT,
    B.NOM_SUPERVISOR AS NOMSUPER,
    DESEMBOLSO_AMT AS MONTO_APROB,
    TASA_RT AS TASA, 
    TIPO_VENTA1_DSC AS TIPO_VENTA, 
    FAMILIA_DSC AS FAMILIA, 
    CUOTAS_NUM AS PLAZO
FROM E_DW_VIEWS.V_FCT_CNV_VENTAS A
LEFT JOIN DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS B
  ON A.REGISTRO_CD = B.REG_EJECUTIVO
WHERE A.REGISTRO_CD IN (SELECT REG_EJECUTIVO FROM DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS WHERE SUB_EQUIPO='CONV_TLV')
  AND A.PERIODO_VAL = :periodo;

COLLECT STATISTICS ON DLAB_GEC.M_EXP_VENTAS_CON COLUMN (CODDOC);


-- DUPG: Upgrade
DELETE FROM DLAB_GEC.M_EXP_VENTAS_UPG ALL;

INSERT INTO DLAB_GEC.M_EXP_VENTAS_UPG (
    MESDESEMBOLSO, TIP_CLIENTE, GESTION, CODPROMOT, NOMPROMOT, NOMSUPER, EQUIPO, 
    SUBEQUIPO, FECDESEMBOLSO, DIA, CODDOC, MONTO_APROB
)
SELECT
    PERIODO_VAL AS MESDESEMBOLSO, 
    'DUPG' AS TIP_CLIENTE,
    'TLV' AS GESTION,
    PROMOTOR_CD AS CODPROMOT,
    PROMOTOR_DSC AS NOMPROMOT,
    SUPERVISOR_DSC AS NOMSUPER,
    'GESTION PORTAFOLIO' AS EQUIPO, 
    'LEALTAD' AS SUBEQUIPO,
    FECHA_FC AS FECDESEMBOLSO,
    EXTRACT(DAY FROM FECHA_FC) AS DIA,
    DOCUMENTO_NUM AS CODDOC,
    0 AS MONTO_APROB
FROM E_DW_VIEWS_DLAB.CGR_UPGRADE_HST
WHERE PERIODO_VAL = :periodo_num
  AND PROMOTOR_CD IN (SELECT REG_EJECUTIVO FROM DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS WHERE SUB_EQUIPO ='PRT')
  AND ESTADO_CD = 'PF' 
  AND BENEFICIARIO_DSC NOT IN ('ADICIONAL');

COLLECT STATISTICS ON DLAB_GEC.M_EXP_VENTAS_UPG COLUMN (CODDOC);


-- DIL: Incremento de Línea
DELETE FROM DLAB_GEC.M_EXP_VENTAS_IL ALL;

INSERT INTO DLAB_GEC.M_EXP_VENTAS_IL (
    MESDESEMBOLSO, TIP_CLIENTE, GESTION, CODPROMOT, NOMPROMOT, NOMSUPER, EQUIPO, 
    SUBEQUIPO, FECDESEMBOLSO, DIA, CODDOC, MONTO_APROB
)
SELECT 
    PERIODO_VAL AS MESDESEMBOLSO, 
    'DIL' AS TIP_CLIENTE,
    'TLV' AS GESTION,
    PROMOTOR_CD AS CODPROMOT,
    PROMOTOR_NM AS NOMPROMOT,
    SUPERVISOR_NM AS NOMSUPER,
    'GESTION PORTAFOLIO' AS EQUIPO, 
    'LEALTAD' AS SUBEQUIPO,
    FECHA_FC AS FECDESEMBOLSO,
    EXTRACT(DAY FROM FECHA_FC) AS DIA,
    DOCUMENTO_NUM AS CODDOC,
    LINEAACTUAL_AMT AS MONTO_APROB
FROM E_DW_VIEWS_DLAB.CGR_INC_LINEA_HST
WHERE PERIODO_VAL = :periodo_num
  AND VALIDO = '1' 
  AND PROMOTOR_CD IN (SELECT REG_EJECUTIVO FROM DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS WHERE SUB_EQUIPO='PRT');

COLLECT STATISTICS ON DLAB_GEC.M_EXP_VENTAS_IL COLUMN (CODDOC);


-- PA: Pago Automático
DELETE FROM DLAB_GEC.M_EXP_VENTAS_PA ALL;

INSERT INTO DLAB_GEC.M_EXP_VENTAS_PA (
    MESDESEMBOLSO, TIP_CLIENTE, GESTION, CODPROMOT, NOMPROMOT, NOMSUPER, EQUIPO, 
    SUBEQUIPO, FECDESEMBOLSO, DIA, CODDOC, MONTO_APROB, FECINGRESO
)
SELECT 
    A.PERIODO_VAL AS MESDESEMBOLSO,
    'PA' AS TIP_CLIENTE,
    'TLV' AS GESTION, 
    A.PROMOTOR_CD AS CODPROMOT, 
    B.NOM_EJECUTIVO AS NOMPROMOT,
    B.NOM_SUPERVISOR AS NOMSUPER,
    'GESTION PORTAFOLIO' AS EQUIPO, 
    'LEALTAD' AS SUBEQUIPO,
    SUBSTRING(A.SOLICITUD_FC FROM 1 FOR 4) || SUBSTRING(A.SOLICITUD_FC FROM 6 FOR 2) || SUBSTRING(A.SOLICITUD_FC FROM 9 FOR 2) AS FECDESEMBOLSO,
    SUBSTRING(A.SOLICITUD_FC FROM 9 FOR 2) AS DIA,
    A.DOCUMENTO_NUM AS CODDOC,
    0 AS MONTO_APROB,
    A.SOLICITUD_FC AS FECINGRESO
FROM E_DW_VIEWS_DLAB.V_CGR_PAGO_AUTOMATICO A
LEFT JOIN DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS B
  ON A.PROMOTOR_CD = B.REG_EJECUTIVO
WHERE A.PERIODO_VAL = :periodo_prev
  AND A.SOLICITUD_PERIODO_VAL = :periodo
  AND A.ESTADO_CD = 'A'
  AND A.RUBRO_CD <> '22'
  AND A.PROMOTOR_CD IN (SELECT REG_EJECUTIVO FROM DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS WHERE SUB_EQUIPO = 'PRT');

COLLECT STATISTICS ON DLAB_GEC.M_EXP_VENTAS_PA COLUMN (CODDOC);


-- SEG: Seguros
DELETE FROM DLAB_GEC.M_EXP_VENTAS_SEG ALL;

INSERT INTO DLAB_GEC.M_EXP_VENTAS_SEG (
    MESDESEMBOLSO, TIP_CLIENTE, GESTION, CODPROMOT, NOMPROMOT, NOMSUPER, EQUIPO, 
    SUBEQUIPO, FECDESEMBOLSO, DIA, CODDOC, MONTO_APROB, FECINGRESO
)
SELECT 
    A.MESVENTA AS MESDESEMBOLSO,
    'SEG' AS TIP_CLIENTE,
    CASE A.PRODUCTO 
        WHEN 'IBK - SEGURO PROTECCION DE TARJETAS 360' THEN 'STC'
        WHEN 'Vive Salud' THEN 'SVS'
        WHEN 'IBK - PROGRAMA ONCOLÓGICO' THEN 'SPO'
        ELSE '' 
    END AS GESTION,
    A.CODPROMOT,
    B.NOM_EJECUTIVO AS NOMPROMOT,
    B.NOM_SUPERVISOR AS NOMSUPER,
    'GESTION PORTAFOLIO' AS EQUIPO,
    'LEALTAD' AS SUBEQUIPO,
    SUBSTRING(A.FECVENTA FROM 7 FOR 4) || SUBSTRING(A.FECVENTA FROM 4 FOR 2) || SUBSTRING(A.FECVENTA FROM 1 FOR 2) AS FECDESEMBOLSO,
    SUBSTRING(A.FECVENTA FROM 1 FOR 2) AS DIA,
    A.DNI_TITULAR AS CODDOC,
    0 AS MONTO_APROB,
    A.FECVENTA AS FECINGRESO
FROM E_DW_VIEWS_DLAB.V_DLAB_CGR_SEGUROS_VENTAS A
LEFT JOIN DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS B
  ON A.CODPROMOT = B.REG_EJECUTIVO
WHERE A.MESVENTA = :periodo
  AND A.CODPROMOT IN (SELECT REG_EJECUTIVO FROM DLAB_GEC.M_EXP_TELEVENTAS_EJECUTIVOS WHERE SUB_EQUIPO = 'SEG');

COLLECT STATISTICS ON DLAB_GEC.M_EXP_VENTAS_SEG COLUMN (CODDOC);
