-- =====================================================================
-- 00_SETUP_HOMOLOGACIONES.SQL
-- Script de configuración inicial (se ejecuta una sola vez)
-- Crea y puebla las tablas de homologación permanentes en Teradata.
-- =====================================================================

-- Limpieza previa de tablas y vistas
DROP TABLE DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_GRUPO;
DROP TABLE DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA;
DROP TABLE DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA;
DROP VIEW DLAB_GEC.V_EXP_CALIDAD_NOTA_SA;
DROP VIEW DLAB_GEC.V_EXP_CALIDAD_NOTA_FINAL;
DROP VIEW DLAB_GEC.V_EXP_ERRORES_CALIDAD_HISTORICO;

-- -------------------------------------------------------------
-- 1. Tabla de Homologación de Grupos de Preguntas
-- -------------------------------------------------------------
CREATE MULTISET TABLE DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_GRUPO ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ORIGINAL VARCHAR(255) CHARACTER SET UNICODE NOT CASESPECIFIC,
      TARGET VARCHAR(255) CHARACTER SET UNICODE NOT CASESPECIFIC
     )
PRIMARY INDEX ( ORIGINAL );

-- Inserción de equivalencias para Grupos
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_GRUPO (ORIGINAL, TARGET) VALUES ('Aceptacion', 'ACEPTACION');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_GRUPO (ORIGINAL, TARGET) VALUES ('Gestion Comercial', 'GESTION COMERCIAL');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_GRUPO (ORIGINAL, TARGET) VALUES ('CARACTERÍSTICAS OBLIGATORIAS', 'CARACTERISTICAS OBLIGATORIAS');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_GRUPO (ORIGINAL, TARGET) VALUES ('Caracteristicas Obligatorias', 'CARACTERISTICAS OBLIGATORIAS');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_GRUPO (ORIGINAL, TARGET) VALUES ('IDENTIFICACIÓN POSITIVA', 'IP BASICA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_GRUPO (ORIGINAL, TARGET) VALUES ('IDENTIFICACION POSITIVA', 'IP BASICA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_GRUPO (ORIGINAL, TARGET) VALUES ('IP_BASICA', 'IP BASICA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_GRUPO (ORIGINAL, TARGET) VALUES ('IP_ROBUSTA', 'IP ROBUSTA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_GRUPO (ORIGINAL, TARGET) VALUES ('Levantamiento de Informacion', 'LEVANTAMIENTO DE INFORMACION');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_GRUPO (ORIGINAL, TARGET) VALUES ('Normas Legales', 'NORMAS LEGALES');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_GRUPO (ORIGINAL, TARGET) VALUES ('Perfilamiento - Llamada 1', 'PERFILAMIENTO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_GRUPO (ORIGINAL, TARGET) VALUES ('Perfilamiento (Llamada 1)', 'PERFILAMIENTO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_GRUPO (ORIGINAL, TARGET) VALUES ('Perfilamiento', 'PERFILAMIENTO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_GRUPO (ORIGINAL, TARGET) VALUES ('Protocolo', 'PROTOCOLO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_GRUPO (ORIGINAL, TARGET) VALUES ('PROTOCOLO/PROCESO', 'PROTOCOLO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_GRUPO (ORIGINAL, TARGET) VALUES ('PROTOCOLO_PROCESO', 'PROTOCOLO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_GRUPO (ORIGINAL, TARGET) VALUES ('Registro', 'REGISTRO');


-- -------------------------------------------------------------
-- 2. Tabla de Homologación de Nombres de Preguntas
-- -------------------------------------------------------------
CREATE MULTISET TABLE DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ORIGINAL VARCHAR(255) CHARACTER SET UNICODE NOT CASESPECIFIC,
      TARGET VARCHAR(255) CHARACTER SET UNICODE NOT CASESPECIFIC
     )
PRIMARY INDEX ( ORIGINAL );

-- Inserción de equivalencias para Preguntas (orden alfabético para facilitar mantenimiento)
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('ABONO/CANJEMILLAS', 'ABONO / CANJE MILLAS');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('ACEPTAVISITA_CELULAR', 'ACEPTA VISITA CELULAR');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('ACEPTAVISITA_CORREO', 'ACEPTA VISITA CORREO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('ACEPTAVISITA_FECHA', 'ACEPTA VISITA FECHA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('AFILIACIONPAGOAUTOMATICO', 'AF. DEBITO AUTOMATICO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('AMPLIACION_LINEA', 'AMPLIACION DE LINEA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('AMPLIACIONLINEACONTRATO', 'AMPLIACION LINEA CONTRATO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('APERTURACUENTANEGOCIOS', 'APERTURA CUENTA NEGOCIOS');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('APLICA_NTD_1', 'APLICA NTD 1');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('APLICA_NTD_2', 'APLICA NTD 2');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('APLICA_NTD_3', 'APLICA NTD 3');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('BAJATASATEA', 'BAJA TASA TEA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('BAJATASATEA_CONTRATO', 'B. TASA TEA CONTRATO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('CANTIDAD_NTD', 'CANTIDAD DE NTD');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('CANTIDADDEPENDIENTES', 'CANTIDAD DE DEPENDIENTES');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('CARGOOCUPACION', 'CARGO / OCUPACION');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('CIERRECOMERCIAL', 'CIERRE COMERCIAL');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('CLACONTRATO', 'CLAUSULA CONTRATO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('CLAUCONTRATO', 'CLAUSULA CONTRATO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('CLAVESECRETA', 'CLAVE SECRETA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('CLOUDTIPIFICACION', 'TIPIFICACION CLOUD');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('CLOUDTIPIFICACIONES', 'TIPIFICACION CLOUD');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('CODIGOEMPLEADO', 'CODIGO EMPLEADO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('COLA_CORRECTA', 'COLA CORRECTA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('VENTA_EN_COLA_CORRECTA', 'COLA CORRECTA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('COMISIONMENSUAL', 'COMISION MENSUAL');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('COMPRASWEB_USOEXT', 'COMPRAS WEB USO EXT');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('COMUNICAVENTAJAS', 'COMUNICA VENTAJAS');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('CONSENTIMIENTOINICIAL', 'CONSENTIMIENTO INICIAL');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('CONYUGEDNI', 'DNI CONYUGE');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('CONYUGEFECHANACIMIENTO', 'FEC. NAC. CONYUGE');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('CONYUGENOMBRESAPELLIDOS', 'NOM. APE. CONYUGE');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('COORDINACIONENTREGATC', 'COORDINACION ENTREGA TC');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('COORDINACIONTC_UPG_TCA', 'COORDINACION ENTREGA TC');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('CORREOELECTRONICO', 'CORREO ELECTRONICO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('CORREO', 'CORREO ELECTRONICO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('CORREOREPRESENLEGAL', 'CORREO REPRESENTANTE LEGAL');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('CUENTAAHORROS', 'CUENTA AHORROS');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('AHORROS', 'CUENTA AHORROS');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('CUOTASTRANSITO', 'CUOTAS EN TRANSITO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('DECLARACION6MESES', 'DECLARA 6 ULT. MESES');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('DECLARACIONJURADA', 'DECLARACION JURADA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('SEGDESGRAVAMEN', 'SEG. DE DESGRAVAMEN');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('DESGRAVAMEN', 'SEG. DE DESGRAVAMEN');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('DEVOLUCIONFINSEMANA', 'DEVOLUCION FDS');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('DIRECCIONDOMICILIO', 'DIRECCION DOMICILIO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('DIRECCIONENTREGATC', 'DIRECCION ENTREGA TC');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('DIRECCIONLABORAL', 'DIRECCION LABORAL');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('DIRECCIONNEGOCIO', 'DIRECCION NEGOCIO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('DISPOSICIONEFECTIVO', 'DISPOSICION EFECTIVO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('DNIREPRESENLEGALACCIONISTA_PJ', 'DNI REPR. LEGAL / ACCIONISTA PJ');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('DNIREPRESENLEGALACCIONISTA(PJ)', 'DNI REPR. LEGAL / ACCIONISTA PJ');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('DOCUMENTOSCONTRACTUALES', 'DOCUMENTOS CONTRACTUALES');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('EECC_CD40K', 'EECC > 40K');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('ENTREGACORRESPONDENCIA', 'ENTREGA CORRESPONDENCIA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('ENVIOEECC', 'ENVIO EECC');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('ESTADOCIVIL', 'ESTADO CIVIL');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('FECHAEMISION', 'FECHA EMISION DNI');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('FECHAEMISIONDNI', 'FECHA EMISION DNI');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('FECHAINGRESO', 'FECHA INGRESO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('FECHANACIMIENTO', 'FECHA NACIMIENTO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('FECHAPAGO', 'FECHA DE PAGO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('FECHAPAGOTC', 'FECHA DE PAGO TC');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('FECHAULTIMOABONO', 'FECHA ULTIMO ABONO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('FIRMACONYUGE', 'FIRMA CONYUGE');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('FIRMADOCUMENTOS', 'FIRMA DOCUMENTOS');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('FOTOSELFIE', 'VIDEOLLAMADA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('GENESYSCLOUD', 'GENESYS CLOUD');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('GIRONEGOCIO', 'GIRO NEGOCIO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('IL_CONTRATO', 'CONTRATO - IL');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('IMPORTEACANCELAR', 'IMPORTE A CANCELAR');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('IMPORTE', 'IMPORTE A CANCELAR');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('IMPORTEAFINANCIAR', 'IMPORTE A FINANCIAR');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('MONTOFINANCIAR', 'IMPORTE A FINANCIAR');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('IMPORTEFINANCIAR', 'IMPORTE A FINANCIAR');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('IMPORTECUOTACREDITO', 'CUOTA CREDITO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('IMPORTEOFERTA', 'IMPORTE OFERTA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('INGRESOINSTITUCION', 'INGRESO INSTITUCION');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('INTERESMORATORIO', 'INTERES MORATORIO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('IP_BASICA', 'IP BASICA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('IPWEB', 'IP_WEB');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('LABORALDIRECCION', 'DIRECCION LABORAL');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('LABORALTELEFONOFIJO', 'TELEFONO LABORAL');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('LLAMADARETENCION', 'LLAMADA DE RETENCION');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('MANEJAOBJECIONES', 'MANEJA OBJECIONES');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('MANEJOOBJECIONES', 'MANEJA OBJECIONES');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('MARCAS_DERIVACION_ONLINE', 'MARCAS DERIVACION ONLINE');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('MICROEMPRESARIOACCIONISTA', 'MICROEMPRESARIO ACCIONISTA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('MOD_NOMBREADICIONAL', 'MODIF. NOMBRE ADICIONAL');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('MOD_OTROPRODUCTO', 'MODIF. OTRO PRODUCTO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('NEGOCIOACTIVO', 'NEGOCIO ACTIVO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('NIVELEDUCACION', 'NIVEL EDUCACION');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('NOMBREADICIONALES', 'NOMBRE DE ADICIONALES');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('NOMBREEMPRESA', 'NOMBRE DE EMPRESA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('NOMBREEMPRESA/RUC', 'NOMBRE EMPRESA / RUC');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('NOMBREMADRE', 'NOMBRE MADRE');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('NOMBREPADRE', 'NOMBRE PADRE');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('NOMBREAPELLIDOS', 'NOMBRES Y APELLIDOS');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('NOMBRESAPELLIDOS', 'NOMBRES Y APELLIDOS');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('NOMBRESREPRESENLEGALACCIONISTA_PJ', 'NOM. REPRESENTANTE LEGAL / ACCIONISTA PJ');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('NOMBRESREPRESENLEGALACCIONISTA/VINCULADOS(PJ)', 'NOM. REPRESENTANTE LEGAL ACCIONISTA / VINCULADOS PJ');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('NORMASLEGALES', 'NORMAS LEGALES');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('NTD_01_CASUISTICA_DETALLE', 'NTD 01 CASUISTICA DETALLE');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('NTD_01_CASUISTICA_GRUPO', 'NTD 01 CASUISTICA GRUPO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('NTD_02_CASUISTICA_DETALLE', 'NTD 02 CASUISTICA DETALLE');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('NTD_02_CASUISTICA_GRUPO', 'NTD 02 CASUISTICA GRUPO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('NTD_03_CASUISTICA_DETALLE', 'NTD 03 CASUISTICA DETALLE');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('NTD_03_CASUISTICA_GRUPO', 'NTD 03 CASUISTICA GRUPO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('NUMEROCELULAR', 'NUMERO CELULAR');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('NUMERORUC', 'NUMERO RUC');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('NUMEVALUACION', 'NUM. EVALUACION');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('NUMLLAMADA', 'NUM. LLAMADA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('ORDENPAGO', 'ORDEN DE PAGO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('OTROSDATOS', 'OTROS DATOS');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('OTROSPRODUCTOSIBK', 'OTROS PRODUCTOS IBK');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('OTROSREPRESENTANTESLEGALESACCIONISTAS_PJ', 'OTROS REPRESENTANTES LEGALES / ACCIONISTAS PJ');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('OTROSREPRESENTANTESLEGALESACCIONISTASVINCULADOS(PJ)', 'OTROS REPRESENTANTES LEGALES ACCIONISTAS / VINCULADOS PJ');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('PA_CELULARSUMINISTRO', 'CELULAR / SUMINISTRO - PA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('PA_CONTRATO', 'CONTRATO - PA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('PA_CORREO', 'CORREO - PA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('PA_IMPORTEMAXIMO', 'IMPORTE MAXIMO - PA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('PA_NOMBREADICIONAL/OTROS_PRODUCTOS', 'NOMBRE ADICIONAL / OTROS PRODUCTOS - PA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('PEDIDO_BAJATASA', 'PEDIDO BAJA TASA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('PEDIDOANULACION', 'PEDIDO ANULACION');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('PREGACEPTACION', 'PREGUNTA ACEPTACION');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('PREGUNTAACEPTACION', 'PREGUNTA ACEPTACION');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('RECIBOHONORARIOS', 'RECIBO POR HONORARIOS');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('RECIBOSHONORARIOS', 'RECIBO POR HONORARIOS');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('REGISTRACXC', 'REGISTRA CXC');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('REGISTRATC', 'REGISTRA TC');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('REINCIDENCIA_NTD_1', 'REINCIDENCIA NTD 1');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('REINCIDENCIA_NTD_2', 'REINCIDENCIA NTD 2');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('REINCIDENCIA_NTD_3', 'REINCIDENCIA NTD 3');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('REPORTA_ALERTA', 'REPORTA ALERTA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('RESPUESTA_ALERTA', 'RESPUESTA ALERTA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('REPORTETRIBUTARIO', 'REPORTE TRIBUTARIO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('REPRESENTANTELEGAL_DUENO_PJ', 'REPRESENTANTE LEGAL DUENO PJ');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('RESULTADOLLAMADA', 'RESULTADO LLAMADA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('REVENDEBENEFICIOS', 'REVENDE BENEFICIOS');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('RUC/NORMBREEMPRESA', 'RUC / NORMBRE EMPRESA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('RUCEMPRESA', 'RUC / NORMBRE EMPRESA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('RUCNOMBREEMPRESA', 'RUC / NORMBRE EMPRESA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('SALDOPENDIENTE', 'SALDO PENDIENTE');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('SEG_COBERTURAS/COSTOSYEXCLUSIONES', 'COBERTURAS / COSTOS / EXCLUSIONES - SEG.');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('SEG_CORREOELECTRONICO', 'CORREO ELECTRONICO - SEG.');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('SEG_DESISTIMIENTO', 'DESISTIMIENTO - SEG.');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('SEG_DIRECCION/DEPARTAMENTO/PROVINCIA/DISTRITO', 'DIRECCION / DEP. / PROV. / DIST. - SEG.');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('SEG_EDAD', 'EDAD - SEG.');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('SEG_ESTADOCIVIL', 'ESTADO CIVIL - SEG.');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('SEG_NACIONALIDAD', 'NACIONALIDAD - SEG.');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('SEG_NOMBRESAPELLIDOS', 'NOMBRES APELLIDOS - SEG.');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('SEG_OCUPACION', 'OCUPACION - SEG.');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('SEG_PREGACEPTACION', 'PREG. ACEPTACION - SEG.');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('SEG_PREGAUTORIZACIONENVIOPOLIZA', 'PREG. AUTORIZACION ENVIO POLIZA - SEG.');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('SEG_TELEFONOREFERENCIA ', 'TELEFONO REFERENCIA - SEG.');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('SEGDESGRAVAMEN_PN', 'SEG. DE DESGRAVAMEN P.N.');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('SEGUROTC', 'SEGURO TC CONTRATO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('SEGUROTC_CONTRATO', 'SEGURO TC CONTRATO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('SITUACIONLABORAL', 'SITUACION LABORAL');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('SUELDOPROMEDIO', 'SUELDO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('SUELDO', 'SUELDO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TARJETASOTRASENTIDADES', 'TARJETAS OTRAS ENTIDADES');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TCA_CELULAR', 'CELULAR - TCA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TCA_CONTRATO', 'CONTRATO - TCA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TCA_CORREO', 'CORREO - TCA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TCA_DIRECCION', 'DIRECCION - TCA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TCA_DNI', 'DNI - TCA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TCA_FECHANACIMIENTO', 'FECHA NACIMIENTO - TCA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TCA_NOMBRESAPELLIDOS', 'NOMBRES APELLIDOS - TCA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TCA_PORCENTAJELINEA', 'PORCENTAJE LINEA - TCA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TCACCESS', 'TC ACCESS');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TCCOMPRADEUDA', 'TC COMPRAR DEUDA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TCCOMPRARDEUDA', 'TC COMPRAR DEUDA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TCEA_PN', 'TCEA P.N.');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TEA/TCEA_CD', 'TEA / TCEA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TEA/TCEA', 'TEA / TCEA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TELEFONO_SIEBEL_MAYOR_30_DIAS', 'SIEBEL > 30D');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TEL_SIEBEL_30D', 'SIEBEL > 30D');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TELEFFIJO', 'TELEFONO FIJO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TELEFONOFIJO', 'TELEFONO FIJO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TELFFIJO', 'TELEFONO FIJO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TELEFONOFIJOCASA', 'TELEFONO FIJO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TELEFFIJOLABORAL', 'TELEFONO FIJO LABORAL');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TELFFIJOLABORAL', 'TELEFONO FIJO LABORAL');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TELEFONO(CELULAR/FIJO)', 'TELEFONO (CELULAR/FIJO)');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TIEMPORESIDENCIA', 'TIEMPO DE RESIDENCIA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TIPO_REVISION', 'TIPO REVISION');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TIPO_DE_REVISION', 'TIPO REVISION');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TIPO_REVISIN', 'TIPO REVISION');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TIPO_IP', 'TIPO IP');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TIPO_MARCACION', 'TIPO MARCACION');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TIPO_REPORTE', 'TIPO REPORTE');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TIPOEVALUACION', 'TIPO EVALUACION');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TIPOLEAD', 'TIPO LEAD');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TIPOVIVIENDA', 'TIPO DE VIVIENDA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('TRANSFERENCIAMARCA_CONTRATO', 'TRANSF. MARCA CONTRATO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('UNIFICACIONLINEAS_CONTRATO', 'UNIFICACION LINEAS CONTRATO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('UPG_CONTRATO', 'CONTRATO - UPG');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('UPG_COORDINACIONTC/TCA_COORDINACIONTC', 'COORDINACION TC - UPG/TCA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('USOHERRAMIENTARET', 'USO HERRAMIENTA RETENCION');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('VENTASTOTALES', 'VENTAS TOTALES');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('COORDINACIONTIENDADESEMBOLSO', 'COORDINACION TDA DESEMBOLSO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('VINCULADOS_SENTINEL', 'VINCULADOS SENTINEL');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_PREGUNTA (ORIGINAL, TARGET) VALUES ('VINCULADOSSENTINEL', 'VINCULADOS SENTINEL');


-- -------------------------------------------------------------
-- 3. Tabla de Homologación de Respuestas
-- -------------------------------------------------------------
CREATE MULTISET TABLE DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ORIGINAL VARCHAR(255) CHARACTER SET UNICODE NOT CASESPECIFIC,
      TARGET VARCHAR(255) CHARACTER SET UNICODE NOT CASESPECIFIC
     )
PRIMARY INDEX ( ORIGINAL );

-- Inserción de equivalencias para Respuestas
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('AceptaCampana', 'ACEPTA CAMPAA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('AceptaCampaa', 'ACEPTA CAMPAA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('Auditoria_Calidad', 'EVALUACION CALIDAD');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('Auditoria_de_Calidad', 'EVALUACION CALIDAD');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('Calidad (Eval/Aud)', 'EVALUACION CALIDAD');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('Auditoria_Prev_Fraude', 'AUDITORIA PREV. FRAUDE');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('Auditoria_Prevencion_de_Fraude', 'AUDITORIA PREV. FRAUDE');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('BASE_RET', 'BASE RETENCION');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('Base Digital - RENIEC', 'BASE DIGITAL - RENIEC');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('Calidad (Eval/Aud)', 'CALIDAD (EVAL/AUDITORIA)');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('Cierre', 'CIERRE');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('Deriva BT - IP WEB', 'DERIVA BT - IP WEB');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('Deriva BT - IVR', 'DERIVA BT - IVR');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('DesisteAnulacion', 'DESISTE ANULACIN');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('Digital', 'DIGITAL');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('Digital - Fide', 'DIGITAL FIDE');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('Ecosistemas', 'ECOSISTEMAS');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('Digital - Puros', 'DIGITAL PUROS');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('In', 'IN');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('KRI_TLF_NO_VALIDADO', 'KRI TLF NO VALIDADO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('KRI_VTA_SIN_AUDIO', 'KRI VTA SIN AUDIO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('Manual - Deriva BT', 'MANUAL - DERIVA BT');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('Manual - Lead Discado', 'MANUAL - LEAD DISCADO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('No', 'NO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('NO_FRAUDE', 'NO FRAUDE');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('NoDesisteAnulacion', 'ANULA');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('Out', 'OUT');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('Predictivo Tradicional', 'PREDICTIVO TRADICIONAL');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('PreAprobado', 'PRE APROBADO');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('Reclamos', 'RECLAMOS');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('Si', 'SI');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('S', 'SI');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('Tradicional', 'TRADICIONAL');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('VENTAS_BPE_B', 'VENTAS BPE B');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('VENTAS_SELECT_PP', 'VENTAS SELECT PP');
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_HOMOLOGA_RESPUESTA (ORIGINAL, TARGET) VALUES ('VENTAS_SELECT_EC', 'VENTAS SELECT EC');


-- -------------------------------------------------------------
-- 4. Definición de Vistas Permanentes
-- -------------------------------------------------------------

-- Vista de Notas de Speech Analytics
REPLACE VIEW DLAB_GEC.V_EXP_CALIDAD_NOTA_SA AS (
    SELECT *
    FROM   DLAB_GEC.M_EXP_CALIDAD_DETALLE_SPEECH_ANALYTICS
);

-- Vista de Notas Finales Consolidadas
REPLACE VIEW DLAB_GEC.V_EXP_CALIDAD_NOTA_FINAL AS (
    SELECT * 
    FROM DLAB_GEC.M_EXP_CALIDAD_NOTA_FINAL
);

-- Vista Histórica de Errores de Calidad
REPLACE VIEW DLAB_GEC.V_EXP_ERRORES_CALIDAD_HISTORICO AS (
    SELECT
        CODIGO,
        PERIODO,
        FECHA_CREADO,
        REG_EJECUTIVO,
        CONID,
        GRUPO_PREGUNTAS,
        PREGUNTA,
        RESPUESTA,
        PREG_VALIDA,
        PREG_CRITICA,
        ES_ERROR,
        COMENTARIO,
        FECHA_CARGA
    FROM DLAB_GEC.M_EXP_HIST_ERRORES_CALIDAD
    WHERE RESPUESTA IN ('INCOMPLETO', 'INCORRECTO', 'INDUCE', 'NO', 'NO INFORMA', 'NO REGISTRA', 'DIFIERE')
);

