-- =====================================================================
-- 02_SA_MARCACION_VENTAS_LPDP.SQL
-- Script SQL refactorizado aplicando las mejores prácticas de rendimiento en Teradata:
-- 1. Sin sentencias UPDATE secuenciales.
-- 2. Uso intensivo de tablas volátiles (en Spool Space, sin consumir Perm Space).
-- 3. Deduplicación de registros usando ROW_NUMBER() OVER en sentencias SELECT.
-- 4. Sentencias JOIN y CASE WHEN unificadas para el marcado de ventas y LPDP.
-- 5. Carga final usando DELETE ALL e INSERT.
-- =====================================================================

-- -------------------------------------------------------------
-- PASO 1: LIMPIEZA DE NÚMEROS TELEFÓNICOS (Tabla Volátil VT_SA_CLEANED)
-- -------------------------------------------------------------
CREATE VOLATILE TABLE VT_SA_CLEANED AS (
    SELECT
        s.*,
        TRIM(BOTH ' ' FROM SUBSTR(CASE WHEN CHARACTER_LENGTH(s.TELEF_IN) > 19 THEN s.TELEF_OUT ELSE s.TELEF_IN END, 8)) AS TELEF_IN_CLEANED
    FROM DLAB_GEC.M_EXP_CALIDAD_DATA_SPEECH_ANALYTICS s
) WITH DATA PRIMARY INDEX (CONID) ON COMMIT PRESERVE ROWS;


-- -------------------------------------------------------------
-- PASO 2: DEDUPLICACIÓN DE CAMPAÑAS (Tablas Volátiles)
-- -------------------------------------------------------------

-- Deduplicación de TC (Período 1 y 2)
CREATE VOLATILE TABLE VT_TC_DEDUP AS (
    SELECT CODDOC, CODPROMOT, DIA,
           CASE WHEN DIA BETWEEN {corte_dia_inicio_1} AND {corte_dia_fin_1} THEN 1 ELSE 2 END AS PeriodType
    FROM (
        SELECT CODDOC, CODPROMOT, DIA,
               ROW_NUMBER() OVER (PARTITION BY CODDOC, (CASE WHEN DIA BETWEEN {corte_dia_inicio_1} AND {corte_dia_fin_1} THEN 1 ELSE 2 END) ORDER BY CODDOC ASC) AS rn
        FROM DLAB_GEC.M_EXP_VENTAS_TC
        WHERE DIA BETWEEN {corte_dia_inicio_1} AND {corte_dia_fin_2}
    ) AS t
    WHERE rn = 1
) WITH DATA PRIMARY INDEX (CODDOC) ON COMMIT PRESERVE ROWS;

-- Deduplicación de PP (Período 1 y 2)
CREATE VOLATILE TABLE VT_PP_DEDUP AS (
    SELECT CODDOC, CODPROMOT, DIA,
           CASE WHEN DIA BETWEEN {corte_dia_inicio_1} AND {corte_dia_fin_1} THEN 1 ELSE 2 END AS PeriodType
    FROM (
        SELECT CODDOC, CODPROMOT, DIA,
               ROW_NUMBER() OVER (PARTITION BY CODDOC, (CASE WHEN DIA BETWEEN {corte_dia_inicio_1} AND {corte_dia_fin_1} THEN 1 ELSE 2 END) ORDER BY CODDOC ASC) AS rn
        FROM DLAB_GEC.M_EXP_VENTAS_PP
        WHERE DIA BETWEEN {corte_dia_inicio_1} AND {corte_dia_fin_2}
    ) AS t
    WHERE rn = 1
) WITH DATA PRIMARY INDEX (CODDOC) ON COMMIT PRESERVE ROWS;

-- Deduplicación de CON (Período 1 y 2)
CREATE VOLATILE TABLE VT_CON_DEDUP AS (
    SELECT CODDOC, CODPROMOT, DIA,
           CASE WHEN DIA BETWEEN {corte_dia_inicio_1} AND {corte_dia_fin_1} THEN 1 ELSE 2 END AS PeriodType
    FROM (
        SELECT CODDOC, CODPROMOT, DIA,
               ROW_NUMBER() OVER (PARTITION BY CODDOC, (CASE WHEN DIA BETWEEN {corte_dia_inicio_1} AND {corte_dia_fin_1} THEN 1 ELSE 2 END) ORDER BY CODDOC ASC) AS rn
        FROM DLAB_GEC.M_EXP_VENTAS_CON
        WHERE DIA BETWEEN {corte_dia_inicio_1} AND {corte_dia_fin_2}
    ) AS t
    WHERE rn = 1
) WITH DATA PRIMARY INDEX (CODDOC) ON COMMIT PRESERVE ROWS;

-- Deduplicación de BNB (BPE Market - Período 1 y 2)
CREATE VOLATILE TABLE VT_BN_DEDUP AS (
    SELECT CODDOC, REGISTRO, FECHA_DESEMBOLSADO,
           CASE WHEN EXTRACT(DAY FROM FECHA_DESEMBOLSADO) BETWEEN {corte_dia_inicio_1} AND {corte_dia_fin_1} THEN 1 ELSE 2 END AS PeriodType
    FROM (
        SELECT CODDOC, REGISTRO, FECHA_DESEMBOLSADO,
               ROW_NUMBER() OVER (PARTITION BY CODDOC, (CASE WHEN EXTRACT(DAY FROM FECHA_DESEMBOLSADO) BETWEEN {corte_dia_inicio_1} AND {corte_dia_fin_1} THEN 1 ELSE 2 END) ORDER BY CODDOC ASC) AS rn
        FROM DLAB_GEC.T_VENTAS_BPE_MARKET
        WHERE EXTRACT(DAY FROM FECHA_DESEMBOLSADO) BETWEEN {corte_dia_inicio_1} AND {corte_dia_fin_2}
    ) AS t
    WHERE rn = 1
) WITH DATA PRIMARY INDEX (CODDOC) ON COMMIT PRESERVE ROWS;

-- Deduplicación de BNC
CREATE VOLATILE TABLE VT_BNC_DEDUP AS (
    SELECT NUM_DOCUMENTO, REGISTRO
    FROM (
        SELECT NUM_DOCUMENTO, REG_EJECUTIVO AS REGISTRO,
               ROW_NUMBER() OVER (PARTITION BY NUM_DOCUMENTO ORDER BY NUM_DOCUMENTO ASC) AS rn
        FROM DLAB_GEC.V_GESTION_BNC
        WHERE EXTRACT(DAY FROM FEC_LLAMADA) BETWEEN 1 AND 31
    ) AS t
    WHERE rn = 1
) WITH DATA PRIMARY INDEX (NUM_DOCUMENTO) ON COMMIT PRESERVE ROWS;

-- Deduplicación de EC
CREATE VOLATILE TABLE VT_EC_DEDUP AS (
    SELECT CODDOC, CODPROMOT
    FROM (
        SELECT CODDOC, CODPROMOT,
               ROW_NUMBER() OVER (PARTITION BY CODDOC ORDER BY CODDOC ASC) AS rn
        FROM DLAB_GEC.M_EXP_VENTAS_EC
        WHERE DIA BETWEEN 1 AND 31
    ) AS t
    WHERE rn = 1
) WITH DATA PRIMARY INDEX (CODDOC) ON COMMIT PRESERVE ROWS;

-- Deduplicación de CHIP (Filtro dinámico de período)
CREATE VOLATILE TABLE VT_CHIP_DEDUP AS (
    SELECT NUM_DOCUMENTO, REG_EJECUTIVO
    FROM (
        SELECT NUM_DOCUMENTO, REG_EJECUTIVO,
               ROW_NUMBER() OVER (PARTITION BY NUM_DOCUMENTO ORDER BY NUM_DOCUMENTO ASC) AS rn
        FROM DLAB_GEC.V_GESTION_CHIP
        WHERE COD_MES = '{PERIODO}'
    ) AS t
    WHERE rn = 1
) WITH DATA PRIMARY INDEX (NUM_DOCUMENTO) ON COMMIT PRESERVE ROWS;

-- Deduplicación de CD
CREATE VOLATILE TABLE VT_CD_DEDUP AS (
    SELECT CODDOC, CODPROMOT
    FROM (
        SELECT CODDOC, CODPROMOT,
               ROW_NUMBER() OVER (PARTITION BY CODDOC ORDER BY CODDOC ASC) AS rn
        FROM DLAB_GEC.M_EXP_VENTAS_CD
        WHERE DIA BETWEEN 1 AND 31
    ) AS t
    WHERE rn = 1
) WITH DATA PRIMARY INDEX (CODDOC) ON COMMIT PRESERVE ROWS;

-- Deduplicación de RTC
CREATE VOLATILE TABLE VT_RTC_DEDUP AS (
    SELECT NUM_DOCUMENTO, REG_ASESOR_RET
    FROM (
        SELECT NUM_DOCUMENTO, REG_ASESOR_RET,
               ROW_NUMBER() OVER (PARTITION BY NUM_DOCUMENTO ORDER BY NUM_DOCUMENTO ASC) AS rn
        FROM DLAB_GEC.T_RETENCION_BASE_CALIDAD_GIRU
        WHERE EXTRACT(DAY FROM FECHA_ALTA) BETWEEN 1 AND 31
    ) AS t
    WHERE rn = 1
) WITH DATA PRIMARY INDEX (NUM_DOCUMENTO) ON COMMIT PRESERVE ROWS;

-- Deduplicación de RCO
CREATE VOLATILE TABLE VT_RCO_DEDUP AS (
    SELECT NRO_DOCUMENTO, PRIMER_REGISTRO
    FROM (
        SELECT NRO_DOCUMENTO, PRIMER_REGISTRO,
               ROW_NUMBER() OVER (PARTITION BY NRO_DOCUMENTO ORDER BY NRO_DOCUMENTO ASC) AS rn
        FROM E_DW_VIEWS_DLAB.V_CNV_VISTA_RETENCION_BT
        WHERE EXTRACT(DAY FROM FECHA) BETWEEN 1 AND 31
    ) AS t
    WHERE rn = 1
) WITH DATA PRIMARY INDEX (NRO_DOCUMENTO) ON COMMIT PRESERVE ROWS;

-- Deduplicación de PRT (IL, TCA, UPG, PA)
CREATE VOLATILE TABLE VT_PRT_IL_DEDUP AS (
    SELECT CODDOC, CODPROMOT
    FROM (
        SELECT CODDOC, CODPROMOT,
               ROW_NUMBER() OVER (PARTITION BY CODDOC ORDER BY CODDOC ASC) AS rn
        FROM DLAB_GEC.M_EXP_VENTAS_IL
        WHERE DIA BETWEEN 1 AND 31
    ) AS t
    WHERE rn = 1
) WITH DATA PRIMARY INDEX (CODDOC) ON COMMIT PRESERVE ROWS;

CREATE VOLATILE TABLE VT_PRT_TCA_DEDUP AS (
    SELECT CODDOC, CODPROMOT
    FROM (
        SELECT CODDOC, CODPROMOT,
               ROW_NUMBER() OVER (PARTITION BY CODDOC ORDER BY CODDOC ASC) AS rn
        FROM DLAB_GEC.M_EXP_VENTAS_TCA
        WHERE DIA BETWEEN 1 AND 31
    ) AS t
    WHERE rn = 1
) WITH DATA PRIMARY INDEX (CODDOC) ON COMMIT PRESERVE ROWS;

CREATE VOLATILE TABLE VT_PRT_UPG_DEDUP AS (
    SELECT CODDOC, CODPROMOT
    FROM (
        SELECT CODDOC, CODPROMOT,
               ROW_NUMBER() OVER (PARTITION BY CODDOC ORDER BY CODDOC ASC) AS rn
        FROM DLAB_GEC.M_EXP_VENTAS_UPG
        WHERE DIA BETWEEN 1 AND 31
    ) AS t
    WHERE rn = 1
) WITH DATA PRIMARY INDEX (CODDOC) ON COMMIT PRESERVE ROWS;

CREATE VOLATILE TABLE VT_PRT_PA_DEDUP AS (
    SELECT CODDOC, CODPROMOT
    FROM (
        SELECT CODDOC, CODPROMOT,
               ROW_NUMBER() OVER (PARTITION BY CODDOC ORDER BY CODDOC ASC) AS rn
        FROM DLAB_GEC.M_EXP_VENTAS_PA
        WHERE DIA BETWEEN 1 AND 31
    ) AS t
    WHERE rn = 1
) WITH DATA PRIMARY INDEX (CODDOC) ON COMMIT PRESERVE ROWS;

-- Deduplicación de SEG
CREATE VOLATILE TABLE VT_SEG_DEDUP AS (
    SELECT CODDOC, CODPROMOT, DIA,
           CASE WHEN DIA BETWEEN {corte_dia_inicio_1} AND {corte_dia_fin_1} THEN 1 ELSE 2 END AS PeriodType
    FROM (
        SELECT CODDOC, CODPROMOT, DIA,
               ROW_NUMBER() OVER (PARTITION BY CODDOC, (CASE WHEN DIA BETWEEN {corte_dia_inicio_1} AND {corte_dia_fin_1} THEN 1 ELSE 2 END) ORDER BY CODDOC ASC) AS rn
        FROM DLAB_GEC.M_EXP_VENTAS_SEG
        WHERE DIA BETWEEN {corte_dia_inicio_1} AND {corte_dia_fin_2}
    ) AS t
    WHERE rn = 1
) WITH DATA PRIMARY INDEX (CODDOC) ON COMMIT PRESERVE ROWS;


-- -------------------------------------------------------------
-- PASO 3: DEDUPLICACIÓN DE FUENTES LPDP (Tablas Volátiles)
-- -------------------------------------------------------------

CREATE VOLATILE TABLE VT_LPDP_CARGA_ACTUAL AS (
    SELECT NUMERO_DOCUMENTO, TIP_CLIENTE, VARIABLE_26
    FROM (
        SELECT NUMERO_DOCUMENTO, TIP_CLIENTE, VARIABLE_26,
               ROW_NUMBER() OVER (PARTITION BY NUMERO_DOCUMENTO, TIP_CLIENTE ORDER BY NUMERO_DOCUMENTO ASC) AS rn
        FROM DLAB_GEC.TLV_CARGA_ACTUAL
        WHERE (
            (TIP_CLIENTE IN ('C', 'NC', '2DA', 'PP', 'CON') AND VARIABLE_4 IS NULL)
            OR (TIP_CLIENTE IN ('EC', 'BPE') AND VARIABLE_3 IS NULL AND VARIABLE_4 IS NULL)
        )
    ) AS t
    WHERE rn = 1
) WITH DATA PRIMARY INDEX (NUMERO_DOCUMENTO) ON COMMIT PRESERVE ROWS;

CREATE VOLATILE TABLE VT_LPDP_CARGA_ACTUAL_DIGITAL AS (
    SELECT NUMERO_DOCUMENTO, TIP_CLIENTE, VARIABLE_26
    FROM (
        SELECT NUMERO_DOCUMENTO, TIP_CLIENTE, VARIABLE_26,
               ROW_NUMBER() OVER (PARTITION BY NUMERO_DOCUMENTO, TIP_CLIENTE ORDER BY NUMERO_DOCUMENTO ASC) AS rn
        FROM DLAB_GEC.TLV_CARGA_ACTUAL_DIGITAL
        WHERE TIP_CLIENTE IN ('DTC', 'DPP', 'DEC', 'DCO')
          AND VARIABLE_3 IS NULL
          AND VARIABLE_4 IS NULL
    ) AS t
    WHERE rn = 1
) WITH DATA PRIMARY INDEX (NUMERO_DOCUMENTO) ON COMMIT PRESERVE ROWS;


-- -------------------------------------------------------------
-- PASO 4: SELECT ÚNICO CON MÚLTIPLES JOINS (Sin UPDATEs)
-- -------------------------------------------------------------
CREATE VOLATILE TABLE VT_SA_MARKED AS (
    SELECT
        s.CD_TASA_PREFERENCIAL,
        s.CD_CONTRATO,
        s.CD_DOC_CONTRACTUALES,
        s.CD_PLAZO_CUOTA,
        s.CD_TC_COMPRA,
        s.CD_COMUNICA_VENTAJAS,
        s.CD_APERTURA_CUENTA,
        s.CD_SEGURO_DESG,
        s.CD_VISA_ACCESS,
        s.CD_ENDOSO_SEGURO,
        s.CD_TASA_TEA,
        s.CD_CROSS_PA,
        s.CD_MANEJA_OBJECIONES,
        s.CD_CIERRE_COMERCIAL,
        s.CON_APERT_CUENTA,
        s.CON_CONTRATO,
        s.CON_BENEFICIOS,
        s.CON_VENTAJAS_PRODUCTO,
        s.CON_MANEJA_OBJECION,
        s.CON_OFRECIMIENTO,
        s.EC_DOC_POLIZA,
        s.EC_PLAZO_CUOTA,
        s.EC_TASA_TCEA,
        s.EC_CONTRATO,
        s.EC_CONTRATO_SEGURO,
        s.EC_INTERES_MORATORIO,
        s.EC_LINEA_PARALELA,
        s.EC_SEG_OPCIONAL,
        s.LINEA_PARALELA,
        s.EC_MANEJA_OBJECION,
        s.OFF_SEG_OPCIONAL,
        s.PP_AP_CUENTA,
        s.PP_ENDOSO,
        s.PP_MONTO,
        s.PP_SEG_DESG,
        s.PP_TASA_CUOTA,
        s.PP_OFF_SEG,
        s.PP_MANEJA_OBJECION,
        s.IL_CONTRATO,
        s.IL_OFRECIMIENTO,
        s.PA_CONTRATO,
        s.PA_OFRECIMIENTO,
        s.TCA_CONTRATO,
        s.TCA_OFRECIMIENTO,
        s.UPG_CONTRATO,
        s.UPG_OFRECIMIENTO,
        s.RET_COORD_ENTREGA,
        s.RET_EXO_MEMBRESIA,
        s.RET_CON_COMPRA_DEUDA,
        s.RET_CON_EVAL_BOLETA,
        s.RET_CON_RET_POR_AMPLIACION,
        s.RET_CON_DEVOL_CUOTAS,
        s.RET_CON_RET_POR_BTASA,
        s.RET_CON_RET_SOL_CANCELACION,
        s.RET_CON_RET_SOL_CRONOGRAMA,
        s.RET_CON_RET_SOL_DEUDA_TOTAL,
        s.RET_CON_RET_SOL_TASA,
        s.RET_ABONO_MILLAS,
        s.RET_CAMBIO_TC,
        s.RET_DEVOL_COMISIONES,
        s.RET_UNIFICA_LINEAS,
        s."360_BENEFICIOS",
        s."360_CONTRATO",
        s."360_OFRECIMIENTO",
        s.VIVE_BENEFICIOS,
        s.VIVE_OFRECIMIENTO,
        s.VIVE_CONTRATO,
        s.COORD_TC,
        s.MEMBRESIA,
        s.TC_SEG_DESG,
        s.SERV_ASOCIADOS,
        s.OFF_CROSS_TC,
        s.BENEFIT,
        s.COMPRA_PROTEGIDA,
        s.VISA_ACCESS,
        s.SESENTA_MESES,
        s.DISP_EFECTIVO,
        s.CIERRE_COMERCIAL,
        s.MANEJA_OBJECIONES,
        s.SIMULACION,
        s.AGRADECE_ESPERA,
        s.EDUCA_CLIENTE,
        s.CONS_INICIAL_TRANSV,
        s.TCEA,
        s.DESPEDIDA,
        s.SALUDO,
        s.TEA,
        s.BN_MANEJA_OBJECIONES,
        s.PERFILAMIENTO,
        s.LEVANT_INF,
        s.CO_CTA_NEG,
        s.CO_CONT_CAP_TRAB,
        s.CO_CONT_NA_AGIL,
        s.CO_CONT_NA_AGIL_CD,
        s.LPDP,
        s.BNC_IZIPAY_YA,
        s.BNC_IZI_MIGRA,
        s.BNC_IZI_VENTA_NUEVA,
        s.BNC_PAGO_SERVICIO,
        s.BNC_PAGO_SUNAT,
        s.BNC_PAGO_PLANILLAS,
        s.BNC_TRADING,
        s.TELEF_IN_CLEANED AS TELEF_IN,
        s.COLA,
        s.DNI,
        s.REG_EV,
        s.TIPIFICACION,
        s.TELEF_OUT,
        s.FECHA_LLAMADA,
        s.CONID,
        
        -- Marcación de venta priorizada (el orden del CASE resuelve traslapes)
        CASE
            WHEN seg.CODDOC IS NOT NULL AND seg.PeriodType = 2 THEN 'SEG02'
            WHEN seg.CODDOC IS NOT NULL AND seg.PeriodType = 1 THEN 'SEG01'
            WHEN pa.CODDOC IS NOT NULL THEN 'PRT01'
            WHEN upg.CODDOC IS NOT NULL THEN 'PRT01'
            WHEN tca.CODDOC IS NOT NULL THEN 'PRT01'
            WHEN il.CODDOC IS NOT NULL THEN 'PRT01'
            WHEN rco.NRO_DOCUMENTO IS NOT NULL THEN 'RCO01'
            WHEN rtc.NUM_DOCUMENTO IS NOT NULL THEN 'RTC01'
            WHEN cd_d.CODDOC IS NOT NULL THEN 'CD01'
            WHEN chip.NUM_DOCUMENTO IS NOT NULL THEN 'CHIP01'
            WHEN ec.CODDOC IS NOT NULL THEN 'EC01'
            WHEN bnc.NUM_DOCUMENTO IS NOT NULL THEN 'BNC01'
            WHEN bn.CODDOC IS NOT NULL AND bn.PeriodType = 2 THEN 'BNB02'
            WHEN bn.CODDOC IS NOT NULL AND bn.PeriodType = 1 THEN 'BNB01'
            WHEN con.CODDOC IS NOT NULL AND con.PeriodType = 2 THEN 'CON02'
            WHEN con.CODDOC IS NOT NULL AND con.PeriodType = 1 THEN 'CON01'
            WHEN pp.CODDOC IS NOT NULL AND pp.PeriodType = 2 THEN 'PP02'
            WHEN pp.CODDOC IS NOT NULL AND pp.PeriodType = 1 THEN 'PP01'
            WHEN tc.CODDOC IS NOT NULL AND tc.PeriodType = 2 THEN 'TC02'
            WHEN tc.CODDOC IS NOT NULL AND tc.PeriodType = 1 THEN 'TC01'
        END AS VENTA,
        
        -- Asignación de número de evaluación
        CASE
            WHEN seg.CODDOC IS NOT NULL AND seg.PeriodType = 2 THEN 2
            WHEN seg.CODDOC IS NOT NULL AND seg.PeriodType = 1 THEN 1
            WHEN pa.CODDOC IS NOT NULL THEN 1
            WHEN upg.CODDOC IS NOT NULL THEN 1
            WHEN tca.CODDOC IS NOT NULL THEN 1
            WHEN il.CODDOC IS NOT NULL THEN 1
            WHEN rco.NRO_DOCUMENTO IS NOT NULL THEN 1
            WHEN rtc.NUM_DOCUMENTO IS NOT NULL THEN 1
            WHEN cd_d.CODDOC IS NOT NULL THEN 1
            WHEN chip.NUM_DOCUMENTO IS NOT NULL THEN 1
            WHEN ec.CODDOC IS NOT NULL THEN 1
            WHEN bnc.NUM_DOCUMENTO IS NOT NULL THEN 1
            WHEN bn.CODDOC IS NOT NULL AND bn.PeriodType = 2 THEN 2
            WHEN bn.CODDOC IS NOT NULL AND bn.PeriodType = 1 THEN 1
            WHEN con.CODDOC IS NOT NULL AND con.PeriodType = 2 THEN 2
            WHEN con.CODDOC IS NOT NULL AND con.PeriodType = 1 THEN 1
            WHEN pp.CODDOC IS NOT NULL AND pp.PeriodType = 2 THEN 2
            WHEN pp.CODDOC IS NOT NULL AND pp.PeriodType = 1 THEN 1
            WHEN tc.CODDOC IS NOT NULL AND tc.PeriodType = 2 THEN 2
            WHEN tc.CODDOC IS NOT NULL AND tc.PeriodType = 1 THEN 1
        END AS NEVALUACION,
        
        -- Clasificación de FLAG_PRT
        CASE
            WHEN pa.CODDOC IS NOT NULL THEN 'PA'
            WHEN upg.CODDOC IS NOT NULL THEN 'UPG'
            WHEN tca.CODDOC IS NOT NULL THEN 'TCA'
            WHEN il.CODDOC IS NOT NULL THEN 'IL'
        END AS FLAG_PRT,
        
        -- Clasificación de FLAG_LPDP
        CASE
            WHEN (
                -- Validación de consentimiento para TC
                (tc.CODDOC IS NOT NULL AND COALESCE(lpdp_ca_tc.VARIABLE_26, lpdp_cad_tc.VARIABLE_26) = 'S')
                -- Validación de consentimiento para PP
                OR (pp.CODDOC IS NOT NULL AND COALESCE(lpdp_ca_pp.VARIABLE_26, lpdp_cad_pp.VARIABLE_26) = 'S')
                -- Validación de consentimiento para EC
                OR (ec.CODDOC IS NOT NULL AND COALESCE(lpdp_ca_ec.VARIABLE_26, lpdp_cad_ec.VARIABLE_26) = 'S')
                -- Validación de consentimiento para CON
                OR (con.CODDOC IS NOT NULL AND COALESCE(lpdp_ca_con.VARIABLE_26, lpdp_cad_con.VARIABLE_26) = 'S')
                -- Validación de consentimiento para BN
                OR (bn.CODDOC IS NOT NULL AND lpdp_ca_bn.VARIABLE_26 = 'S')
            ) THEN 'TIENE CONSENTIMIENTO INICIAL'
            ELSE 'SOLICITAR CONSENTIMIENTO INICIAL'
        END AS FLAG_LPDP

    FROM VT_SA_CLEANED s
    
    -- Cruce de campañas
    LEFT JOIN VT_TC_DEDUP tc ON s.DNI = tc.CODDOC AND s.REG_EV = tc.CODPROMOT AND s.DNI IS NOT NULL
    LEFT JOIN VT_PP_DEDUP pp ON s.DNI = pp.CODDOC AND s.REG_EV = pp.CODPROMOT AND s.DNI IS NOT NULL
    LEFT JOIN VT_CON_DEDUP con ON s.DNI = con.CODDOC AND s.REG_EV = con.CODPROMOT AND s.DNI IS NOT NULL
    LEFT JOIN VT_BN_DEDUP bn ON s.DNI = bn.CODDOC AND s.REG_EV = bn.REGISTRO AND s.DNI IS NOT NULL
    LEFT JOIN VT_BNC_DEDUP bnc ON s.DNI = bnc.NUM_DOCUMENTO AND s.REG_EV = bnc.REGISTRO AND s.DNI IS NOT NULL
    LEFT JOIN VT_EC_DEDUP ec ON s.DNI = ec.CODDOC AND s.REG_EV = ec.CODPROMOT AND s.DNI IS NOT NULL
    LEFT JOIN VT_CHIP_DEDUP chip ON s.DNI = chip.NUM_DOCUMENTO AND s.REG_EV = chip.REG_EJECUTIVO AND s.DNI IS NOT NULL
    LEFT JOIN VT_CD_DEDUP cd_d ON s.DNI = cd_d.CODDOC AND s.REG_EV = cd_d.CODPROMOT AND s.DNI IS NOT NULL
    LEFT JOIN VT_RTC_DEDUP rtc ON s.DNI = rtc.NUM_DOCUMENTO AND s.REG_EV = rtc.REG_ASESOR_RET AND s.DNI IS NOT NULL
    LEFT JOIN VT_RCO_DEDUP rco ON s.DNI = rco.NRO_DOCUMENTO AND s.REG_EV = rco.PRIMER_REGISTRO AND s.DNI IS NOT NULL
    LEFT JOIN VT_PRT_IL_DEDUP il ON s.DNI = il.CODDOC AND s.REG_EV = il.CODPROMOT AND s.DNI IS NOT NULL
    LEFT JOIN VT_PRT_TCA_DEDUP tca ON s.DNI = tca.CODDOC AND s.REG_EV = tca.CODPROMOT AND s.DNI IS NOT NULL
    LEFT JOIN VT_PRT_UPG_DEDUP upg ON s.DNI = upg.CODDOC AND s.REG_EV = upg.CODPROMOT AND s.DNI IS NOT NULL
    LEFT JOIN VT_PRT_PA_DEDUP pa ON s.DNI = pa.CODDOC AND s.REG_EV = pa.CODPROMOT AND s.DNI IS NOT NULL
    LEFT JOIN VT_SEG_DEDUP seg ON s.DNI = seg.CODDOC AND s.REG_EV = seg.CODPROMOT AND s.DNI IS NOT NULL
    
    -- Cruce de LPDP
    -- TC
    LEFT JOIN VT_LPDP_CARGA_ACTUAL lpdp_ca_tc ON s.DNI = lpdp_ca_tc.NUMERO_DOCUMENTO AND lpdp_ca_tc.TIP_CLIENTE IN ('C', 'NC', '2DA')
    LEFT JOIN VT_LPDP_CARGA_ACTUAL_DIGITAL lpdp_cad_tc ON s.DNI = lpdp_cad_tc.NUMERO_DOCUMENTO AND lpdp_cad_tc.TIP_CLIENTE = 'DTC'
    -- PP
    LEFT JOIN VT_LPDP_CARGA_ACTUAL lpdp_ca_pp ON s.DNI = lpdp_ca_pp.NUMERO_DOCUMENTO AND lpdp_ca_pp.TIP_CLIENTE = 'PP'
    LEFT JOIN VT_LPDP_CARGA_ACTUAL_DIGITAL lpdp_cad_pp ON s.DNI = lpdp_cad_pp.NUMERO_DOCUMENTO AND lpdp_cad_pp.TIP_CLIENTE = 'DPP'
    -- EC
    LEFT JOIN VT_LPDP_CARGA_ACTUAL lpdp_ca_ec ON s.DNI = lpdp_ca_ec.NUMERO_DOCUMENTO AND lpdp_ca_ec.TIP_CLIENTE = 'EC'
    LEFT JOIN VT_LPDP_CARGA_ACTUAL_DIGITAL lpdp_cad_ec ON s.DNI = lpdp_cad_ec.NUMERO_DOCUMENTO AND lpdp_cad_ec.TIP_CLIENTE = 'DEC'
    -- CON
    LEFT JOIN VT_LPDP_CARGA_ACTUAL lpdp_ca_con ON s.DNI = lpdp_ca_con.NUMERO_DOCUMENTO AND lpdp_ca_con.TIP_CLIENTE = 'CON'
    LEFT JOIN VT_LPDP_CARGA_ACTUAL_DIGITAL lpdp_cad_con ON s.DNI = lpdp_cad_con.NUMERO_DOCUMENTO AND lpdp_cad_con.TIP_CLIENTE = 'DCO'
    -- BN
    LEFT JOIN VT_LPDP_CARGA_ACTUAL lpdp_ca_bn ON s.DNI = lpdp_ca_bn.NUMERO_DOCUMENTO AND lpdp_ca_bn.TIP_CLIENTE = 'BPE'
) WITH DATA PRIMARY INDEX (CONID) ON COMMIT PRESERVE ROWS;


-- -------------------------------------------------------------
-- PASO 5: EXCLUSIÓN DE REGISTROS NO MARCADOS
-- -------------------------------------------------------------
CREATE VOLATILE TABLE VT_SA_FINAL AS (
    SELECT * FROM VT_SA_MARKED
    WHERE VENTA IS NOT NULL
) WITH DATA PRIMARY INDEX (CONID) ON COMMIT PRESERVE ROWS;


-- -------------------------------------------------------------
-- PASO 6: VACIADO E INSERCIÓN EN TABLA PRODUCTIVA
-- -------------------------------------------------------------

-- Vaciado rápido de Teradata
DELETE FROM DLAB_GEC.M_EXP_CALIDAD_DATA_SPEECH_ANALYTICS ALL;

-- Carga final
INSERT INTO DLAB_GEC.M_EXP_CALIDAD_DATA_SPEECH_ANALYTICS
(
    CD_TASA_PREFERENCIAL,
    CD_CONTRATO,
    CD_DOC_CONTRACTUALES,
    CD_PLAZO_CUOTA,
    CD_TC_COMPRA,
    CD_COMUNICA_VENTAJAS,
    CD_APERTURA_CUENTA,
    CD_SEGURO_DESG,
    CD_VISA_ACCESS,
    CD_ENDOSO_SEGURO,
    CD_TASA_TEA,
    CD_CROSS_PA,
    CD_MANEJA_OBJECIONES,
    CD_CIERRE_COMERCIAL,
    CON_APERT_CUENTA,
    CON_CONTRATO,
    CON_BENEFICIOS,
    CON_VENTAJAS_PRODUCTO,
    CON_MANEJA_OBJECION,
    CON_OFRECIMIENTO,
    EC_DOC_POLIZA,
    EC_PLAZO_CUOTA,
    EC_TASA_TCEA,
    EC_CONTRATO,
    EC_CONTRATO_SEGURO,
    EC_INTERES_MORATORIO,
    EC_LINEA_PARALELA,
    EC_SEG_OPCIONAL,
    LINEA_PARALELA,
    EC_MANEJA_OBJECION,
    OFF_SEG_OPCIONAL,
    PP_AP_CUENTA,
    PP_ENDOSO,
    PP_MONTO,
    PP_SEG_DESG,
    PP_TASA_CUOTA,
    PP_OFF_SEG,
    PP_MANEJA_OBJECION,
    IL_CONTRATO,
    IL_OFRECIMIENTO,
    PA_CONTRATO,
    PA_OFRECIMIENTO,
    TCA_CONTRATO,
    TCA_OFRECIMIENTO,
    UPG_CONTRATO,
    UPG_OFRECIMIENTO,
    RET_COORD_ENTREGA,
    RET_EXO_MEMBRESIA,
    RET_CON_COMPRA_DEUDA,
    RET_CON_EVAL_BOLETA,
    RET_CON_RET_POR_AMPLIACION,
    RET_CON_DEVOL_CUOTAS,
    RET_CON_RET_POR_BTASA,
    RET_CON_RET_SOL_CANCELACION,
    RET_CON_RET_SOL_CRONOGRAMA,
    RET_CON_RET_SOL_DEUDA_TOTAL,
    RET_CON_RET_SOL_TASA,
    RET_ABONO_MILLAS,
    RET_CAMBIO_TC,
    RET_DEVOL_COMISIONES,
    RET_UNIFICA_LINEAS,
    "360_BENEFICIOS",
    "360_CONTRATO",
    "360_OFRECIMIENTO",
    VIVE_BENEFICIOS,
    VIVE_OFRECIMIENTO,
    VIVE_CONTRATO,
    COORD_TC,
    MEMBRESIA,
    TC_SEG_DESG,
    SERV_ASOCIADOS,
    OFF_CROSS_TC,
    BENEFIT,
    COMPRA_PROTEGIDA,
    VISA_ACCESS,
    SESENTA_MESES,
    DISP_EFECTIVO,
    CIERRE_COMERCIAL,
    MANEJA_OBJECIONES,
    SIMULACION,
    AGRADECE_ESPERA,
    EDUCA_CLIENTE,
    CONS_INICIAL_TRANSV,
    TCEA,
    DESPEDIDA,
    SALUDO,
    TEA,
    BN_MANEJA_OBJECIONES,
    PERFILAMIENTO,
    LEVANT_INF,
    CO_CTA_NEG,
    CO_CONT_CAP_TRAB,
    CO_CONT_NA_AGIL,
    CO_CONT_NA_AGIL_CD,
    LPDP,
    BNC_IZIPAY_YA,
    BNC_IZI_MIGRA,
    BNC_IZI_VENTA_NUEVA,
    BNC_PAGO_SERVICIO,
    BNC_PAGO_SUNAT,
    BNC_PAGO_PLANILLAS,
    BNC_TRADING,
    TELEF_IN,
    COLA,
    DNI,
    REG_EV,
    TIPIFICACION,
    TELEF_OUT,
    FECHA_LLAMADA,
    CONID,
    NEVALUACION,
    VENTA,
    FLAG_PRT,
    FLAG_LPDP
)
SELECT
    CD_TASA_PREFERENCIAL,
    CD_CONTRATO,
    CD_DOC_CONTRACTUALES,
    CD_PLAZO_CUOTA,
    CD_TC_COMPRA,
    CD_COMUNICA_VENTAJAS,
    CD_APERTURA_CUENTA,
    CD_SEGURO_DESG,
    CD_VISA_ACCESS,
    CD_ENDOSO_SEGURO,
    CD_TASA_TEA,
    CD_CROSS_PA,
    CD_MANEJA_OBJECIONES,
    CD_CIERRE_COMERCIAL,
    CON_APERT_CUENTA,
    CON_CONTRATO,
    CON_BENEFICIOS,
    CON_VENTAJAS_PRODUCTO,
    CON_MANEJA_OBJECION,
    CON_OFRECIMIENTO,
    EC_DOC_POLIZA,
    EC_PLAZO_CUOTA,
    EC_TASA_TCEA,
    EC_CONTRATO,
    EC_CONTRATO_SEGURO,
    EC_INTERES_MORATORIO,
    EC_LINEA_PARALELA,
    EC_SEG_OPCIONAL,
    LINEA_PARALELA,
    EC_MANEJA_OBJECION,
    OFF_SEG_OPCIONAL,
    PP_AP_CUENTA,
    PP_ENDOSO,
    PP_MONTO,
    PP_SEG_DESG,
    PP_TASA_CUOTA,
    PP_OFF_SEG,
    PP_MANEJA_OBJECION,
    IL_CONTRATO,
    IL_OFRECIMIENTO,
    PA_CONTRATO,
    PA_OFRECIMIENTO,
    TCA_CONTRATO,
    TCA_OFRECIMIENTO,
    UPG_CONTRATO,
    UPG_OFRECIMIENTO,
    RET_COORD_ENTREGA,
    RET_EXO_MEMBRESIA,
    RET_CON_COMPRA_DEUDA,
    RET_CON_EVAL_BOLETA,
    RET_CON_RET_POR_AMPLIACION,
    RET_CON_DEVOL_CUOTAS,
    RET_CON_RET_POR_BTASA,
    RET_CON_RET_SOL_CANCELACION,
    RET_CON_RET_SOL_CRONOGRAMA,
    RET_CON_RET_SOL_DEUDA_TOTAL,
    RET_CON_RET_SOL_TASA,
    RET_ABONO_MILLAS,
    RET_CAMBIO_TC,
    RET_DEVOL_COMISIONES,
    RET_UNIFICA_LINEAS,
    "360_BENEFICIOS",
    "360_CONTRATO",
    "360_OFRECIMIENTO",
    VIVE_BENEFICIOS,
    VIVE_OFRECIMIENTO,
    VIVE_CONTRATO,
    COORD_TC,
    MEMBRESIA,
    TC_SEG_DESG,
    SERV_ASOCIADOS,
    OFF_CROSS_TC,
    BENEFIT,
    COMPRA_PROTEGIDA,
    VISA_ACCESS,
    SESENTA_MESES,
    DISP_EFECTIVO,
    CIERRE_COMERCIAL,
    MANEJA_OBJECIONES,
    SIMULACION,
    AGRADECE_ESPERA,
    EDUCA_CLIENTE,
    CONS_INICIAL_TRANSV,
    TCEA,
    DESPEDIDA,
    SALUDO,
    TEA,
    BN_MANEJA_OBJECIONES,
    PERFILAMIENTO,
    LEVANT_INF,
    CO_CTA_NEG,
    CO_CONT_CAP_TRAB,
    CO_CONT_NA_AGIL,
    CO_CONT_NA_AGIL_CD,
    LPDP,
    BNC_IZIPAY_YA,
    BNC_IZI_MIGRA,
    BNC_IZI_VENTA_NUEVA,
    BNC_PAGO_SERVICIO,
    BNC_PAGO_SUNAT,
    BNC_PAGO_PLANILLAS,
    BNC_TRADING,
    TELEF_IN,
    COLA,
    DNI,
    REG_EV,
    TIPIFICACION,
    TELEF_OUT,
    FECHA_LLAMADA,
    CONID,
    NEVALUACION,
    VENTA,
    FLAG_PRT,
    FLAG_LPDP
FROM VT_SA_FINAL;
