-- =====================================================================
-- 03_SA_CALCULO_PESOS_UNPIVOT.SQL
-- Agrupa las métricas de Speech Analytics y las convierte de columnas
-- a filas (unpivot) en la tabla volátil VT_EXP_CALIDAD_PESOS_SA.
-- =====================================================================

-- Promedios de detección agrupados en tabla volátil intermedia para evitar CTEs
CREATE VOLATILE TABLE VT_BASE_SPEECH AS (
    SELECT
        '{PERIODO}' AS PERIODO,
        SUBSTRING(VENTA FROM 1 FOR CHAR_LENGTH(VENTA) - 2) AS PRODUCTO,
        REG_EV,
        NEVALUACION,
        
        -- Promedio de detección por categoría (valor entre 0 y 1)
        AVG(CAST(AGRADECE_ESPERA        AS FLOAT)) AS AGRADECE_ESPERA,
        AVG(CAST(BENEFIT                AS FLOAT)) AS BENEFIT,
        AVG(CAST(BN_MANEJA_OBJECIONES   AS FLOAT)) AS BN_MANEJA_OBJECIONES,
        AVG(CAST(PERFILAMIENTO          AS FLOAT)) AS PERFILAMIENTO,
        AVG(CAST(LEVANT_INF             AS FLOAT)) AS LEVANT_INF,
        AVG(CAST(CO_CTA_NEG             AS FLOAT)) AS CO_CTA_NEG,
        AVG(CAST(CO_CONT_CAP_TRAB       AS FLOAT)) AS CO_CONT_CAP_TRAB,
        AVG(CAST(CO_CONT_NA_AGIL        AS FLOAT)) AS CO_CONT_NA_AGIL,
        AVG(CAST(CO_CONT_NA_AGIL_CD     AS FLOAT)) AS CO_CONT_NA_AGIL_CD,
        AVG(CAST(CIERRE_COMERCIAL       AS FLOAT)) AS CIERRE_COMERCIAL,
        AVG(CAST("360_BENEFICIOS"       AS FLOAT)) AS "360_BENEFICIOS",
        AVG(CAST("360_CONTRATO"         AS FLOAT)) AS "360_CONTRATO",
        AVG(CAST("360_OFRECIMIENTO"     AS FLOAT)) AS "360_OFRECIMIENTO",
        AVG(CAST(COMPRA_PROTEGIDA       AS FLOAT)) AS COMPRA_PROTEGIDA,
        AVG(CAST(CON_APERT_CUENTA       AS FLOAT)) AS CON_APERT_CUENTA,
        AVG(CAST(CON_BENEFICIOS         AS FLOAT)) AS CON_BENEFICIOS,
        AVG(CAST(CON_CONTRATO           AS FLOAT)) AS CON_CONTRATO,
        AVG(CAST(CON_MANEJA_OBJECION    AS FLOAT)) AS CON_MANEJA_OBJECION,
        AVG(CAST(CON_OFRECIMIENTO       AS FLOAT)) AS CON_OFRECIMIENTO,
        AVG(CAST(CON_VENTAJAS_PRODUCTO  AS FLOAT)) AS CON_VENTAJAS_PRODUCTO,
        AVG(CAST(CONS_INICIAL_TRANSV    AS FLOAT)) AS CONS_INICIAL_TRANSV,
        AVG(CAST(COORD_TC               AS FLOAT)) AS COORD_TC,
        AVG(CAST(DESPEDIDA              AS FLOAT)) AS DESPEDIDA,
        AVG(CAST(DISP_EFECTIVO          AS FLOAT)) AS DISP_EFECTIVO,
        AVG(CAST(EC_CONTRATO            AS FLOAT)) AS EC_CONTRATO,
        AVG(CAST(EC_CONTRATO_SEGURO     AS FLOAT)) AS EC_CONTRATO_SEGURO,
        AVG(CAST(EC_DOC_POLIZA          AS FLOAT)) AS EC_DOC_POLIZA,
        AVG(CAST(EC_INTERES_MORATORIO   AS FLOAT)) AS EC_INTERES_MORATORIO,
        AVG(CAST(EC_LINEA_PARALELA      AS FLOAT)) AS EC_LINEA_PARALELA,
        AVG(CAST(EC_MANEJA_OBJECION     AS FLOAT)) AS EC_MANEJA_OBJECION,
        AVG(CAST(EC_PLAZO_CUOTA         AS FLOAT)) AS EC_PLAZO_CUOTA,
        AVG(CAST(EC_SEG_OPCIONAL        AS FLOAT)) AS EC_SEG_OPCIONAL,
        AVG(CAST(EC_TASA_TCEA           AS FLOAT)) AS EC_TASA_TCEA,
        AVG(CAST(EDUCA_CLIENTE          AS FLOAT)) AS EDUCA_CLIENTE,
        AVG(CAST(IL_CONTRATO            AS FLOAT)) AS IL_CONTRATO,
        AVG(CAST(IL_OFRECIMIENTO        AS FLOAT)) AS IL_OFRECIMIENTO,
        AVG(CAST(LPDP                   AS FLOAT)) AS LPDP,
        AVG(CAST(LINEA_PARALELA         AS FLOAT)) AS LINEA_PARALELA,
        AVG(CAST(MANEJA_OBJECIONES      AS FLOAT)) AS MANEJA_OBJECIONES,
        AVG(CAST(MEMBRESIA              AS FLOAT)) AS MEMBRESIA,
        AVG(CAST(OFF_CROSS_TC           AS FLOAT)) AS OFF_CROSS_TC,
        AVG(CAST(OFF_SEG_OPCIONAL       AS FLOAT)) AS OFF_SEG_OPCIONAL,
        AVG(CAST(PA_CONTRATO            AS FLOAT)) AS PA_CONTRATO,
        AVG(CAST(PA_OFRECIMIENTO        AS FLOAT)) AS PA_OFRECIMIENTO,
        AVG(CAST(PP_AP_CUENTA           AS FLOAT)) AS PP_AP_CUENTA,
        AVG(CAST(PP_ENDOSO              AS FLOAT)) AS PP_ENDOSO,
        AVG(CAST(PP_MANEJA_OBJECION     AS FLOAT)) AS PP_MANEJA_OBJECION,
        AVG(CAST(PP_MONTO               AS FLOAT)) AS PP_MONTO,
        AVG(CAST(PP_OFF_SEG             AS FLOAT)) AS PP_OFF_SEG,
        AVG(CAST(PP_SEG_DESG            AS FLOAT)) AS PP_SEG_DESG,
        AVG(CAST(PP_TASA_CUOTA          AS FLOAT)) AS PP_TASA_CUOTA,
        AVG(CAST(SALUDO                 AS FLOAT)) AS SALUDO,
        AVG(CAST(SERV_ASOCIADOS         AS FLOAT)) AS SERV_ASOCIADOS,
        AVG(CAST(SESENTA_MESES          AS FLOAT)) AS SESENTA_MESES,
        AVG(CAST(TC_SEG_DESG            AS FLOAT)) AS TC_SEG_DESG,
        AVG(CAST(TCA_CONTRATO           AS FLOAT)) AS TCA_CONTRATO,
        AVG(CAST(TCEA                   AS FLOAT)) AS TCEA,
        AVG(CAST(UPG_OFRECIMIENTO       AS FLOAT)) AS UPG_OFRECIMIENTO,
        AVG(CAST(TCA_OFRECIMIENTO       AS FLOAT)) AS TCA_OFRECIMIENTO,
        AVG(CAST(TEA                    AS FLOAT)) AS TEA,
        AVG(CAST(UPG_CONTRATO           AS FLOAT)) AS UPG_CONTRATO,
        AVG(CAST(VISA_ACCESS            AS FLOAT)) AS VISA_ACCESS,
        AVG(CAST(VIVE_BENEFICIOS        AS FLOAT)) AS VIVE_BENEFICIOS,
        AVG(CAST(VIVE_CONTRATO          AS FLOAT)) AS VIVE_CONTRATO,
        AVG(CAST(VIVE_OFRECIMIENTO      AS FLOAT)) AS VIVE_OFRECIMIENTO,
        AVG(CAST(SIMULACION             AS FLOAT)) AS SIMULACION,
        AVG(CAST(CD_APERTURA_CUENTA     AS FLOAT)) AS CD_APERTURA_CUENTA,
        AVG(CAST(CD_SEGURO_DESG         AS FLOAT)) AS CD_SEGURO_DESG,
        AVG(CAST(CD_VISA_ACCESS         AS FLOAT)) AS CD_VISA_ACCESS,
        AVG(CAST(CD_CONTRATO            AS FLOAT)) AS CD_CONTRATO,
        AVG(CAST(CD_DOC_CONTRACTUALES   AS FLOAT)) AS CD_DOC_CONTRACTUALES,
        AVG(CAST(CD_ENDOSO_SEGURO       AS FLOAT)) AS CD_ENDOSO_SEGURO,
        AVG(CAST(CD_PLAZO_CUOTA         AS FLOAT)) AS CD_PLAZO_CUOTA,
        AVG(CAST(CD_TASA_TEA            AS FLOAT)) AS CD_TASA_TEA,
        AVG(CAST(CD_TC_COMPRA           AS FLOAT)) AS CD_TC_COMPRA,
        AVG(CAST(CD_CROSS_PA            AS FLOAT)) AS CD_CROSS_PA,
        AVG(CAST(CD_MANEJA_OBJECIONES   AS FLOAT)) AS CD_MANEJA_OBJECIONES,
        AVG(CAST(CD_CIERRE_COMERCIAL    AS FLOAT)) AS CD_CIERRE_COMERCIAL,
        AVG(CAST(CD_COMUNICA_VENTAJAS   AS FLOAT)) AS CD_COMUNICA_VENTAJAS,
        AVG(CAST(CD_TASA_PREFERENCIAL   AS FLOAT)) AS CD_TASA_PREFERENCIAL,
        AVG(CAST(RET_COORD_ENTREGA      AS FLOAT)) AS RET_COORD_ENTREGA,
        AVG(CAST(RET_EXO_MEMBRESIA      AS FLOAT)) AS RET_EXO_MEMBRESIA,
        AVG(CAST(RET_ABONO_MILLAS       AS FLOAT)) AS RET_ABONO_MILLAS,
        AVG(CAST(RET_CAMBIO_TC          AS FLOAT)) AS RET_CAMBIO_TC,
        AVG(CAST(RET_DEVOL_COMISIONES   AS FLOAT)) AS RET_DEVOL_COMISIONES,
        AVG(CAST(RET_UNIFICA_LINEAS     AS FLOAT)) AS RET_UNIFICA_LINEAS,
        AVG(CAST(RET_CON_COMPRA_DEUDA   AS FLOAT)) AS RET_CON_COMPRA_DEUDA,
        AVG(CAST(RET_CON_EVAL_BOLETA    AS FLOAT)) AS RET_CON_EVAL_BOLETA,
        AVG(CAST(RET_CON_RET_POR_AMPLIACION  AS FLOAT)) AS RET_CON_RET_POR_AMPLIACION,
        AVG(CAST(RET_CON_DEVOL_CUOTAS        AS FLOAT)) AS RET_CON_DEVOL_CUOTAS,
        AVG(CAST(RET_CON_RET_POR_BTASA       AS FLOAT)) AS RET_CON_RET_POR_BTASA,
        AVG(CAST(RET_CON_RET_SOL_CANCELACION AS FLOAT)) AS RET_CON_RET_SOL_CANCELACION,
        AVG(CAST(RET_CON_RET_SOL_CRONOGRAMA  AS FLOAT)) AS RET_CON_RET_SOL_CRONOGRAMA,
        AVG(CAST(RET_CON_RET_SOL_DEUDA_TOTAL AS FLOAT)) AS RET_CON_RET_SOL_DEUDA_TOTAL,
        AVG(CAST(RET_CON_RET_SOL_TASA        AS FLOAT)) AS RET_CON_RET_SOL_TASA,
        AVG(CAST(BNC_IZIPAY_YA              AS FLOAT)) AS BNC_IZIPAY_YA,
        AVG(CAST(BNC_IZI_MIGRA              AS FLOAT)) AS BNC_IZI_MIGRA,
        AVG(CAST(BNC_IZI_VENTA_NUEVA        AS FLOAT)) AS BNC_IZI_VENTA_NUEVA,
        AVG(CAST(BNC_PAGO_SERVICIO          AS FLOAT)) AS BNC_PAGO_SERVICIO,
        AVG(CAST(BNC_PAGO_SUNAT             AS FLOAT)) AS BNC_PAGO_SUNAT,
        AVG(CAST(BNC_PAGO_PLANILLAS         AS FLOAT)) AS BNC_PAGO_PLANILLAS,
        AVG(CAST(BNC_TRADING                AS FLOAT)) AS BNC_TRADING,
        MAX(FLAG_LPDP) AS FLAG_LPDP
    FROM DLAB_GEC.M_EXP_CALIDAD_DATA_SPEECH_ANALYTICS
    GROUP BY 1,2,3,4
) WITH DATA PRIMARY INDEX (PERIODO, PRODUCTO, REG_EV, NEVALUACION) ON COMMIT PRESERVE ROWS;


-- Estructuración unpivot en la tabla volátil VT_EXP_CALIDAD_PESOS_SA
CREATE VOLATILE TABLE VT_EXP_CALIDAD_PESOS_SA AS (
    SELECT
        PERIODO,
        PRODUCTO,
        REG_EV,
        CATEGORIA,
        IND AS OBTENIDO,
        NEVALUACION,
        CAST(NULL AS FLOAT) AS ESPERADO,
        CAST(NULL AS FLOAT) AS PESO_CATEGORIA,
        CAST(NULL AS FLOAT) AS PESO_GRUPO,
        CAST(NULL AS FLOAT) AS PUNTAJE,
        CAST(NULL AS INTEGER) AS FLAG,
        CAST(NULL AS VARCHAR(255) CHARACTER SET UNICODE NOT CASESPECIFIC) AS GRUPO_CATEGORIA,
        CAST(PERIODO || '_' || REG_EV AS VARCHAR(255)) AS CODIGO
    FROM (
        SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('AGRADECE_ESPERA' AS VARCHAR(255)) AS CATEGORIA, AGRADECE_ESPERA AS IND FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('BENEFIT'                AS VARCHAR(255)), BENEFIT                FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('BN_MANEJA_OBJECIONES'   AS VARCHAR(255)), BN_MANEJA_OBJECIONES   FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('PERFILAMIENTO'          AS VARCHAR(255)), PERFILAMIENTO          FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('LEVANT_INF'             AS VARCHAR(255)), LEVANT_INF             FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('CO_CTA_NEG'             AS VARCHAR(255)), CO_CTA_NEG             FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('CO_CONT_CAP_TRAB'       AS VARCHAR(255)), CO_CONT_CAP_TRAB       FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('CO_CONT_NA_AGIL'        AS VARCHAR(255)), CO_CONT_NA_AGIL        FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('CO_CONT_NA_AGIL_CD'     AS VARCHAR(255)), CO_CONT_NA_AGIL_CD     FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('CIERRE_COMERCIAL'       AS VARCHAR(255)), CIERRE_COMERCIAL       FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('360_BENEFICIOS'         AS VARCHAR(255)), "360_BENEFICIOS"       FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('360_CONTRATO'           AS VARCHAR(255)), "360_CONTRATO"         FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('360_OFRECIMIENTO'       AS VARCHAR(255)), "360_OFRECIMIENTO"     FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('COMPRA_PROTEGIDA'       AS VARCHAR(255)), COMPRA_PROTEGIDA       FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('CON_APERT_CUENTA'       AS VARCHAR(255)), CON_APERT_CUENTA       FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('CON_BENEFICIOS'         AS VARCHAR(255)), CON_BENEFICIOS         FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('CON_CONTRATO'           AS VARCHAR(255)), CON_CONTRATO           FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('CON_MANEJA_OBJECION'    AS VARCHAR(255)), CON_MANEJA_OBJECION    FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('CON_OFRECIMIENTO'       AS VARCHAR(255)), CON_OFRECIMIENTO       FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('CON_VENTAJAS_PRODUCTO'  AS VARCHAR(255)), CON_VENTAJAS_PRODUCTO  FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('CONS_INICIAL_TRANSV'    AS VARCHAR(255)), CONS_INICIAL_TRANSV    FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('COORD_TC'               AS VARCHAR(255)), COORD_TC               FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('DESPEDIDA'              AS VARCHAR(255)), DESPEDIDA              FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('DISP_EFECTIVO'          AS VARCHAR(255)), DISP_EFECTIVO          FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('EC_CONTRATO'            AS VARCHAR(255)), EC_CONTRATO            FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('EC_CONTRATO_SEGURO'     AS VARCHAR(255)), EC_CONTRATO_SEGURO     FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('EC_DOC_POLIZA'          AS VARCHAR(255)), EC_DOC_POLIZA          FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('EC_INTERES_MORATORIO'   AS VARCHAR(255)), EC_INTERES_MORATORIO   FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('EC_LINEA_PARALELA'      AS VARCHAR(255)), EC_LINEA_PARALELA      FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('EC_MANEJA_OBJECION'     AS VARCHAR(255)), EC_MANEJA_OBJECION     FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('EC_PLAZO_CUOTA'         AS VARCHAR(255)), EC_PLAZO_CUOTA         FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('EC_SEG_OPCIONAL'        AS VARCHAR(255)), EC_SEG_OPCIONAL        FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('EC_TASA_TCEA'           AS VARCHAR(255)), EC_TASA_TCEA           FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('EDUCA_CLIENTE'          AS VARCHAR(255)), EDUCA_CLIENTE          FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('IL_CONTRATO'            AS VARCHAR(255)), IL_CONTRATO            FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('IL_OFRECIMIENTO'        AS VARCHAR(255)), IL_OFRECIMIENTO        FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('LPDP'                   AS VARCHAR(255)), LPDP                   FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('LINEA_PARALELA'         AS VARCHAR(255)), LINEA_PARALELA         FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('MANEJA_OBJECIONES'      AS VARCHAR(255)), MANEJA_OBJECIONES      FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('MEMBRESIA'              AS VARCHAR(255)), MEMBRESIA              FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('OFF_CROSS_TC'           AS VARCHAR(255)), OFF_CROSS_TC           FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('OFF_SEG_OPCIONAL'       AS VARCHAR(255)), OFF_SEG_OPCIONAL       FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('PA_CONTRATO'            AS VARCHAR(255)), PA_CONTRATO            FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('PA_OFRECIMIENTO'        AS VARCHAR(255)), PA_OFRECIMIENTO        FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('PP_AP_CUENTA'           AS VARCHAR(255)), PP_AP_CUENTA           FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('PP_ENDOSO'              AS VARCHAR(255)), PP_ENDOSO              FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('PP_MANEJA_OBJECION'     AS VARCHAR(255)), PP_MANEJA_OBJECION     FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('PP_MONTO'               AS VARCHAR(255)), PP_MONTO               FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('PP_OFF_SEG'             AS VARCHAR(255)), PP_OFF_SEG             FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('PP_SEG_DESG'            AS VARCHAR(255)), PP_SEG_DESG            FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('PP_TASA_CUOTA'          AS VARCHAR(255)), PP_TASA_CUOTA          FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('SALUDO'                 AS VARCHAR(255)), SALUDO                 FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('SERV_ASOCIADOS'         AS VARCHAR(255)), SERV_ASOCIADOS         FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('SESENTA_MESES'          AS VARCHAR(255)), SESENTA_MESES          FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('TC_SEG_DESG'            AS VARCHAR(255)), TC_SEG_DESG            FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('TCA_CONTRATO'           AS VARCHAR(255)), TCA_CONTRATO           FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('TCEA'                   AS VARCHAR(255)), TCEA                   FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('UPG_OFRECIMIENTO'       AS VARCHAR(255)), UPG_OFRECIMIENTO       FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('TCA_OFRECIMIENTO'       AS VARCHAR(255)), TCA_OFRECIMIENTO       FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('TEA'                    AS VARCHAR(255)), TEA                    FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('UPG_CONTRATO'           AS VARCHAR(255)), UPG_CONTRATO           FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('VISA_ACCESS'            AS VARCHAR(255)), VISA_ACCESS            FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('VIVE_BENEFICIOS'        AS VARCHAR(255)), VIVE_BENEFICIOS        FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('VIVE_CONTRATO'          AS VARCHAR(255)), VIVE_CONTRATO          FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('VIVE_OFRECIMIENTO'      AS VARCHAR(255)), VIVE_OFRECIMIENTO      FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('SIMULACION'             AS VARCHAR(255)), SIMULACION             FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('CD_APERTURA_CUENTA'     AS VARCHAR(255)), CD_APERTURA_CUENTA     FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('CD_SEGURO_DESG'         AS VARCHAR(255)), CD_SEGURO_DESG         FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('CD_VISA_ACCESS'         AS VARCHAR(255)), CD_VISA_ACCESS         FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('CD_CONTRATO'            AS VARCHAR(255)), CD_CONTRATO            FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('CD_DOC_CONTRACTUALES'   AS VARCHAR(255)), CD_DOC_CONTRACTUALES   FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('CD_ENDOSO_SEGURO'       AS VARCHAR(255)), CD_ENDOSO_SEGURO       FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('CD_PLAZO_CUOTA'         AS VARCHAR(255)), CD_PLAZO_CUOTA         FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('CD_TASA_TEA'            AS VARCHAR(255)), CD_TASA_TEA            FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('CD_TC_COMPRA'           AS VARCHAR(255)), CD_TC_COMPRA           FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('CD_CROSS_PA'            AS VARCHAR(255)), CD_CROSS_PA            FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('CD_MANEJA_OBJECIONES'   AS VARCHAR(255)), CD_MANEJA_OBJECIONES   FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('CD_CIERRE_COMERCIAL'    AS VARCHAR(255)), CD_CIERRE_COMERCIAL    FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('CD_COMUNICA_VENTAJAS'   AS VARCHAR(255)), CD_COMUNICA_VENTAJAS   FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('CD_TASA_PREFERENCIAL'   AS VARCHAR(255)), CD_TASA_PREFERENCIAL   FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('RET_COORD_ENTREGA'      AS VARCHAR(255)), RET_COORD_ENTREGA      FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('RET_EXO_MEMBRESIA'      AS VARCHAR(255)), RET_EXO_MEMBRESIA      FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('RET_ABONO_MILLAS'       AS VARCHAR(255)), RET_ABONO_MILLAS       FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('RET_CAMBIO_TC'          AS VARCHAR(255)), RET_CAMBIO_TC          FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('RET_DEVOL_COMISIONES'   AS VARCHAR(255)), RET_DEVOL_COMISIONES   FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('RET_UNIFICA_LINEAS'     AS VARCHAR(255)), RET_UNIFICA_LINEAS     FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('RET_CON_COMPRA_DEUDA'   AS VARCHAR(255)), RET_CON_COMPRA_DEUDA   FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('RET_CON_EVAL_BOLETA'    AS VARCHAR(255)), RET_CON_EVAL_BOLETA    FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('RET_CON_RET_POR_AMPLIACION'  AS VARCHAR(255)), RET_CON_RET_POR_AMPLIACION  FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('RET_CON_DEVOL_CUOTAS'        AS VARCHAR(255)), RET_CON_DEVOL_CUOTAS        FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('RET_CON_RET_POR_BTASA'       AS VARCHAR(255)), RET_CON_RET_POR_BTASA       FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('RET_CON_RET_SOL_CANCELACION' AS VARCHAR(255)), RET_CON_RET_SOL_CANCELACION FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('RET_CON_RET_SOL_CRONOGRAMA'  AS VARCHAR(255)), RET_CON_RET_SOL_CRONOGRAMA  FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('RET_CON_RET_SOL_DEUDA_TOTAL' AS VARCHAR(255)), RET_CON_RET_SOL_DEUDA_TOTAL FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('RET_CON_RET_SOL_TASA'        AS VARCHAR(255)), RET_CON_RET_SOL_TASA        FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('BNC_IZIPAY_YA'              AS VARCHAR(255)), BNC_IZIPAY_YA              FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('BNC_IZI_MIGRA'              AS VARCHAR(255)), BNC_IZI_MIGRA              FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('BNC_IZI_VENTA_NUEVA'        AS VARCHAR(255)), BNC_IZI_VENTA_NUEVA        FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('BNC_PAGO_SERVICIO'          AS VARCHAR(255)), BNC_PAGO_SERVICIO          FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('BNC_PAGO_SUNAT'             AS VARCHAR(255)), BNC_PAGO_SUNAT             FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('BNC_PAGO_PLANILLAS'         AS VARCHAR(255)), BNC_PAGO_PLANILLAS         FROM VT_BASE_SPEECH
        UNION ALL SELECT PERIODO, PRODUCTO, REG_EV, NEVALUACION, CAST('BNC_TRADING'                AS VARCHAR(255)), BNC_TRADING                FROM VT_BASE_SPEECH
    ) unpivoted
) WITH DATA PRIMARY INDEX (PERIODO, PRODUCTO, REG_EV, NEVALUACION) ON COMMIT PRESERVE ROWS;


-- Eliminar tabla intermedia de promedios para liberar memoria/spool
DROP TABLE VT_BASE_SPEECH;

